In [1]:
import polars as pl
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import glob
import json
import numpy as np
from sklearn.cluster import KMeans
from datetime import datetime
from datetime import date
import re
from itertools import combinations
from collections import Counter
from sklearn.preprocessing import LabelEncoder
from scipy.sparse import csr_matrix
from scipy.sparse import coo_matrix
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfTransformer
from collections import defaultdict
import pyarrow.parquet as pq
import pyarrow as pa
from xgboost import XGBRegressor

In [13]:
item_df = pl.scan_parquet("data_full/sales_item/*.parquet")

purchase_history_df = pl.scan_parquet("data_full/sales_history/*.parquet")

user_df = pl.scan_parquet("data_full/sales_user/*.parquet")

In [14]:
print(item_df.explain(optimized=True))

Parquet SCAN [data_full\sales_item\sales_pers.item_chunk_0.parquet]
PROJECT */34 COLUMNS

In [15]:
print(user_df.explain(optimized=True))

Parquet SCAN [data_full\sales_user\sales_pers.user_chunk_0.parquet, ... 9 other sources]
PROJECT */18 COLUMNS

In [16]:
print(purchase_history_df.explain(optimized=True))

Parquet SCAN [data_full\sales_history\sales_pers.purchase_history_daily_chunk_0.parquet, ... 72 other sources]
PROJECT */16 COLUMNS

In [17]:
purchase_history_df[:1].collect()

shape: (1, 16)
┌────────────┬──────────────────────┬───────────────┬────────────┬───┬─────────┬──────────┬───────────────┬────────────┐
│ timestamp  ┆ user_id              ┆ item_id       ┆ event_type ┆ … ┆ payment ┆ location ┆ discount      ┆ is_deleted │
│ ---        ┆ ---                  ┆ ---           ┆ ---        ┆   ┆ ---     ┆ ---      ┆ ---           ┆ ---        │
│ i64        ┆ str                  ┆ str           ┆ str        ┆   ┆ str     ┆ i32      ┆ decimal[38,4] ┆ bool       │
╞════════════╪══════════════════════╪═══════════════╪════════════╪═══╪═════════╪══════════╪═══════════════╪════════════╡
│ 1735064221 ┆ ca12702ddf55acaa9fb7 ┆ 7115000000004 ┆ Purchase   ┆ … ┆ VietQR  ┆ 656      ┆ 0.0000        ┆ false      │
│            ┆ 67e10faaa6…          ┆               ┆            ┆   ┆         ┆          ┆               ┆            │
└────────────┴──────────────────────┴───────────────┴────────────┴───┴─────────┴──────────┴───────────────┴────────────┘

In [14]:
import polars as pl

result = (
    purchase_history_df
    .filter(
        (pl.col("created_date") >= pl.datetime(2025, 1, 1)) &
        (pl.col("created_date") <  pl.datetime(2025, 1, 31))
    )
    .collect()
)

print("Số dòng:", result.height)

Số dòng: 3298252

In [15]:
item_df[:1].collect()

shape: (1, 34)
┌───────┬─────────────────┬────────────────┬────────────────┬───┬───────────┬───────────┬─────────────┬────────────────┐
│ p_id  ┆ item_id         ┆ price          ┆ category_l1_id ┆ … ┆ volume    ┆ material  ┆ sale_status ┆ description_ne │
│ ---   ┆ ---             ┆ ---            ┆ ---            ┆   ┆ ---       ┆ ---       ┆ ---         ┆ w              │
│ i32   ┆ str             ┆ decimal[38,4]  ┆ i32            ┆   ┆ str       ┆ str       ┆ i32         ┆ ---            │
│       ┆                 ┆                ┆                ┆   ┆           ┆           ┆             ┆ str            │
╞═══════╪═════════════════╪════════════════╪════════════════╪═══╪═══════════╪═══════════╪═════════════╪════════════════╡
│ 17065 ┆ 0502020000004   ┆ 99000.0000     ┆ 1              ┆ … ┆ Không xác ┆ Không xác ┆ 0           ┆ Chi tiết sản   │
│       ┆                 ┆                ┆                ┆   ┆ định      ┆ định      ┆             ┆ phẩm           │
│       ┆                 ┆                ┆                ┆   ┆           ┆           ┆             ┆ …              │
└───────┴─────────────────┴────────────────┴────────────────┴───┴───────────┴───────────┴─────────────┴────────────────┘

In [16]:
user_df[:1].collect()

shape: (1, 18)
┌─────────────┬────────┬──────────┬─────────────┬───┬──────────────┬──────────┬───────────────────────────┬────────────┐
│ customer_id ┆ gender ┆ location ┆ province    ┆ … ┆ install_date ┆ district ┆ user_id                   ┆ is_deleted │
│ ---         ┆ ---    ┆ ---      ┆ ---         ┆   ┆ ---          ┆ ---      ┆ ---                       ┆ ---        │
│ i32         ┆ str    ┆ i32      ┆ str         ┆   ┆ i64          ┆ str      ┆ str                       ┆ bool       │
╞═════════════╪════════╪══════════╪═════════════╪═══╪══════════════╪══════════╪═══════════════════════════╪════════════╡
│ 14732       ┆ Nam    ┆ 155      ┆ Hồ Chí Minh ┆ … ┆ 1306281600   ┆ 7        ┆ e1e48206652bf8c279ff0206c ┆ false      │
│             ┆        ┆          ┆             ┆   ┆              ┆          ┆ 69a80…                    ┆            │
└─────────────┴────────┴──────────┴─────────────┴───┴──────────────┴──────────┴───────────────────────────┴────────────┘

In [17]:
#laebl encoding cột giới tính 
item_df_lazy = item_df.lazy()
item_df_lazy = item_df_lazy.with_columns([
    pl.when(pl.col("gender_target") == "Bé Gái").then(0)
      .when(pl.col("gender_target") == "Bé Trai").then(1)
      .when(pl.col("gender_target") == "Không xác định").then(2)
      .when(pl.col("gender_target") == "Sơ sinh").then(3)
      .when(pl.col("gender_target") == "Unisex").then(4)
      .otherwise(-1)
      .alias("gender_target")
])
item_df = item_df_lazy.collect()

In [18]:
# Tạo LazyFrame từ item_df
item_df_lazy = item_df.lazy()

# 1️⃣ Tìm top 10 brand được mua nhiều nhất
top_brands = (
    item_df_lazy
    .group_by("brand")
    .agg(pl.count().alias("brand_count"))
    .sort("brand_count", descending=True)
    .head(10)
    .collect()  # Lấy danh sách brand top 10
)
top_brand_list = top_brands["brand"].to_list()

# 2️⃣ Label encoding: top 10 giữ nguyên, các brand khác thành "Other"
item_df_lazy = item_df_lazy.with_columns([
    pl.when(pl.col("brand").is_in(top_brand_list))
      .then(pl.col("brand"))
      .otherwise(pl.lit("Other"))
      .alias("brand_mapped")
])

# 3️⃣ Tạo mapping brand → số
unique_brands = item_df_lazy.select("brand_mapped").unique().collect()["brand_mapped"].to_list()
brand_mapping = {b: i for i, b in enumerate(unique_brands)}

# 4️⃣ Áp dụng mapping
item_df_lazy = item_df_lazy.with_columns([
    pl.col("brand_mapped").map_elements(lambda x: brand_mapping.get(x, -1)).alias("brand")
]).drop("brand_mapped")


# 6️⃣ Khi cần, collect về DataFrame bình thường
item_df = item_df_lazy.collect()

print(item_df.select(["brand"]).head(15))
print(f"Tổng số brand sau khi mã hóa: {len(unique_brands)}")
print("Mapping:", brand_mapping)

shape: (15, 1)
┌───────┐
│ brand │
│ ---   │
│ i64   │
╞═══════╡
│ 2     │
│ 7     │
│ 0     │
│ 2     │
│ 2     │
│ …     │
│ 9     │
│ 2     │
│ 2     │
│ 2     │
│ 2     │
└───────┘
Tổng số brand sau khi mã hóa: 11
Mapping: {'Thương hiệu khác': 0, 'Mesuca': 1, 'Other': 2, 'TOYCITY': 3, 'ConCung Good': 4, 'Không xác định': 5, 'Pigeon': 6, 'Con Cưng': 7, 'Animo': 8, 'CF (ConCung Fashion)': 9, 'Nous': 10}

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_26976\1428647967.py:8: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .agg(pl.count().alias("brand_count"))

In [19]:
# 1️⃣ Tạo LazyFrame
purchase_lazy = purchase_history_df.lazy()
# 2️⃣ Lấy danh sách các channel unique
unique_channels = (
    purchase_lazy.select("channel")
    .unique()
    .collect()["channel"]
    .to_list()
)
# 3️⃣ Tạo mapping
channel_mapping = {ch: i for i, ch in enumerate(unique_channels)}
# 4️⃣  dụng mapping (Lazy)
purchase_lazy = purchase_lazy.with_columns([
    pl.col("channel").map_elements(lambda x: channel_mapping.get(x, -1)).alias("channel")
])
# 6️⃣ Khi cần collect về DataFrame bình thường
purchase_history_df = purchase_lazy.collect()
# 7️⃣ In ra kết quả
print("Mapping:", channel_mapping)
print(purchase_history_df.select("channel").head(10))

Mapping: {'iOS': 0, 'Wholesale': 1, 'SPE': 2, 'Không xác định': 3, 'Call': 4, 'Android': 5, 'TKS': 6, 'CRM Partner': 7, 'Web': 8, 'Chat': 9, 'In-Store': 10}
shape: (10, 1)
┌─────────┐
│ channel │
│ ---     │
│ i64     │
╞═════════╡
│ 10      │
│ 10      │
│ 10      │
│ 10      │
│ 5       │
│ 10      │
│ 10      │
│ 10      │
│ 10      │
│ 10      │
└─────────┘

In [20]:
# 1️⃣ Tạo LazyFrame
purchase_lazy = purchase_history_df.lazy()
# 2️⃣ Lấy danh sách các payment unique
unique_payments = (
    purchase_lazy.select("payment")
    .unique()
    .collect()["payment"]
    .to_list()
)
# 3️⃣ Tạo mapping
payment_mapping = {p: i for i, p in enumerate(unique_payments)}
# 4️⃣ Áp dụng mapping (Lazy)
purchase_lazy = purchase_lazy.with_columns([
    pl.col("payment").map_elements(lambda x: payment_mapping.get(x, -1)).alias("payment")
])
# 6️⃣ Khi cần collect về DataFrame bình thường
purchase_history_df = purchase_lazy.collect()
# 7️⃣ In kết quả
print("Mapping:", payment_mapping)
print(purchase_history_df.select("payment").head(10))

Mapping: {'VietQR': 0, 'Tiền mặt': 1, 'ShopeePay': 2, 'Không xác định': 3, 'ZaloPay': 4, 'VNPay': 5, 'Chuyển khoản': 6, 'Cà thẻ': 7, 'MoMo': 8, 'Kredivo': 9}
shape: (10, 1)
┌─────────┐
│ payment │
│ ---     │
│ i64     │
╞═════════╡
│ 0       │
│ 1       │
│ 8       │
│ 8       │
│ 8       │
│ 1       │
│ 1       │
│ 0       │
│ 0       │
│ 5       │
└─────────┘

In [21]:
# 1️⃣ Tạo LazyFrame từ user_df
user_lazy = user_df.lazy()
# 2️⃣ Lấy danh sách các giá trị gender duy nhất
unique_genders = (
    user_lazy.select("gender")
    .unique()
    .collect()["gender"]  # collect để lấy Series
    .to_list()
)
# 3️⃣ Tạo mapping
gender_mapping = {g: i for i, g in enumerate(unique_genders)}
# 4️⃣ In mapping ra
print("Mapping gender → số:")
for k, v in gender_mapping.items():
    print(f"{k} -> {v}")
# 5️⃣ Áp dụng mapping trên LazyFrame
user_lazy = user_lazy.with_columns([
    pl.col("gender").map_elements(lambda x: gender_mapping.get(x, -1)).alias("gender")
])
# 6️⃣ Khi cần, collect về DataFrame bình thường
user_df = user_lazy.collect()
# 7️⃣ Kiểm tra 10 dòng đầu
print(user_df.select("gender").head(10))

Mapping gender → số:
Khác -> 0
Nữ -> 1
Nam -> 2
shape: (10, 1)
┌────────┐
│ gender │
│ ---    │
│ i64    │
╞════════╡
│ 2      │
│ 1      │
│ 1      │
│ 1      │
│ 1      │
│ 1      │
│ 1      │
│ 1      │
│ 1      │
│ 1      │
└────────┘

In [22]:
# 1️⃣ Tạo LazyFrame từ user_df
user_lazy = user_df.lazy()
# 2️⃣ Lấy danh sách các membership duy nhất
unique_memberships = (
    user_lazy.select("membership")
    .unique()
    .collect()["membership"]  # collect để lấy giá trị ra Series
    .to_list()
)
# 3️⃣ Tạo mapping
membership_mapping = {m: i for i, m in enumerate(unique_memberships)}
print("Membership mapping:", membership_mapping)
# 4️⃣ Áp dụng mapping trên LazyFrame
user_lazy = user_lazy.with_columns([
    pl.col("membership").map_elements(lambda x: membership_mapping.get(x, -1)).alias("membership")
])
# 5️⃣ Khi cần, collect về DataFrame bình thường
user_df = user_lazy.collect()
# 6️⃣ In kết quả
print(user_df.select("membership").limit(10))

Membership mapping: {'Diamond': 0, 'Standard': 1, 'Gold': 2}
shape: (10, 1)
┌────────────┐
│ membership │
│ ---        │
│ i64        │
╞════════════╡
│ 1          │
│ 1          │
│ 1          │
│ 1          │
│ 1          │
│ 1          │
│ 1          │
│ 1          │
│ 1          │
│ 1          │
└────────────┘

In [23]:
# 1️⃣ Tạo LazyFrame từ user_df
user_lazy = user_df.lazy()
# 2️⃣ Lấy danh sách các giá trị region duy nhất
unique_regions = (
    user_lazy.select("region")
    .unique()
    .collect()["region"]  # collect để lấy Series
    .to_list()
)
# 3️⃣ Tạo mapping
region_mapping = {r: i for i, r in enumerate(unique_regions)}
# 4️⃣ In mapping ra
print("Mapping region → số:")
for k, v in region_mapping.items():
    print(f"{k} -> {v}")
# 5️⃣ Áp dụng mapping trên LazyFrame
user_lazy = user_lazy.with_columns([
    pl.col("region").map_elements(lambda x: region_mapping.get(x, -1)).alias("region")
])
# 6️⃣ Khi cần, collect về DataFrame bình thường
user_df = user_lazy.collect()
# 7️⃣ Kiểm tra 10 dòng đầu
print(user_df.select("region").head(10))

Mapping region → số:
Trung du và miền núi phía Bắc -> 0
Đồng bằng sông Cửu Long -> 1
Duyên hải Nam Trung Bộ -> 2
Đông Nam Bộ -> 3
Bắc Trung Bộ -> 4
Tây Nguyên -> 5
Đồng bằng sông Hồng -> 6
Duyên hải Bắc Bộ -> 7
shape: (10, 1)
┌────────┐
│ region │
│ ---    │
│ i64    │
╞════════╡
│ 3      │
│ 3      │
│ 1      │
│ 3      │
│ 3      │
│ 3      │
│ 3      │
│ 1      │
│ 3      │
│ 3      │
└────────┘

In [24]:
# 1️⃣ Tạo LazyFrame từ user_df
user_lazy = user_df.lazy()
# 2️⃣ Lấy danh sách các giá trị install_app duy nhất
unique_install_apps = (
    user_lazy.select("install_app")
    .unique()
    .collect()["install_app"]
    .to_list()
)
# 3️⃣ Tạo mapping
install_app_mapping = {app: i for i, app in enumerate(unique_install_apps)}
# 4️⃣ In mapping ra
print("Mapping install_app → số:")
for k, v in install_app_mapping.items():
    print(f"{k} -> {v}")
# 5️⃣ Áp dụng mapping trên LazyFrame
user_lazy = user_lazy.with_columns([
    pl.col("install_app")
      .map_elements(lambda x: install_app_mapping.get(x, -1), return_dtype=pl.Int32)
      .alias("install_app")
])
# 6️⃣ Khi cần, collect về DataFrame bình thường
user_df = user_lazy.collect()
# 7️⃣ Kiểm tra 10 dòng đầu
print(user_df.select("install_app").head(10))

Mapping install_app → số:
Web -> 0
CRM Partner -> 1
Android -> 2
In-Store -> 3
iOS -> 4
Chat -> 5
LZD -> 6
SPE -> 7
Wholesale -> 8
Call -> 9
Không xác định -> 10
shape: (10, 1)
┌─────────────┐
│ install_app │
│ ---         │
│ i32         │
╞═════════════╡
│ 3           │
│ 3           │
│ 3           │
│ 3           │
│ 3           │
│ 3           │
│ 3           │
│ 3           │
│ 3           │
│ 3           │
└─────────────┘

In [25]:
# 1️⃣ Tạo LazyFrame từ user_df
user_lazy = user_df.lazy()
# 2️⃣ Chuẩn hóa province
user_lazy = user_lazy.with_columns(
    pl.col("province")
      .str.strip_chars()
      .str.replace("Tỉnh ", "")
      .str.replace("Thành phố ", "")
      .str.replace("Thành Phố ", "")
      .alias("province")
)
# 3️⃣ Lấy danh sách tỉnh duy nhất, sắp xếp và tạo mapping
province_list = (
    user_lazy.select("province")
    .unique()
    .sort("province")
    .collect()
    .to_series()
    .to_list()
)
province_mapping = {prov: i for i, prov in enumerate(province_list)}
# 4️⃣ Áp dụng mapping trên LazyFrame
user_lazy = user_lazy.with_columns(
    pl.col("province").map_elements(lambda x: province_mapping.get(x, -1), return_dtype=pl.Int32).alias("province")
)
# 5️⃣ Collect về DataFrame bình thường
user_df = user_lazy.collect()
# 6️⃣ Kiểm tra 10 dòng đầu
print(user_df.select("province").head(10))

shape: (10, 1)
┌──────────┐
│ province │
│ ---      │
│ i32      │
╞══════════╡
│ 24       │
│ 24       │
│ 10       │
│ 24       │
│ 24       │
│ 24       │
│ 24       │
│ 13       │
│ 24       │
│ 24       │
└──────────┘

In [26]:
# 1️⃣ Tạo LazyFrame
purchase_lazy = purchase_history_df.lazy()
# 2️⃣ Tính quantile 0.99
q99_df = purchase_lazy.select(pl.col("price").quantile(0.99)).collect()
p99 = q99_df.to_numpy()[0][0]
print(f"Quantile 0.99 của price: {p99}")
# 3️⃣ Cắt outlier và log1p trên LazyFrame
purchase_lazy = purchase_lazy.with_columns(
    pl.when(pl.col("price") > p99)
      .then(p99)
      .otherwise(pl.col("price"))
      .log1p()
      .alias("price")
)
# 4️⃣ Collect về DataFrame bình thường
purchase_history_df = purchase_lazy.collect()
# 5️⃣ Kiểm tra 10 dòng đầu
print(purchase_history_df.select(["price"]).head(10))

Quantile 0.99 của price: 805000.0
shape: (10, 1)
┌───────────┐
│ price     │
│ ---       │
│ f64       │
╞═══════════╡
│ 10.799596 │
│ 11.141876 │
│ 11.225257 │
│ 10.976799 │
│ 11.396403 │
│ 11.133678 │
│ 12.594734 │
│ 12.301387 │
│ 12.594734 │
│ 9.615872  │
└───────────┘

In [ ]:
# ------------------------------------------------
# 1. FILTER PURCHASE + CLEAN DATE
# ------------------------------------------------
df = (
    purchase_history_df
    .filter(
        (pl.col("event_type") == "Purchase") &
        (pl.col("is_deleted") == False) &
        (pl.col("created_date").is_not_null())
    )
    .select([
        "customer_id",
        "item_id",
        "quantity",
        "price",
        "discount",
        "created_date"
    ])
)

now = pl.lit(pd.Timestamp.now())

df = df.with_columns(
    (now - pl.col("created_date"))
        .dt.total_days()
        .clip(lower_bound=0)
        .alias("days_ago")
)

df = df.with_columns(
    (
        (pl.col("quantity") * pl.col("price") - pl.col("discount"))
        * pl.col("days_ago").map_elements(lambda x: np.exp(-0.01 * x))
    ).alias("score")
)

# ------------------------------------------------
# 2. AGG USER–ITEM
# ------------------------------------------------
ui = (
    df.group_by(["customer_id", "item_id"])
      .agg(pl.col("score").sum())
      .filter(pl.col("score").is_finite())
)

ui_pd = ui.to_pandas()

# ------------------------------------------------
# 3. BUILD MATRIX
# ------------------------------------------------
user_map = {u: i for i, u in enumerate(ui_pd["customer_id"].unique())}
item_map = {i: j for j, i in enumerate(ui_pd["item_id"].unique())}
inv_item_map = {v: k for k, v in item_map.items()}

ui_pd["u_idx"] = ui_pd["customer_id"].map(user_map)
ui_pd["i_idx"] = ui_pd["item_id"].map(item_map)

matrix = csr_matrix(
    (ui_pd["score"], (ui_pd["u_idx"], ui_pd["i_idx"]))
)

item_user_matrix = matrix.T  # (num_items, num_users)

# ------------------------------------------------
# 4. ITEM-CF (COSINE)
# ------------------------------------------------
item_similarity_cf = cosine_similarity(
    item_user_matrix,
    dense_output=False
)

item_importance_cf = np.array(
    item_similarity_cf.sum(axis=1)
).ravel()

top_cf = (
    pd.DataFrame({
        "item_id": [inv_item_map[i] for i in range(len(item_importance_cf))],
        "score_cf": item_importance_cf
    })
    .sort_values("score_cf", ascending=False)
    .head(40)
)

# ------------------------------------------------
# 5. PMI / PPMI
# ------------------------------------------------
binary_matrix = item_user_matrix.copy()
binary_matrix.data = np.ones_like(binary_matrix.data)

# Co-occurrence
C = (binary_matrix @ binary_matrix.T).tocoo()
C.setdiag(0)

# Frequencies
item_freq = np.array(C.sum(axis=1)).ravel()
total = item_freq.sum()
item_freq[item_freq == 0] = 1e-9

# ==== PMI tính trực tiếp trên non-zero entries ====
rows = C.row
cols = C.col
data = C.data

pmi_data = np.log((data * total) / (item_freq[rows] * item_freq[cols]))
pmi_data[pmi_data < 0] = 0  # PPMI

PMI = coo_matrix((pmi_data, (rows, cols)), shape=C.shape)

# Item importance
item_importance_pmi = np.array(PMI.sum(axis=1)).ravel()

top_pmi = (
    pd.DataFrame({
        "item_id": [inv_item_map[i] for i in range(len(item_importance_pmi))],
        "score_pmi": item_importance_pmi
    })
    .sort_values("score_pmi", ascending=False)
    .head(40)
)

# ------------------------------------------------
# 6. TOP 500 POPULAR
# ------------------------------------------------
top_popularity = (
    purchase_history_df
    .filter(
        (pl.col("event_type") == "Purchase") &
        (pl.col("is_deleted") == False)
    )
    .group_by("item_id")
    .agg(pl.count().alias("num_transactions"))
    .sort("num_transactions", descending=True)
    .head(30)
    .select("item_id")
    .to_pandas()
)

# ------------------------------------------------
# 7. FINAL CANDIDATE
# ------------------------------------------------
final_candidate_items = (
    pd.concat([
        top_cf[["item_id"]],
        top_pmi[["item_id"]],
        top_popularity[["item_id"]]
    ])
    .drop_duplicates()
    .reset_index(drop=True)
)

final_candidate_items.to_parquet(
    "final_candidate_items.parquet",
    index=False
)
df_final = pl.read_parquet("final_candidate_items.parquet")
print(f"Number of items in final file: {df_final.height}")

In [27]:
# ------------------------------------------------
# 1. Chọn giao dịch hợp lệ (Purchase, chưa xoá, có ngày)
# ------------------------------------------------
df = purchase_history_df.filter(
    (pl.col("event_type") == "Purchase") &
    (pl.col("is_deleted") == False) &
    (pl.col("created_date").is_not_null())
)

# Nếu created_date là string → parse
if df.schema["created_date"] == pl.Utf8:
    df = df.with_columns(
        pl.col("created_date").str.strptime(pl.Datetime, strict=False)
    )

# ------------------------------------------------
# 2. Lọc giao dịch trong năm 2024–2025
# ------------------------------------------------
df_2024_2025 = df.filter(
    pl.col("created_date").dt.year().is_in([2024, 2025])
)

# ------------------------------------------------
# 3. Khách hàng có ≥ 2 giao dịch
# ------------------------------------------------
final_active_customers = (
    df_2024_2025
    .group_by("customer_id")
    .agg(pl.len().alias("num_orders"))
    .filter(pl.col("num_orders") >= 2)
    .select("customer_id")
)

print(
    "Số khách hàng có ≥2 giao dịch trong năm 2024–2025:",
    final_active_customers.height
)

# ------------------------------------------------
# 4. Lưu parquet
# ------------------------------------------------
final_active_customers.write_parquet("customer_list.parquet")

Số khách hàng có ≥2 giao dịch trong năm 2024–2025: 1924932

In [46]:
import polars as pl
import math

# Load dữ liệu
customers = pl.read_parquet("customer_list.parquet").select("customer_id")
items = pl.read_parquet("final_candidate_items.parquet").select("item_id")

n_items = items.height
target_rows_per_chunk = 1_000_000

# Số customer mỗi chunk ≈ 1M / n_items
customers_per_chunk = max(1, target_rows_per_chunk // n_items)

print("Items:", n_items)
print("Customers per chunk:", customers_per_chunk)

total_customers = customers.height
chunk_idx = 0
total_rows = 0

for start in range(0, total_customers, customers_per_chunk):
    cust_chunk = customers.slice(start, customers_per_chunk)

    joined = cust_chunk.join(items, how="cross")
    rows = joined.height
    total_rows += rows

    out_file = f"customer_item_keys_chunk_{chunk_idx}.parquet"
    joined.write_parquet(out_file)

    print(f"Saved {out_file} with {rows:,} rows")

    chunk_idx += 1

print(f"Total rows generated: {total_rows:,}")

Items: 97
Customers per chunk: 10309
Saved customer_item_keys_chunk_0.parquet with 999,973 rows
Saved customer_item_keys_chunk_1.parquet with 999,973 rows
Saved customer_item_keys_chunk_2.parquet with 999,973 rows
Saved customer_item_keys_chunk_3.parquet with 999,973 rows
Saved customer_item_keys_chunk_4.parquet with 999,973 rows
Saved customer_item_keys_chunk_5.parquet with 999,973 rows
Saved customer_item_keys_chunk_6.parquet with 999,973 rows
Saved customer_item_keys_chunk_7.parquet with 999,973 rows
Saved customer_item_keys_chunk_8.parquet with 999,973 rows
Saved customer_item_keys_chunk_9.parquet with 999,973 rows
Saved customer_item_keys_chunk_10.parquet with 999,973 rows
Saved customer_item_keys_chunk_11.parquet with 999,973 rows
Saved customer_item_keys_chunk_12.parquet with 999,973 rows
Saved customer_item_keys_chunk_13.parquet with 999,973 rows
Saved customer_item_keys_chunk_14.parquet with 999,973 rows
Saved customer_item_keys_chunk_15.parquet with 999,973 rows
Saved customer_item_keys_chunk_16.parquet with 999,973 rows
Saved customer_item_keys_chunk_17.parquet with 999,973 rows
Saved customer_item_keys_chunk_18.parquet with 999,973 rows
Saved customer_item_keys_chunk_19.parquet with 999,973 rows
Saved customer_item_keys_chunk_20.parquet with 999,973 rows
Saved customer_item_keys_chunk_21.parquet with 999,973 rows
Saved customer_item_keys_chunk_22.parquet with 999,973 rows
Saved customer_item_keys_chunk_23.parquet with 999,973 rows
Saved customer_item_keys_chunk_24.parquet with 999,973 rows
Saved customer_item_keys_chunk_25.parquet with 999,973 rows
Saved customer_item_keys_chunk_26.parquet with 999,973 rows
Saved customer_item_keys_chunk_27.parquet with 999,973 rows
Saved customer_item_keys_chunk_28.parquet with 999,973 rows
Saved customer_item_keys_chunk_29.parquet with 999,973 rows
Saved customer_item_keys_chunk_30.parquet with 999,973 rows
Saved customer_item_keys_chunk_31.parquet with 999,973 rows
Saved customer_item_keys_chunk_32.parquet with 999,973 rows
Saved customer_item_keys_chunk_33.parquet with 999,973 rows
Saved customer_item_keys_chunk_34.parquet with 999,973 rows
Saved customer_item_keys_chunk_35.parquet with 999,973 rows
Saved customer_item_keys_chunk_36.parquet with 999,973 rows
Saved customer_item_keys_chunk_37.parquet with 999,973 rows
Saved customer_item_keys_chunk_38.parquet with 999,973 rows
Saved customer_item_keys_chunk_39.parquet with 999,973 rows
Saved customer_item_keys_chunk_40.parquet with 999,973 rows
Saved customer_item_keys_chunk_41.parquet with 999,973 rows
Saved customer_item_keys_chunk_42.parquet with 999,973 rows
Saved customer_item_keys_chunk_43.parquet with 999,973 rows
Saved customer_item_keys_chunk_44.parquet with 999,973 rows
Saved customer_item_keys_chunk_45.parquet with 999,973 rows
Saved customer_item_keys_chunk_46.parquet with 999,973 rows
Saved customer_item_keys_chunk_47.parquet with 999,973 rows
Saved customer_item_keys_chunk_48.parquet with 999,973 rows
Saved customer_item_keys_chunk_49.parquet with 999,973 rows
Saved customer_item_keys_chunk_50.parquet with 999,973 rows
Saved customer_item_keys_chunk_51.parquet with 999,973 rows
Saved customer_item_keys_chunk_52.parquet with 999,973 rows
Saved customer_item_keys_chunk_53.parquet with 999,973 rows
Saved customer_item_keys_chunk_54.parquet with 999,973 rows
Saved customer_item_keys_chunk_55.parquet with 999,973 rows
Saved customer_item_keys_chunk_56.parquet with 999,973 rows
Saved customer_item_keys_chunk_57.parquet with 999,973 rows
Saved customer_item_keys_chunk_58.parquet with 999,973 rows
Saved customer_item_keys_chunk_59.parquet with 999,973 rows
Saved customer_item_keys_chunk_60.parquet with 999,973 rows
Saved customer_item_keys_chunk_61.parquet with 999,973 rows
Saved customer_item_keys_chunk_62.parquet with 999,973 rows
Saved customer_item_keys_chunk_63.parquet with 999,973 rows
Saved customer_item_keys_chunk_64.parquet with 999,973 rows
Saved customer_item_keys_chunk_65.parquet with 999,973 rows
Saved customer_item_keys_chunk_66.parquet with 999,973 rows
Saved customer_item_keys_chunk_67.parquet with 999,973 rows
Saved customer_item_keys_chunk_68.parquet with 999,973 rows
Saved customer_item_keys_chunk_69.parquet with 999,973 rows
Saved customer_item_keys_chunk_70.parquet with 999,973 rows
Saved customer_item_keys_chunk_71.parquet with 999,973 rows
Saved customer_item_keys_chunk_72.parquet with 999,973 rows
Saved customer_item_keys_chunk_73.parquet with 999,973 rows
Saved customer_item_keys_chunk_74.parquet with 999,973 rows
Saved customer_item_keys_chunk_75.parquet with 999,973 rows
Saved customer_item_keys_chunk_76.parquet with 999,973 rows
Saved customer_item_keys_chunk_77.parquet with 999,973 rows
Saved customer_item_keys_chunk_78.parquet with 999,973 rows
Saved customer_item_keys_chunk_79.parquet with 999,973 rows
Saved customer_item_keys_chunk_80.parquet with 999,973 rows
Saved customer_item_keys_chunk_81.parquet with 999,973 rows
Saved customer_item_keys_chunk_82.parquet with 999,973 rows
Saved customer_item_keys_chunk_83.parquet with 999,973 rows
Saved customer_item_keys_chunk_84.parquet with 999,973 rows
Saved customer_item_keys_chunk_85.parquet with 999,973 rows
Saved customer_item_keys_chunk_86.parquet with 999,973 rows
Saved customer_item_keys_chunk_87.parquet with 999,973 rows
Saved customer_item_keys_chunk_88.parquet with 999,973 rows
Saved customer_item_keys_chunk_89.parquet with 999,973 rows
Saved customer_item_keys_chunk_90.parquet with 999,973 rows
Saved customer_item_keys_chunk_91.parquet with 999,973 rows
Saved customer_item_keys_chunk_92.parquet with 999,973 rows
Saved customer_item_keys_chunk_93.parquet with 999,973 rows
Saved customer_item_keys_chunk_94.parquet with 999,973 rows
Saved customer_item_keys_chunk_95.parquet with 999,973 rows
Saved customer_item_keys_chunk_96.parquet with 999,973 rows
Saved customer_item_keys_chunk_97.parquet with 999,973 rows
Saved customer_item_keys_chunk_98.parquet with 999,973 rows
Saved customer_item_keys_chunk_99.parquet with 999,973 rows
Saved customer_item_keys_chunk_100.parquet with 999,973 rows
Saved customer_item_keys_chunk_101.parquet with 999,973 rows
Saved customer_item_keys_chunk_102.parquet with 999,973 rows
Saved customer_item_keys_chunk_103.parquet with 999,973 rows
Saved customer_item_keys_chunk_104.parquet with 999,973 rows
Saved customer_item_keys_chunk_105.parquet with 999,973 rows
Saved customer_item_keys_chunk_106.parquet with 999,973 rows
Saved customer_item_keys_chunk_107.parquet with 999,973 rows
Saved customer_item_keys_chunk_108.parquet with 999,973 rows
Saved customer_item_keys_chunk_109.parquet with 999,973 rows
Saved customer_item_keys_chunk_110.parquet with 999,973 rows
Saved customer_item_keys_chunk_111.parquet with 999,973 rows
Saved customer_item_keys_chunk_112.parquet with 999,973 rows
Saved customer_item_keys_chunk_113.parquet with 999,973 rows
Saved customer_item_keys_chunk_114.parquet with 999,973 rows
Saved customer_item_keys_chunk_115.parquet with 999,973 rows
Saved customer_item_keys_chunk_116.parquet with 999,973 rows
Saved customer_item_keys_chunk_117.parquet with 999,973 rows
Saved customer_item_keys_chunk_118.parquet with 999,973 rows
Saved customer_item_keys_chunk_119.parquet with 999,973 rows
Saved customer_item_keys_chunk_120.parquet with 999,973 rows
Saved customer_item_keys_chunk_121.parquet with 999,973 rows
Saved customer_item_keys_chunk_122.parquet with 999,973 rows
Saved customer_item_keys_chunk_123.parquet with 999,973 rows
Saved customer_item_keys_chunk_124.parquet with 999,973 rows
Saved customer_item_keys_chunk_125.parquet with 999,973 rows
Saved customer_item_keys_chunk_126.parquet with 999,973 rows
Saved customer_item_keys_chunk_127.parquet with 999,973 rows
Saved customer_item_keys_chunk_128.parquet with 999,973 rows
Saved customer_item_keys_chunk_129.parquet with 999,973 rows
Saved customer_item_keys_chunk_130.parquet with 999,973 rows
Saved customer_item_keys_chunk_131.parquet with 999,973 rows
Saved customer_item_keys_chunk_132.parquet with 999,973 rows
Saved customer_item_keys_chunk_133.parquet with 999,973 rows
Saved customer_item_keys_chunk_134.parquet with 999,973 rows
Saved customer_item_keys_chunk_135.parquet with 999,973 rows
Saved customer_item_keys_chunk_136.parquet with 999,973 rows
Saved customer_item_keys_chunk_137.parquet with 999,973 rows
Saved customer_item_keys_chunk_138.parquet with 999,973 rows
Saved customer_item_keys_chunk_139.parquet with 999,973 rows
Saved customer_item_keys_chunk_140.parquet with 999,973 rows
Saved customer_item_keys_chunk_141.parquet with 999,973 rows
Saved customer_item_keys_chunk_142.parquet with 999,973 rows
Saved customer_item_keys_chunk_143.parquet with 999,973 rows
Saved customer_item_keys_chunk_144.parquet with 999,973 rows
Saved customer_item_keys_chunk_145.parquet with 999,973 rows
Saved customer_item_keys_chunk_146.parquet with 999,973 rows
Saved customer_item_keys_chunk_147.parquet with 999,973 rows
Saved customer_item_keys_chunk_148.parquet with 999,973 rows
Saved customer_item_keys_chunk_149.parquet with 999,973 rows
Saved customer_item_keys_chunk_150.parquet with 999,973 rows
Saved customer_item_keys_chunk_151.parquet with 999,973 rows
Saved customer_item_keys_chunk_152.parquet with 999,973 rows
Saved customer_item_keys_chunk_153.parquet with 999,973 rows
Saved customer_item_keys_chunk_154.parquet with 999,973 rows
Saved customer_item_keys_chunk_155.parquet with 999,973 rows
Saved customer_item_keys_chunk_156.parquet with 999,973 rows
Saved customer_item_keys_chunk_157.parquet with 999,973 rows
Saved customer_item_keys_chunk_158.parquet with 999,973 rows
Saved customer_item_keys_chunk_159.parquet with 999,973 rows
Saved customer_item_keys_chunk_160.parquet with 999,973 rows
Saved customer_item_keys_chunk_161.parquet with 999,973 rows
Saved customer_item_keys_chunk_162.parquet with 999,973 rows
Saved customer_item_keys_chunk_163.parquet with 999,973 rows
Saved customer_item_keys_chunk_164.parquet with 999,973 rows
Saved customer_item_keys_chunk_165.parquet with 999,973 rows
Saved customer_item_keys_chunk_166.parquet with 999,973 rows
Saved customer_item_keys_chunk_167.parquet with 999,973 rows
Saved customer_item_keys_chunk_168.parquet with 999,973 rows
Saved customer_item_keys_chunk_169.parquet with 999,973 rows
Saved customer_item_keys_chunk_170.parquet with 999,973 rows
Saved customer_item_keys_chunk_171.parquet with 999,973 rows
Saved customer_item_keys_chunk_172.parquet with 999,973 rows
Saved customer_item_keys_chunk_173.parquet with 999,973 rows
Saved customer_item_keys_chunk_174.parquet with 999,973 rows
Saved customer_item_keys_chunk_175.parquet with 999,973 rows
Saved customer_item_keys_chunk_176.parquet with 999,973 rows
Saved customer_item_keys_chunk_177.parquet with 999,973 rows
Saved customer_item_keys_chunk_178.parquet with 999,973 rows
Saved customer_item_keys_chunk_179.parquet with 999,973 rows
Saved customer_item_keys_chunk_180.parquet with 999,973 rows
Saved customer_item_keys_chunk_181.parquet with 999,973 rows
Saved customer_item_keys_chunk_182.parquet with 999,973 rows
Saved customer_item_keys_chunk_183.parquet with 999,973 rows
Saved customer_item_keys_chunk_184.parquet with 999,973 rows
Saved customer_item_keys_chunk_185.parquet with 999,973 rows
Saved customer_item_keys_chunk_186.parquet with 723,426 rows
Total rows generated: 186,718,404

In [20]:
begin_hist = datetime.strptime('2024-01-01', '%Y-%m-%d')
end_hist   = datetime.strptime('2024-11-30', '%Y-%m-%d')
begin_recent = datetime.strptime('2024-05-01', '%Y-%m-%d')
end_recent   = datetime.strptime('2025-01-31', '%Y-%m-%d')
#begin_val = datetime.strptime('2024-12-01', '%Y-%m-%d')
#end_val   = datetime.strptime('2024-12-31', '%Y-%m-%d')
#begin_test =datetime.strptime('2025-01-01', '%Y-%m-%d')
#end_test=datetime.strptime('2025-01-31', '%Y-%m-%d')
train_history = purchase_history_df.lazy().filter(
    (pl.col("created_date") >= begin_hist) & (pl.col("created_date") <= end_hist)
)
train_recent = purchase_history_df.lazy().filter(
    (pl.col("created_date") >= begin_recent) & (pl.col("created_date") <= end_recent)
)
#val = purchase_history_df.lazy().filter(
#    (pl.col("created_date") >= begin_val) & (pl.col("created_date") <= end_val)
#)

In [21]:
# hàm chuyển các nhóm tuổi về month 

def normalize_and_split_age_group(age_str: str):
    if not age_str or age_str.strip() == "" or age_str.upper() == "KHÔNG XÁC ĐỊNH":
        return []

    s = age_str.upper().replace(" ", "")

    def to_months(value: str) -> int:
        years = months = 0
        y_match = re.search(r'(\d+)Y', value)
        m_match = re.search(r'(\d+)M', value)
        if y_match: years = int(y_match.group(1))
        if m_match: months = int(m_match.group(1))
        if not y_match and not m_match and value.isdigit(): months = int(value)
        return years * 12 + months

    parts = re.split(r'[-–]', s)
    if len(parts) == 2:
        start = to_months(parts[0])
        end = to_months(parts[1])
    elif "TỪ" in s or "TRÊN" in s:
        m = re.search(r'(\d+[MY])', s).group(1)
        start = to_months(m)
        end = start + 60
    else:
        start = to_months(s)
        end = start

    return [f"{m}M" for m in range(start, end + 1, 6)]  # mỗi 6 tháng

In [22]:
def compute_X1(train_history, item):
    df = (
        train_history.lazy()
        .join(item.lazy(), on="item_id", how="inner")
        .group_by(["customer_id", "item_id"])
        .agg((pl.col("brand") == pl.col("brand")).sum().alias("X_1"))
    )
    return df

In [23]:
feature_X1 =compute_X1(train_history, item_df)
feature_X1.collect().write_parquet("feature_X1_train.parquet", compression="snappy", use_pyarrow=True)

In [24]:
feature_X1=compute_X1(train_recent, item_df)
feature_X1.collect().write_parquet("feature_X1_val.parquet", compression="snappy", use_pyarrow=True)

In [25]:
def compute_X2(train_history, item):
    df = (
        train_history.lazy()
        .join(item.lazy(), on="item_id", how="inner")
        .group_by(["customer_id", "item_id"])
        .agg((pl.col("age_group") == pl.col("age_group")).sum().alias("X_2"))
    )
    return df

In [26]:
feature_X2 =compute_X2(train_history, item_df)
feature_X2.collect().write_parquet("feature_X2_train.parquet", compression="snappy", use_pyarrow=True)
print("finish")

finish

In [27]:
feature_X2=compute_X2(train_recent, item_df)
feature_X2.collect().write_parquet("feature_X2_val.parquet", compression="snappy", use_pyarrow=True)
print("finish")

finish

In [28]:
def compute_X3(train_history, item):
    df = (
        train_history.lazy()
        .join(item.lazy(), on="item_id", how="inner")
        .group_by(["customer_id", "item_id"])
        .agg((pl.col("category") == pl.col("category")).sum().alias("X_3"))
    )
    return df

In [29]:
feature_X3 =compute_X3(train_history, item_df)
feature_X3.collect().write_parquet("feature_X3_train.parquet", compression="snappy", use_pyarrow=True)
print("finish")

finish

In [30]:
feature_X3=compute_X3(train_recent, item_df)
feature_X3.collect().write_parquet("feature_X3_val.parquet", compression="snappy", use_pyarrow=True)
print("finish")

finish

In [22]:
# đếm số lần item được mua chung với các item khác 
def compute_X4(train_history):
    """
    Tính feature X_4: số lần item được mua chung với các item khác (bỏ customer)
    
    Args:
        train_history: pl.DataFrame, chứa item_id, created_date
    
    Returns:
        pl.DataFrame: item_id, X_4
    """
    
    # Gom các item theo đơn (created_date + giả sử mỗi row = 1 order)
    orders = train_history.lazy().group_by("created_date") \
                           .agg(pl.col("item_id").sort().alias("items"))
    
    # Explode để tạo cặp item trong cùng đơn
    orders_exploded = orders.explode("items").rename({"items": "item_1"})
    
    cooc_df = (
        orders_exploded.join(orders_exploded, on="created_date", how="inner")
        .filter(pl.col("item_1") < pl.col("item_1_right"))
        .group_by(["item_1", "item_1_right"])
        .agg(pl.count().alias("cooc_count"))
        .rename({"item_1_right": "item_2"})
    )
    
    # Tính X_4 cho từng item
    X4_df = (
        cooc_df.lazy()
        .select([
            pl.col("item_1").alias("item_id"), 
            pl.col("cooc_count")
        ])
        .group_by("item_id")
        .agg(pl.col("cooc_count").sum().alias("X_4"))
        .collect()
    )
    
    return X4_df

In [23]:
feature_X4_items = compute_X4(train_history)
feature_X4_items.write_parquet("feature_X4_train.parquet", compression="snappy", use_pyarrow=True)
print("finish")

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_10376\1625565777.py:24: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .agg(pl.count().alias("cooc_count"))

finish

In [24]:
feature_X4=compute_X4(train_recent)
feature_X4.write_parquet("feature_X4_val.parquet", compression="snappy", use_pyarrow=True)
print("finish")

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_10376\1625565777.py:24: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .agg(pl.count().alias("cooc_count"))

finish

In [25]:
# xác định nhóm tuổi của item theo month 
def compute_X5(item_df: pl.DataFrame):
    """
    Tạo feature X_5 cho item:
    - Gộp tất cả các nhóm tuổi (6M, 12M, …, 120M) thành 1 cột tổng.
    - Trả về DataFrame chỉ có item_id và X_5.
    """

    # 1️⃣ LazyFrame với cột X_5 dạng list
    lf = item_df.lazy().with_columns(
        pl.col("age_group")
          .map_elements(normalize_and_split_age_group, return_dtype=pl.List(pl.Utf8))
          .alias("X_5")
    )

    # 2️⃣ Collect về eager
    df = lf.collect()

    # 3️⃣ Explode list -> mỗi row 1 mốc tuổi
    df = df.explode("X_5")

    # 4️⃣ Tạo multi-hot: cột X5_6M … X5_120M
    all_months = [f"{m}M" for m in range(6, 121, 6)]
    for m in all_months:
        df = df.with_columns(
            (pl.col("X_5") == m).cast(pl.UInt8).alias(f"X5_{m}")
        )

    # 5️⃣ Group lại theo item_id, max từng cột
    df = df.group_by("item_id").agg([pl.max(f"X5_{m}").alias(f"X5_{m}") for m in all_months])

    # 6️⃣ Gộp 20 cột thành 1 cột tổng
    df = df.with_columns(
    sum([pl.col(f"X5_{m}") for m in all_months]).alias("X_5")
     ).drop([f"X5_{m}" for m in all_months])  # xóa các cột cũ đúng tên

    # 7️⃣ Lưu parquet
    df.write_parquet("feature_X5.parquet", compression="snappy", use_pyarrow=True)

    return df

In [26]:
feature_X5=compute_X5(item_df)
feature_X5.write_parquet("feature_X5_train.parquet", compression="snappy", use_pyarrow=True)
print("finish")

finish

In [27]:
feature_X5=compute_X5(item_df)
feature_X5.write_parquet("feature_X5_val.parquet", compression="snappy", use_pyarrow=True)
print("finish")

finish

In [28]:
def compute_X6(train_history: pl.LazyFrame) -> pl.DataFrame:
    df = train_history.select(
        "customer_id",
        (
            pl.col("price").cast(pl.Decimal(38,4)) *
            pl.col("quantity").cast(pl.Decimal(38,4))
        ).alias("total_amount")
    )

    return (
        df.group_by("customer_id")
          .agg(pl.col("total_amount").mean().alias("X_6"))
          .collect()
    )

In [29]:
feature_X6 = compute_X6(train_history)
feature_X6.write_parquet("feature_X6_train.parquet", compression="snappy", use_pyarrow=True)
print("finish")

finish

In [30]:
feature_X6 = compute_X6(train_recent)
feature_X6.write_parquet("feature_X6_val.parquet", compression="snappy", use_pyarrow=True)
print("finish")

finish

In [31]:
def compute_X7_X8_X9(train_history: pl.LazyFrame, item_df: pl.LazyFrame):
    """
    Tính các feature:
        X_7: tổng số đơn hàng
        X_8: số item trung bình mỗi đơn hàng
        X_9: số brand khác nhau mà khách hàng đã từng mua (dựa trên item_df)

    Args:
        train_history: pl.LazyFrame, chứa customer_id, item_id, created_date
        item_df: pl.LazyFrame, chứa item_id và brand

    Returns:
        Tuple[pl.DataFrame]: X7, X8, X9
    """

    # -------------------------------
    # X7: tổng số đơn hàng
    # -------------------------------
    X7 = (
        train_history
        .group_by("customer_id")
        .agg(pl.count("created_date").alias("X_7"))
        .collect()
    )

    # -------------------------------
    # X8: số item trung bình mỗi đơn hàng
    # -------------------------------
    orders = (
        train_history
        .group_by(["customer_id", "created_date"])
        .agg(pl.count("item_id").alias("num_items"))
    )

    X8 = (
        orders
        .group_by("customer_id")
        .agg(pl.col("num_items").mean().alias("X_8"))
        .collect()
    )

    # -------------------------------
    # X9: số brand khác nhau từng mua
    # -------------------------------
    X9 = (
    train_history
    .join(item_df.lazy().select(["item_id", "brand"]), on="item_id", how="left")
    .select(["customer_id", "brand"])
    .unique()
    .group_by("customer_id")
    .agg(pl.count("brand").alias("X_9"))
    .collect()
    )

    return X7, X8, X9

In [32]:
X7, X8, X9 = compute_X7_X8_X9(train_history,item_df)
X7.write_parquet("feature_X7_train.parquet", compression="snappy")
X8.write_parquet("feature_X8_train.parquet", compression="snappy")
X9.write_parquet("feature_X9_train.parquet", compression="snappy")
print("finish")

finish

In [33]:
X7, X8, X9 = compute_X7_X8_X9(train_recent,item_df)
X7.write_parquet("feature_X7_val.parquet", compression="snappy")
X8.write_parquet("feature_X8_val.parquet", compression="snappy")
X9.write_parquet("feature_X9_val.parquet", compression="snappy")
print("finish")

finish

In [34]:
def compute_X10_X11_X12(train_history, user_df, end_hist):
    """
    Tạo các feature thời gian:
    X_10: số ngày từ end_hist đến ngày tạo account
    X_11: số ngày từ lần mua cuối cùng đến end_hist
    X_12: tổng số ngày khách hàng có mua hàng (distinct purchase days)
    """
    user_df_lazy = user_df.lazy()
    train_history_lazy = train_history.lazy()

    # -------------------------------
    # X_10: số ngày từ ngày tạo account đến end_hist
    # -------------------------------
    user_df_lazy = user_df_lazy.with_columns(
        (pl.lit(end_hist) - pl.col("created_date"))
        .dt.total_days()
        .alias("X_10")
    )

    # -------------------------------
    # Ngày mua đầu tiên & cuối cùng
    # -------------------------------
    purchase_base = (
        train_history_lazy
        .filter(
            (pl.col("event_type") == "Purchase") &
            (pl.col("is_deleted") == False)
        )
    )

    purchase_dates = (
        purchase_base
        .group_by("customer_id")
        .agg([
            pl.col("created_date").min().alias("first_purchase_date"),
            pl.col("created_date").max().alias("last_purchase_date")
        ])
    )

    # -------------------------------
    # X_12: tổng số ngày có mua hàng
    # -------------------------------
    purchase_days = (
        purchase_base
        .with_columns(
            pl.col("created_date").dt.date().alias("purchase_day")
        )
        .group_by("customer_id")
        .agg(
            pl.col("purchase_day").n_unique().alias("X_12")
        )
    )

    # -------------------------------
    # Join & tạo X_11
    # -------------------------------
    features = (
        user_df_lazy
        .join(purchase_dates, on="customer_id", how="left")
        .join(purchase_days, on="customer_id", how="left")
        .with_columns(
            (pl.lit(end_hist) - pl.col("last_purchase_date"))
            .dt.total_days()
            .alias("X_11")
        )
    )

    X10 = features.select(["customer_id", "X_10"])
    X11 = features.select(["customer_id", "X_11"])
    X12 = features.select(["customer_id", "X_12"])

    return X10, X11, X12

In [35]:
X10,X11,X12=compute_X10_X11_X12(train_history, user_df, end_hist)
X10.collect().write_parquet("feature_X10_train.parquet", compression="snappy")
X11.collect().write_parquet("feature_X11_train.parquet", compression="snappy")
X12.collect().write_parquet("feature_X12_train.parquet", compression="snappy")

In [36]:
X10,X11,X12=compute_X10_X11_X12(train_recent, user_df, end_recent)
X10.collect().write_parquet("feature_X10_val.parquet", compression="snappy")
X11.collect().write_parquet("feature_X11_val.parquet", compression="snappy")
X12.collect().write_parquet("feature_X12_val.parquet", compression="snappy")

In [37]:
def compute_X13(train_history, item):
    """
    Tính feature X_13: số loại sản phẩm (category_l1) trung bình cho một lần mua hàng.
    Trả về DataFrame chỉ gồm customer_id và X_13 (giữ giá trị trung bình liên tục).
    """
    # 1️⃣ Join để lấy category_l1
    df = train_history.lazy().join(
        item.lazy().select(["item_id", "category_l1"]),
        on="item_id",
        how="left"
    )

    # 2️⃣ Số loại sản phẩm unique mỗi giao dịch
    unique_cate_per_order = (
        df.group_by(["customer_id", "date_key"])
          .agg(pl.col("category_l1").n_unique().alias("so_loai_san_pham"))
    )

    # 3️⃣ Trung bình số loại sản phẩm mỗi khách hàng
    avg_cate_customer = (
        unique_cate_per_order.group_by("customer_id")
        .agg(pl.col("so_loai_san_pham").mean().alias("X_13"))
    ).collect()

    return avg_cate_customer.lazy()

In [38]:
feature_X13 = compute_X13(train_history, item_df)
feature_X13.collect().write_parquet("feature_X13_train.parquet", compression="snappy", use_pyarrow=True)
print("finish")

finish

In [39]:
feature_X13 = compute_X13(train_recent, item_df)
feature_X13.collect().write_parquet("feature_X13_val.parquet", compression="snappy", use_pyarrow=True)
print("finish")

finish

In [40]:
def compute_X14(train_history, item_chunk_df, n_clusters=5):
    """
    Tính feature X_14: đặc trưng khách hàng dựa trên sản phẩm category 'Sữa'.
    Phân thành n_clusters theo giá và chọn cluster mua nhiều nhất.
    """
    # 1️⃣ Lọc sản phẩm sữa
    milk_df = (
        item_chunk_df.lazy()
        .filter(pl.col("category_l1").str.contains("Sữa", literal=False))
        .select(["item_id", "price"])
        .collect()
    )

    # 2️⃣ KMeans n_clusters cluster giá
    X = milk_df["price"].to_numpy().reshape(-1, 1)
    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init="auto").fit(X)
    milk_df = milk_df.with_columns(pl.Series("cluster", kmeans.labels_))

    # 3️⃣ Xác định thứ tự cluster theo giá tăng dần → số 0..n_clusters-1
    cluster_order = np.argsort([X[kmeans.labels_ == i].mean() for i in range(n_clusters)])
    tier_map = {cluster_order[i]: i for i in range(n_clusters)}

    milk_df = milk_df.with_columns(
        pl.col("cluster").cast(pl.Int64).replace_strict(tier_map).alias("milk_price_tier_num")
    ).select(["item_id", "milk_price_tier_num"])

    # 4️⃣ Join với train_history
    milk_purchase = train_history.lazy().join(milk_df.lazy(), on="item_id", how="inner").collect()

    # 5️⃣ Group + count theo tier
    customer_milk_stats = (
        milk_purchase.group_by(["customer_id", "milk_price_tier_num"])
        .agg(pl.count("item_id").alias("purchase_count"))
        .pivot(
            values="purchase_count",
            index="customer_id",
            on="milk_price_tier_num"  # columns
        )
        .fill_null(0)
    )

    # 6️⃣ Đổi tên cột từ int → string
    col_rename = {col: str(col) for col in customer_milk_stats.columns if isinstance(col, int)}
    customer_milk_stats = customer_milk_stats.rename(col_rename)

    # 7️⃣ Đảm bảo đủ cột từ "0" đến str(n_clusters-1)
    for tier in map(str, range(n_clusters)):
        if tier not in customer_milk_stats.columns:
            customer_milk_stats = customer_milk_stats.with_columns(
                pl.lit(0).alias(tier)
            )

    # 8️⃣ Chọn tier mua nhiều nhất → X_14 là số 0..n_clusters-1
    customer_milk_stats = customer_milk_stats.with_columns(
        pl.struct(list(map(str, range(n_clusters)))).map_elements(
            lambda r: int(max(r.items(), key=lambda x: x[1])[0]),
            return_dtype=pl.Int64
        ).alias("X_14")
    )

    return customer_milk_stats

In [41]:
feature_X14 = compute_X14(train_history, item_df)
feature_X14.write_parquet("feature_X14_train.parquet", compression="snappy", use_pyarrow=True)
print("finish")

finish

In [42]:
feature_X14 = compute_X14(train_recent, item_df)
feature_X14.write_parquet("feature_X14_val.parquet", compression="snappy", use_pyarrow=True)
print("finish")

finish

In [43]:
def compute_x15(train_history: pl.DataFrame) -> pl.DataFrame:
    """
    Compute x_15: average time gap (days) between purchases for each customer.
    If purchase_count <= 2, x_15 = 0.
    
    Parameters
    ----------
    train_history : pl.DataFrame
        Must contain:
        - customer_id
        - event_type
        - created_date (datetime)
    
    Returns
    -------
    pl.DataFrame
        Columns:
        - customer_id
        - x_15
    """

    return (
        train_history
        # 1️⃣ Chỉ lấy giao dịch mua
        .filter(pl.col("event_type") == "Purchase")
        
        # 2️⃣ Sort theo customer + thời gian
        .sort(["customer_id", "created_date"])
        
        # 3️⃣ Tính gap giữa các lần mua (ngày)
        .with_columns(
            gap_days = (
                pl.col("created_date")
                .diff()
                .dt.total_days()
                .over("customer_id")
            )
        )
        
        # 4️⃣ Gom theo customer
        .group_by("customer_id")
        .agg(
            purchase_count = pl.len(),
            avg_gap_days_raw = pl.col("gap_days").mean()
        )
        
        # 5️⃣ Nếu mua ≤ 2 lần → gán = 0
        .with_columns(
            X_15 = pl.when(pl.col("purchase_count") <= 2)
                .then(0.0)
                .otherwise(pl.col("avg_gap_days_raw"))
        )
        
        # 6️⃣ Chỉ giữ 2 cột theo yêu cầu
        .select([
            "customer_id",
            "X_15"
        ])
    )

In [44]:
df_x15 = compute_x15(train_history)
df_x15.collect().write_parquet("feature_X15_train.parquet", compression="snappy", use_pyarrow=True)

In [45]:
df_x15 = compute_x15(train_recent)
df_x15.collect().write_parquet("feature_X15_val.parquet", compression="snappy", use_pyarrow=True)

In [46]:
def compute_x16(user_df: pl.DataFrame) -> pl.DataFrame:
    return (
        user_df
        .select([
            "customer_id",
            pl.col("membership").alias("X_16")
        ])
    )

In [47]:
df_x16 = compute_x16(user_df)
df_x16.write_parquet("feature_X16_train.parquet", compression="snappy", use_pyarrow=True)

In [48]:
df_x16 = compute_x16(user_df)
df_x16.write_parquet("feature_X16_val.parquet", compression="snappy", use_pyarrow=True)

In [50]:
def compute_candidates(train_history, train_recent):
    # ----------------------------
    # Positive samples (Y = 1)
    # ----------------------------
    positives = (
        train_recent
        .select(["customer_id", "item_id"])
        .unique()
        .with_columns(pl.lit(1.0).alias("Y"))
    )
    # ----------------------------
    # Negative samples (weighted Y)
    # ----------------------------
    negatives = (
        train_history
        .select(["customer_id", "item_id", "created_date"])
        .unique(subset=["customer_id", "item_id"])
        .join(positives.select(["customer_id", "item_id"]),
              on=["customer_id", "item_id"],
              how="anti")
        .with_columns(
            pl.when(pl.col("created_date").dt.month().is_in([7, 8,9]))
              .then(0.5)
              .when(pl.col("created_date").dt.month().is_in([4, 5, 6]))
              .then(0.3)
              .when(pl.col("created_date").dt.month().is_in([1, 2, 3]))
              .then(0.2)
              .otherwise(0.0)   # fallback (phòng hờ)
              .alias("Y")
        )
        .select(["customer_id", "item_id", "Y"])
    )

    # ----------------------------
    # Merge candidates
    # ----------------------------
    candidates = pl.concat([positives, negatives])

    return candidates

In [51]:
candidates=compute_candidates(train_history, train_recent)
candidates.collect().write_parquet("candidates_train.parquet", compression="snappy", use_pyarrow=True)

In [52]:
def compute_candidates_val(train_history, train_recent):
    """
    Lấy tất cả cặp (customer_id, item_id) xuất hiện trong train_history và train_recent.
    Không gán nhãn Y.
    """
    # Lấy cặp từ recent
    recent_keys = train_recent.select(["customer_id", "item_id"]).unique()

    # Lấy cặp từ history trừ recent (nếu muốn loại bỏ trùng với recent)
    #history_keys = train_history.select(["customer_id", "item_id"]).unique()
    
    # Kết hợp 2 tập
    #candidates = pl.concat([recent_keys, history_keys]).unique()
    candidates = recent_keys
    return candidates

In [53]:
candidates=compute_candidates_val(train_history, train_recent)
candidates.collect().write_parquet("candidates_val.parquet", compression="snappy", use_pyarrow=True)

In [54]:
print("Số dòng candidates:", candidates.select(pl.len()).collect().item())

Số dòng candidates: 19217254

In [55]:
def merge_features():
    # Scan parquet (LazyFrame)
    candidates = pl.scan_parquet("candidates_train.parquet")
    X1  = pl.scan_parquet("feature_X1_train.parquet")
    X2  = pl.scan_parquet("feature_X2_train.parquet")
    X3  = pl.scan_parquet("feature_X3_train.parquet")
    X4  = pl.scan_parquet("feature_X4_train.parquet")
    X5  = pl.scan_parquet("feature_X5_train.parquet")
    X6  = pl.scan_parquet("feature_X6_train.parquet")
    X7  = pl.scan_parquet("feature_X7_train.parquet")
    X8  = pl.scan_parquet("feature_X8_train.parquet")
    X9  = pl.scan_parquet("feature_X9_train.parquet")
    X10 = pl.scan_parquet("feature_X10_train.parquet")
    X11 = pl.scan_parquet("feature_X11_train.parquet")
    X12 = pl.scan_parquet("feature_X12_train.parquet")
    X13 = pl.scan_parquet("feature_X13_train.parquet")
    X14 = pl.scan_parquet("feature_X14_train.parquet")
    X15 = pl.scan_parquet("feature_X15_train.parquet")
    X16 = pl.scan_parquet("feature_X16_train.parquet")
    # Merge features
    features = (
        candidates
        .join(X5,  on="item_id", how="left")
        .join(X1,  on=["customer_id", "item_id"], how="left")
        .join(X2,  on=["customer_id", "item_id"], how="left")
        .join(X3,  on=["customer_id", "item_id"], how="left")
        .join(X4,  on="item_id", how="left")
        .join(X6,  on="customer_id", how="left")
        .join(X7,  on="customer_id", how="left")
        .join(X8,  on="customer_id", how="left")
        .join(X9,  on="customer_id", how="left")
        .join(X10, on="customer_id", how="left")
        .join(X11, on="customer_id", how="left")
        .join(X12, on="customer_id", how="left")
        .join(X13, on="customer_id", how="left")
        .join(X14, on="customer_id", how="left")
        .join(X15, on="customer_id", how="left")
        .join(X16, on="customer_id", how="left")
        .fill_null(0)
        .select([
            "customer_id",
            "item_id",
            "X_1", "X_2", "X_3", "X_4", "X_5",
            "X_6", "X_7", "X_8", "X_9", "X_10",
            "X_11", "X_12", "X_13", "X_14", "X_15", "X_16",
            "Y"
        ])
    )
    # Ghi ra parquet
    features.collect().write_parquet(
        "features_train.parquet",
        compression="snappy",
        use_pyarrow=True
    )
    return features
features = merge_features()

In [56]:
# -----------------------------
# 3️⃣ Merge all features + candidates
# -----------------------------
def merge_features():
    candidates = pl.scan_parquet("candidates_val.parquet")
    X1 = pl.scan_parquet("feature_X1_val.parquet")
    X2 = pl.scan_parquet("feature_X2_val.parquet")
    X3 = pl.scan_parquet("feature_X3_val.parquet")
    X4 = pl.scan_parquet("feature_X4_val.parquet")
    X5 = pl.scan_parquet("feature_X5_val.parquet")
    X6 = pl.scan_parquet("feature_X6_val.parquet")
    X7 = pl.scan_parquet("feature_X7_val.parquet")
    X8 = pl.scan_parquet("feature_X8_val.parquet")
    X9 = pl.scan_parquet("feature_X9_val.parquet")
    X10 = pl.scan_parquet("feature_X10_val.parquet")
    X11 = pl.scan_parquet("feature_X11_val.parquet")
    X12 = pl.scan_parquet("feature_X12_val.parquet")
    X13 = pl.scan_parquet("feature_X13_val.parquet")
    X14 = pl.scan_parquet("feature_X14_val.parquet")
    X15 = pl.scan_parquet("feature_X15_val.parquet")
    X16 = pl.scan_parquet("feature_X16_val.parquet")

    features = (
        candidates
        .join(X5, on="item_id", how="left")
        .join(X1, on=["customer_id", "item_id"], how="left")
        .join(X2, on=["customer_id", "item_id"], how="left")
        .join(X3, on=["customer_id", "item_id"], how="left")
        .join(X4, on="item_id", how="left")
        .join(X6, on="customer_id", how="left") 
        .join(X7, on="customer_id", how="left")
        .join(X8, on="customer_id", how="left")
        .join(X9, on="customer_id", how="left")
        .join(X10, on="customer_id", how="left")
        .join(X11, on="customer_id", how="left")
        .join(X12, on="customer_id", how="left")
        .join(X13, on="customer_id", how="left")
        .join(X14, on="customer_id", how="left")
        .join(X15, on="customer_id", how="left")
        .join(X16, on="customer_id", how="left")  
        .fill_null(0)
        .select(["customer_id", "item_id", "X_1", "X_2", "X_3","X_4","X_5","X_6","X_7","X_8","X_9","X_10","X_11","X_12","X_13","X_14","X_15","X_16"])
    )

    features.collect().write_parquet("features_val.parquet", compression="snappy", use_pyarrow=True)
    return features

features = merge_features()

In [2]:
train_path = "features_train.parquet"
val_path = "features_val.parquet"

# Đọc file parquet bằng Polars
df_train = pl.read_parquet(train_path)
df_val = pl.read_parquet(val_path)

# In số dòng
print("Số dòng train:", df_train.height)
print("Số dòng validation:", df_val.height)

# Đọc 10 dòng đầu
print("\n===== 10 dòng đầu của TRAIN =====")
df_train.head(1)

Số dòng train: 26790113
Số dòng validation: 19217254

===== 10 dòng đầu của TRAIN =====

shape: (1, 19)
┌─────────────┬───────────────┬─────┬─────┬───┬──────┬──────────┬──────┬─────┐
│ customer_id ┆ item_id       ┆ X_1 ┆ X_2 ┆ … ┆ X_14 ┆ X_15     ┆ X_16 ┆ Y   │
│ ---         ┆ ---           ┆ --- ┆ --- ┆   ┆ ---  ┆ ---      ┆ ---  ┆ --- │
│ i32         ┆ str           ┆ u32 ┆ u32 ┆   ┆ i64  ┆ f64      ┆ i64  ┆ f64 │
╞═════════════╪═══════════════╪═════╪═════╪═══╪══════╪══════════╪══════╪═════╡
│ 841313      ┆ 4600000000001 ┆ 6   ┆ 6   ┆ … ┆ 3    ┆ 7.818182 ┆ 2    ┆ 1.0 │
└─────────────┴───────────────┴─────┴─────┴───┴──────┴──────────┴──────┴─────┘

In [3]:
print("\n===== 10 dòng đầu của VALIDATION =====")
df_val.head(1)

===== 10 dòng đầu của VALIDATION =====

shape: (1, 18)
┌─────────────┬───────────────┬─────┬─────┬───┬──────────┬──────┬──────────┬──────┐
│ customer_id ┆ item_id       ┆ X_1 ┆ X_2 ┆ … ┆ X_13     ┆ X_14 ┆ X_15     ┆ X_16 │
│ ---         ┆ ---           ┆ --- ┆ --- ┆   ┆ ---      ┆ ---  ┆ ---      ┆ ---  │
│ i32         ┆ str           ┆ u32 ┆ u32 ┆   ┆ f64      ┆ i64  ┆ f64      ┆ i64  │
╞═════════════╪═══════════════╪═════╪═════╪═══╪══════════╪══════╪══════════╪══════╡
│ 5316154     ┆ 0203000000002 ┆ 1   ┆ 1   ┆ … ┆ 3.307692 ┆ 0    ┆ 3.246377 ┆ 1    │
└─────────────┴───────────────┴─────┴─────┴───┴──────────┴──────┴──────────┴──────┘

In [4]:
df_y1 = df_train.filter(pl.col("Y") == 1)
df_y0 = df_train.filter(pl.col("Y") != 1)

print("Số mẫu Y=1:", df_y1.height)
print("Số mẫu Y!=1:", df_y0.height)

# Lấy ngẫu nhiên 3 triệu mẫu Y=0
df_y0_sample = df_y0.sample(n=1_000_000, shuffle=True)

# Gộp lại thành tập train balanced
df_train_balanced = pl.concat([df_y1, df_y0_sample], how="vertical")

print("Tổng số mẫu balanced:", df_train_balanced.height)

 #Nếu muốn shuffle lại toàn bộ:
df_train_balanced = df_train_balanced.sample(n=df_train_balanced.height, shuffle=True)

Số mẫu Y=1: 19217254
Số mẫu Y!=1: 7572859
Tổng số mẫu balanced: 20217254

In [5]:

# 3️⃣ Tạo lại X_test và id_cols
X_test = df_val.drop(["customer_id", "item_id"])
id_cols = df_val.select(["customer_id", "item_id"])


X_test.head(1)

shape: (1, 16)
┌─────┬─────┬─────┬────────┬───┬──────────┬──────┬──────────┬──────┐
│ X_1 ┆ X_2 ┆ X_3 ┆ X_4    ┆ … ┆ X_13     ┆ X_14 ┆ X_15     ┆ X_16 │
│ --- ┆ --- ┆ --- ┆ ---    ┆   ┆ ---      ┆ ---  ┆ ---      ┆ ---  │
│ u32 ┆ u32 ┆ u32 ┆ u32    ┆   ┆ f64      ┆ i64  ┆ f64      ┆ i64  │
╞═════╪═════╪═════╪════════╪═══╪══════════╪══════╪══════════╪══════╡
│ 1   ┆ 1   ┆ 1   ┆ 125013 ┆ … ┆ 3.307692 ┆ 0    ┆ 3.246377 ┆ 1    │
└─────┴─────┴─────┴────────┴───┴──────────┴──────┴──────────┴──────┘

In [6]:
# ======================
# 0) Các cột định danh
# ======================
key_cols = ["customer_id", "item_id"]
# ====================================================
# 5) Tạo X_train, y_train, X_test, y_test
# ====================================================
X_train = df_train.drop(["customer_id", "item_id", "Y"])
y_train = df_train["Y"]


#y_test = df_val["Y"]
id_cols = df_val.select(["customer_id", "item_id"])
# ====================================================
# 6) Debug xem sample
# ====================================================
X_train.head(1)

shape: (1, 16)
┌─────┬─────┬─────┬───────┬───┬──────────┬──────┬──────────┬──────┐
│ X_1 ┆ X_2 ┆ X_3 ┆ X_4   ┆ … ┆ X_13     ┆ X_14 ┆ X_15     ┆ X_16 │
│ --- ┆ --- ┆ --- ┆ ---   ┆   ┆ ---      ┆ ---  ┆ ---      ┆ ---  │
│ u32 ┆ u32 ┆ u32 ┆ u32   ┆   ┆ f64      ┆ i64  ┆ f64      ┆ i64  │
╞═════╪═════╪═════╪═══════╪═══╪══════════╪══════╪══════════╪══════╡
│ 6   ┆ 6   ┆ 6   ┆ 25843 ┆ … ┆ 1.833333 ┆ 3    ┆ 7.818182 ┆ 2    │
└─────┴─────┴─────┴───────┴───┴──────────┴──────┴──────────┴──────┘

In [7]:
y_train.value_counts()

shape: (3, 2)
┌─────┬──────────┐
│ Y   ┆ count    │
│ --- ┆ ---      │
│ f64 ┆ u32      │
╞═════╪══════════╡
│ 0.2 ┆ 5786325  │
│ 0.3 ┆ 1786534  │
│ 1.0 ┆ 19217254 │
└─────┴──────────┘

In [8]:
X_test.head(1)

shape: (1, 16)
┌─────┬─────┬─────┬────────┬───┬──────────┬──────┬──────────┬──────┐
│ X_1 ┆ X_2 ┆ X_3 ┆ X_4    ┆ … ┆ X_13     ┆ X_14 ┆ X_15     ┆ X_16 │
│ --- ┆ --- ┆ --- ┆ ---    ┆   ┆ ---      ┆ ---  ┆ ---      ┆ ---  │
│ u32 ┆ u32 ┆ u32 ┆ u32    ┆   ┆ f64      ┆ i64  ┆ f64      ┆ i64  │
╞═════╪═════╪═════╪════════╪═══╪══════════╪══════╪══════════╪══════╡
│ 1   ┆ 1   ┆ 1   ┆ 125013 ┆ … ┆ 3.307692 ┆ 0    ┆ 3.246377 ┆ 1    │
└─────┴─────┴─────┴────────┴───┴──────────┴──────┴──────────┴──────┘

In [9]:
import polars as pl
import xgboost as xgb
import numpy as np

# ======================
# CONFIG
# ======================
feature_cols = [f"X_{i}" for i in range(1, 17)]

params = {
    "max_depth": 6,
    "learning_rate": 0.001,
    "min_child_weight": 4,
    "gamma": 0.2,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "reg_alpha": 0.1,
    "reg_lambda": 1.0,
    "objective": "reg:squarederror",
    "eval_metric": "rmse",
    "tree_method": "hist",
    "device": "cuda",
    "max_bin": 128,
    "seed": 42
}

# ======================
# POLARS → NUMPY (NO PANDAS)
# ======================
X_train_np = (
    X_train
    .select(feature_cols)
    .with_columns(pl.all().cast(pl.Float32))
    .to_numpy(order="c")
)

y_train_np = (
    y_train
    .cast(pl.Float32)
    .to_numpy()
)

# ======================
# GPU-OPTIMIZED DMatrix
# ======================
dtrain = xgb.QuantileDMatrix(
    X_train_np,
    label=y_train_np,
    max_bin=128
)

# ======================
# TRAIN
# ======================
model = xgb.train(
    params,
    dtrain,
    num_boost_round=600
)

# ======================
# SAVE
# ======================
model.save_model("xgb_model.json")

print("✅ Train done (Polars → NumPy → QuantileDMatrix, NO pandas)")


"""from xgboost import XGBRegressor

model = XGBRegressor(
    booster="gblinear",          # 🔥 LINEAR REGRESSION
    objective="reg:squarederror",
    eval_metric="rmse",

    # Linear model params
    learning_rate=0.03,
    reg_alpha=0.1,               # L1 (Lasso)
    reg_lambda=1.0,              # L2 (Ridge)

    # GPU
    tree_method="gpu_hist",      # vẫn cần để dùng GPU
    predictor="gpu_predictor",

    random_state=42
)

# Ép float32 như cũ (OK)
X_train_np = X_train_np.astype("float32")
y_train_np = y_train_np.astype("float32")

model.fit(X_train_np, y_train_np)
"""

✅ Train done (Polars → NumPy → QuantileDMatrix, NO pandas)

'from xgboost import XGBRegressor\n\nmodel = XGBRegressor(\n    booster="gblinear",          # 🔥 LINEAR REGRESSION\n    objective="reg:squarederror",\n    eval_metric="rmse",\n\n    # Linear model params\n    learning_rate=0.03,\n    reg_alpha=0.1,               # L1 (Lasso)\n    reg_lambda=1.0,              # L2 (Ridge)\n\n    # GPU\n    tree_method="gpu_hist",      # vẫn cần để dùng GPU\n    predictor="gpu_predictor",\n\n    random_state=42\n)\n\n# Ép float32 như cũ (OK)\nX_train_np = X_train_np.astype("float32")\ny_train_np = y_train_np.astype("float32")\n\nmodel.fit(X_train_np, y_train_np)\n'

In [12]:
import polars as pl

# lấy importance (weight / gain / cover)
importance_dict = model.get_score(importance_type="gain")
feature_names = [f"X_{i}" for i in range(1, 17)]

rows = []
for i, name in enumerate(feature_names):
    rows.append({
        "feature": name,
        "importance": importance_dict.get(f"f{i}", 0.0)
    })
df_importance = (
    pl.DataFrame(rows)
    .sort("importance", descending=True)
)

df_importance.head(10)

shape: (10, 2)
┌─────────┬──────────────┐
│ feature ┆ importance   │
│ ---     ┆ ---          │
│ str     ┆ f64          │
╞═════════╪══════════════╡
│ X_11    ┆ 34821.320312 │
│ X_1     ┆ 19021.853516 │
│ X_2     ┆ 18570.044922 │
│ X_3     ┆ 16171.330078 │
│ X_10    ┆ 13746.035156 │
│ X_15    ┆ 6063.500977  │
│ X_12    ┆ 3114.571533  │
│ X_16    ┆ 3095.648438  │
│ X_5     ┆ 1409.376709  │
│ X_7     ┆ 913.575989   │
└─────────┴──────────────┘

In [13]:
import xgboost as xgb

model = xgb.Booster()
model.load_model("xgb_model.json")
model.set_param({"device": "cuda"})   # hoặc "cpu"

import numpy as np

def predict_in_batches(model, X_np, batch_size=1_000_000):
    preds = []

    for i in range(0, X_np.shape[0], batch_size):
        batch = X_np[i:i+batch_size]
        y_pred = model.inplace_predict(batch)
        preds.append(y_pred)

    return np.concatenate(preds)
    
# Polars → NumPy (NO pandas)
X_all_np = (
    X_test
    .with_columns(pl.all().cast(pl.Float32))
    .to_numpy(order="c")
)

pred_score = predict_in_batches(model, X_all_np)
'''import joblib
import numpy as np
import polars as pl

# ======================
# LOAD LINEAR MODEL (sklearn)
# ======================
model = joblib.load("linear_sgd_225M.joblib")

# ======================
# PREDICT IN BATCHES
# ======================
def predict_in_batches(model, X_np, batch_size=1_000_000):
    preds = []

    for i in range(0, X_np.shape[0], batch_size):
        batch = X_np[i:i + batch_size]
        y_pred = model.predict(batch)   # ✅ đúng cho linear regression
        preds.append(y_pred)

    return np.concatenate(preds)

# ======================
# POLARS → NUMPY
# ======================
X_all_np = (
    X_test
    .with_columns(pl.all().cast(pl.Float32))
    .to_numpy(order="c")
)

# ======================
# PREDICT
# ======================
pred_score = predict_in_batches(model, X_all_np)

In [14]:
import polars as pl
import json

# =================================================
# 1️⃣ GỘP KẾT QUẢ PREDICT (TRAIN + TEST)
# =================================================

df_test_pred = (
    X_test
    .with_columns(
        pl.Series("pred_proba", pred_score) # pred_score = predict(X_test)
    )
    .with_columns([
        df_val["customer_id"],
        df_val["item_id"]
    ])
)

#df_train_pred = (
#    X_train
#    .with_columns(
#        pl.Series("pred_proba", pred_train)   # pred_train = predict(X_train)
#    )
#   .with_columns([
#        df_train_balanced["customer_id"],
#        df_train_balanced["item_id"]
#    ])
#)

# 🔥 Gộp TRAIN + TEST
df_all = df_test_pred

# =================================================
# 2️⃣ GIỮ ITEM ĐƯỢC DỰ ĐOÁN MUA
# (hiện tại giữ tất cả)
# =================================================

df_buy = df_all

# =================================================
# 3️⃣ SORT: customer_id ↑ , pred_proba ↓
# =================================================

df_buy = df_buy.sort(
    ["customer_id", "pred_proba"],
    descending=[False, True]
)

# =================================================
# 4️⃣ MỖI CUSTOMER LẤY TỐI ĐA 10 ITEM
# =================================================

df_top10 = (
    df_buy
    .group_by("customer_id")
    .head(10)
)

# =================================================
# 5️⃣ GOM item_id → LIST
# =================================================

df_result = (
    df_top10
    .group_by("customer_id")
    .agg(
        pl.col("item_id").implode().alias("items")
    )
)

# =================================================
# 6️⃣ GHI FILE submission.json (THEO BATCH – NHẸ RAM)
# =================================================

BATCH_SIZE = 50_000   # giảm xuống 20_000 nếu RAM yếu

with open("submission.json", "w", encoding="utf-8") as f:
    f.write("{\n")

    total = df_result.height

    for start in range(0, total, BATCH_SIZE):
        batch = df_result.slice(start, BATCH_SIZE)

        for idx, row in enumerate(batch.iter_rows(named=True)):
            customer_id = str(row["customer_id"])
            items = row["items"]

            f.write(f'"{customer_id}": ')
            json.dump(items, f)

            # chỉ ghi dấu phẩy nếu CHƯA phải phần tử cuối
            if start + idx < total - 1:
                f.write(",\n")

    f.write("\n}")

print("✅ Đã xuất submission.json – gồm TRAIN + TEST, mỗi customer tối đa 10 item")

✅ Đã xuất submission.json – gồm TRAIN + TEST, mỗi customer tối đa 10 item

In [11]:
import pickle
import json
import numpy as np

def precision_at_k(pred, gt, hist=None, filter_bought_items=True, K=10):
    """
    pred: dict {customer_id: [item_id1, item_id2, ...]} - file submission
    gt: dict {customer_id: [item_id1, item_id2, ...]} - file groundtruth
    hist: dict {customer_id: [item_id1, ...]} - lịch sử mua của user, optional
    filter_bought_items: nếu True, loại bỏ các item đã mua trong history
    K: đánh giá top-K
    """
    precisions = []
    cold_start_users = []

    for user in gt.keys():
        if user not in pred:
            cold_start_users.append(user)
            continue

        gt_items = set(gt[user])
        if filter_bought_items and hist is not None and user in hist:
            gt_items -= set(hist[user])

        hits = len(set(pred[user][:K]) & gt_items)
        precisions.append(hits / K)

    mean_precision = np.mean(precisions) if precisions else 0.0
    return mean_precision, cold_start_users

# --- Load groundtruth ---
with open("final_groundtruth_clean.pkl", "rb") as f:
    groundtruth = pickle.load(f)

print(f"Số customer trong groundtruth: {len(groundtruth)}")

# --- Load submission ---
with open("submission_with_hist.json", "r") as f:
    submission = json.load(f)

# Nếu keys trong submission là str mà groundtruth là int, chuyển sang int
try:
    submission_fixed = {int(k): v for k, v in submission.items()}
except ValueError:
    submission_fixed = submission  # giữ nguyên nếu không thể chuyển

print(f"Số customer trong submission: {len(submission_fixed)}")
 
# --- Tính precision@K ---
precision, cold_users = precision_at_k(submission_fixed, groundtruth, hist=None, K=10)
print(f"Precision@10: {precision:.6f}")
print(f"Số cold start users (không có dự đoán): {len(cold_users)}")

Số customer trong groundtruth: 644970
Số customer trong submission: 2094582
Precision@10: 0.093271
Số cold start users (không có dự đoán): 148385

In [31]:
import pickle
import json
import numpy as np
import pandas as pd

# ================= FUNCTION =================
def precision_at_k(pred, gt, hist=None, filter_bought_items=True, K=10, fill_cold_start=None):
    precisions = []

    for user in gt.keys():
        if user in pred:
            user_pred = pred[user][:K]
        else:
            if fill_cold_start is not None:
                user_pred = fill_cold_start[:K]
            else:
                user_pred = []

        gt_items = set(gt[user])
        if filter_bought_items and hist is not None and user in hist:
            gt_items -= set(hist[user])

        hits = len(set(user_pred) & gt_items)
        precisions.append(hits / K)

    return np.mean(precisions) if precisions else 0.0


# ================= LOAD GROUNDTRUTH =================
with open("final_groundtruth_clean.pkl", "rb") as f:
    groundtruth = pickle.load(f)

print(f"👥 Số customer trong groundtruth: {len(groundtruth)}")


# ================= LOAD SUBMISSION =================
with open("submission_with_hist.json", "r", encoding="utf-8") as f:
    submission = json.load(f)

# fix key type nếu cần
try:
    submission = {int(k): v for k, v in submission.items()}
except ValueError:
    pass

print(f"📁 Số customer trong submission gốc: {len(submission)}")


# ================= LOAD TOP ITEMS =================
top_items_df = pd.read_csv("top10_first_purchase_by_count.csv")
top_items = top_items_df["item_id"].tolist()


# ================= FILL COLD START (KHÔNG LOẠI CUSTOMER) =================

# 1️⃣ Giữ nguyên toàn bộ submission gốc
submission_filled = {
    user: items[:10]
    for user, items in submission.items()
}

# 2️⃣ Chỉ fill customer thiếu so với groundtruth
cold_start_count = 0
for user in groundtruth.keys():
    if user not in submission_filled:
        submission_filled[user] = top_items[:10]
        cold_start_count += 1

print(f"❄️ Cold-start customers được fill: {cold_start_count}")
print(f"✅ Tổng customer sau fill: {len(submission_filled)}")


# ================= SAVE FILLED SUBMISSION =================
with open("submission_filled.json", "w", encoding="utf-8") as f:
    json.dump(submission_filled, f, ensure_ascii=False)

print("💾 Đã lưu file submission_filled.json")


# ================= EVALUATE =================
precision = precision_at_k(
    submission_filled,
    groundtruth,
    hist=None,
    K=10,
    fill_cold_start=None   # đã fill rồi nên không cần nữa
)

print(f"🎯 Precision@10 (sau khi fill & lưu): {precision:.6f}")

👥 Số customer trong groundtruth: 644970
📁 Số customer trong submission gốc: 2107732
❄️ Cold-start customers được fill: 135235
✅ Tổng customer sau fill: 2242967
💾 Đã lưu file submission_filled.json
🎯 Precision@10 (sau khi fill & lưu): 0.080587

In [28]:
import polars as pl
import math

# Load dữ liệu
customers = pl.read_parquet("customer_id_predict.parquet").select("customer_id")
items = pl.read_parquet("final_candidate_items.parquet").select("item_id")

n_items = items.height
target_rows_per_chunk = 1_000_000

# Số customer mỗi chunk ≈ 1M / n_items
customers_per_chunk = max(1, target_rows_per_chunk // n_items)

print("Items:", n_items)
print("Customers per chunk:", customers_per_chunk)

total_customers = customers.height
chunk_idx = 0
total_rows = 0

for start in range(0, total_customers, customers_per_chunk):
    cust_chunk = customers.slice(start, customers_per_chunk)

    joined = cust_chunk.join(items, how="cross")
    rows = joined.height
    total_rows += rows

    out_file = f"customer_item_keys_chunk_{chunk_idx}.parquet"
    joined.write_parquet(out_file)

    print(f"Saved {out_file} with {rows:,} rows")

    chunk_idx += 1

print(f"Total rows generated: {total_rows:,}")

Items: 97
Customers per chunk: 10309
Saved customer_item_keys_chunk_0.parquet with 999,973 rows
Saved customer_item_keys_chunk_1.parquet with 999,973 rows
Saved customer_item_keys_chunk_2.parquet with 999,973 rows
Saved customer_item_keys_chunk_3.parquet with 999,973 rows
Saved customer_item_keys_chunk_4.parquet with 999,973 rows
Saved customer_item_keys_chunk_5.parquet with 999,973 rows
Saved customer_item_keys_chunk_6.parquet with 999,973 rows
Saved customer_item_keys_chunk_7.parquet with 999,973 rows
Saved customer_item_keys_chunk_8.parquet with 999,973 rows
Saved customer_item_keys_chunk_9.parquet with 999,973 rows
Saved customer_item_keys_chunk_10.parquet with 999,973 rows
Saved customer_item_keys_chunk_11.parquet with 999,973 rows
Saved customer_item_keys_chunk_12.parquet with 999,973 rows
Saved customer_item_keys_chunk_13.parquet with 999,973 rows
Saved customer_item_keys_chunk_14.parquet with 999,973 rows
Saved customer_item_keys_chunk_15.parquet with 999,973 rows
Saved customer_item_keys_chunk_16.parquet with 999,973 rows
Saved customer_item_keys_chunk_17.parquet with 999,973 rows
Saved customer_item_keys_chunk_18.parquet with 999,973 rows
Saved customer_item_keys_chunk_19.parquet with 999,973 rows
Saved customer_item_keys_chunk_20.parquet with 999,973 rows
Saved customer_item_keys_chunk_21.parquet with 999,973 rows
Saved customer_item_keys_chunk_22.parquet with 999,973 rows
Saved customer_item_keys_chunk_23.parquet with 999,973 rows
Saved customer_item_keys_chunk_24.parquet with 999,973 rows
Saved customer_item_keys_chunk_25.parquet with 999,973 rows
Saved customer_item_keys_chunk_26.parquet with 999,973 rows
Saved customer_item_keys_chunk_27.parquet with 999,973 rows
Saved customer_item_keys_chunk_28.parquet with 999,973 rows
Saved customer_item_keys_chunk_29.parquet with 999,973 rows
Saved customer_item_keys_chunk_30.parquet with 999,973 rows
Saved customer_item_keys_chunk_31.parquet with 999,973 rows
Saved customer_item_keys_chunk_32.parquet with 999,973 rows
Saved customer_item_keys_chunk_33.parquet with 999,973 rows
Saved customer_item_keys_chunk_34.parquet with 999,973 rows
Saved customer_item_keys_chunk_35.parquet with 999,973 rows
Saved customer_item_keys_chunk_36.parquet with 999,973 rows
Saved customer_item_keys_chunk_37.parquet with 999,973 rows
Saved customer_item_keys_chunk_38.parquet with 999,973 rows
Saved customer_item_keys_chunk_39.parquet with 999,973 rows
Saved customer_item_keys_chunk_40.parquet with 999,973 rows
Saved customer_item_keys_chunk_41.parquet with 999,973 rows
Saved customer_item_keys_chunk_42.parquet with 999,973 rows
Saved customer_item_keys_chunk_43.parquet with 999,973 rows
Saved customer_item_keys_chunk_44.parquet with 999,973 rows
Saved customer_item_keys_chunk_45.parquet with 999,973 rows
Saved customer_item_keys_chunk_46.parquet with 999,973 rows
Saved customer_item_keys_chunk_47.parquet with 999,973 rows
Saved customer_item_keys_chunk_48.parquet with 999,973 rows
Saved customer_item_keys_chunk_49.parquet with 999,973 rows
Saved customer_item_keys_chunk_50.parquet with 999,973 rows
Saved customer_item_keys_chunk_51.parquet with 999,973 rows
Saved customer_item_keys_chunk_52.parquet with 999,973 rows
Saved customer_item_keys_chunk_53.parquet with 999,973 rows
Saved customer_item_keys_chunk_54.parquet with 999,973 rows
Saved customer_item_keys_chunk_55.parquet with 999,973 rows
Saved customer_item_keys_chunk_56.parquet with 999,973 rows
Saved customer_item_keys_chunk_57.parquet with 999,973 rows
Saved customer_item_keys_chunk_58.parquet with 999,973 rows
Saved customer_item_keys_chunk_59.parquet with 999,973 rows
Saved customer_item_keys_chunk_60.parquet with 999,973 rows
Saved customer_item_keys_chunk_61.parquet with 999,973 rows
Saved customer_item_keys_chunk_62.parquet with 999,973 rows
Saved customer_item_keys_chunk_63.parquet with 999,973 rows
Saved customer_item_keys_chunk_64.parquet with 999,973 rows
Saved customer_item_keys_chunk_65.parquet with 999,973 rows
Saved customer_item_keys_chunk_66.parquet with 999,973 rows
Saved customer_item_keys_chunk_67.parquet with 999,973 rows
Saved customer_item_keys_chunk_68.parquet with 999,973 rows
Saved customer_item_keys_chunk_69.parquet with 999,973 rows
Saved customer_item_keys_chunk_70.parquet with 999,973 rows
Saved customer_item_keys_chunk_71.parquet with 999,973 rows
Saved customer_item_keys_chunk_72.parquet with 999,973 rows
Saved customer_item_keys_chunk_73.parquet with 999,973 rows
Saved customer_item_keys_chunk_74.parquet with 999,973 rows
Saved customer_item_keys_chunk_75.parquet with 999,973 rows
Saved customer_item_keys_chunk_76.parquet with 999,973 rows
Saved customer_item_keys_chunk_77.parquet with 999,973 rows
Saved customer_item_keys_chunk_78.parquet with 999,973 rows
Saved customer_item_keys_chunk_79.parquet with 999,973 rows
Saved customer_item_keys_chunk_80.parquet with 999,973 rows
Saved customer_item_keys_chunk_81.parquet with 999,973 rows
Saved customer_item_keys_chunk_82.parquet with 999,973 rows
Saved customer_item_keys_chunk_83.parquet with 999,973 rows
Saved customer_item_keys_chunk_84.parquet with 999,973 rows
Saved customer_item_keys_chunk_85.parquet with 999,973 rows
Saved customer_item_keys_chunk_86.parquet with 999,973 rows
Saved customer_item_keys_chunk_87.parquet with 999,973 rows
Saved customer_item_keys_chunk_88.parquet with 999,973 rows
Saved customer_item_keys_chunk_89.parquet with 999,973 rows
Saved customer_item_keys_chunk_90.parquet with 999,973 rows
Saved customer_item_keys_chunk_91.parquet with 999,973 rows
Saved customer_item_keys_chunk_92.parquet with 999,973 rows
Saved customer_item_keys_chunk_93.parquet with 999,973 rows
Saved customer_item_keys_chunk_94.parquet with 999,973 rows
Saved customer_item_keys_chunk_95.parquet with 999,973 rows
Saved customer_item_keys_chunk_96.parquet with 999,973 rows
Saved customer_item_keys_chunk_97.parquet with 999,973 rows
Saved customer_item_keys_chunk_98.parquet with 999,973 rows
Saved customer_item_keys_chunk_99.parquet with 999,973 rows
Saved customer_item_keys_chunk_100.parquet with 999,973 rows
Saved customer_item_keys_chunk_101.parquet with 999,973 rows
Saved customer_item_keys_chunk_102.parquet with 999,973 rows
Saved customer_item_keys_chunk_103.parquet with 999,973 rows
Saved customer_item_keys_chunk_104.parquet with 999,973 rows
Saved customer_item_keys_chunk_105.parquet with 999,973 rows
Saved customer_item_keys_chunk_106.parquet with 999,973 rows
Saved customer_item_keys_chunk_107.parquet with 999,973 rows
Saved customer_item_keys_chunk_108.parquet with 999,973 rows
Saved customer_item_keys_chunk_109.parquet with 999,973 rows
Saved customer_item_keys_chunk_110.parquet with 999,973 rows
Saved customer_item_keys_chunk_111.parquet with 999,973 rows
Saved customer_item_keys_chunk_112.parquet with 999,973 rows
Saved customer_item_keys_chunk_113.parquet with 999,973 rows
Saved customer_item_keys_chunk_114.parquet with 999,973 rows
Saved customer_item_keys_chunk_115.parquet with 999,973 rows
Saved customer_item_keys_chunk_116.parquet with 999,973 rows
Saved customer_item_keys_chunk_117.parquet with 999,973 rows
Saved customer_item_keys_chunk_118.parquet with 999,973 rows
Saved customer_item_keys_chunk_119.parquet with 999,973 rows
Saved customer_item_keys_chunk_120.parquet with 999,973 rows
Saved customer_item_keys_chunk_121.parquet with 999,973 rows
Saved customer_item_keys_chunk_122.parquet with 999,973 rows
Saved customer_item_keys_chunk_123.parquet with 999,973 rows
Saved customer_item_keys_chunk_124.parquet with 999,973 rows
Saved customer_item_keys_chunk_125.parquet with 999,973 rows
Saved customer_item_keys_chunk_126.parquet with 999,973 rows
Saved customer_item_keys_chunk_127.parquet with 999,973 rows
Saved customer_item_keys_chunk_128.parquet with 999,973 rows
Saved customer_item_keys_chunk_129.parquet with 999,973 rows
Saved customer_item_keys_chunk_130.parquet with 999,973 rows
Saved customer_item_keys_chunk_131.parquet with 999,973 rows
Saved customer_item_keys_chunk_132.parquet with 999,973 rows
Saved customer_item_keys_chunk_133.parquet with 999,973 rows
Saved customer_item_keys_chunk_134.parquet with 999,973 rows
Saved customer_item_keys_chunk_135.parquet with 999,973 rows
Saved customer_item_keys_chunk_136.parquet with 999,973 rows
Saved customer_item_keys_chunk_137.parquet with 999,973 rows
Saved customer_item_keys_chunk_138.parquet with 999,973 rows
Saved customer_item_keys_chunk_139.parquet with 999,973 rows
Saved customer_item_keys_chunk_140.parquet with 999,973 rows
Saved customer_item_keys_chunk_141.parquet with 999,973 rows
Saved customer_item_keys_chunk_142.parquet with 999,973 rows
Saved customer_item_keys_chunk_143.parquet with 999,973 rows
Saved customer_item_keys_chunk_144.parquet with 999,973 rows
Saved customer_item_keys_chunk_145.parquet with 999,973 rows
Saved customer_item_keys_chunk_146.parquet with 999,973 rows
Saved customer_item_keys_chunk_147.parquet with 999,973 rows
Saved customer_item_keys_chunk_148.parquet with 999,973 rows
Saved customer_item_keys_chunk_149.parquet with 999,973 rows
Saved customer_item_keys_chunk_150.parquet with 999,973 rows
Saved customer_item_keys_chunk_151.parquet with 999,973 rows
Saved customer_item_keys_chunk_152.parquet with 999,973 rows
Saved customer_item_keys_chunk_153.parquet with 999,973 rows
Saved customer_item_keys_chunk_154.parquet with 999,973 rows
Saved customer_item_keys_chunk_155.parquet with 999,973 rows
Saved customer_item_keys_chunk_156.parquet with 999,973 rows
Saved customer_item_keys_chunk_157.parquet with 999,973 rows
Saved customer_item_keys_chunk_158.parquet with 999,973 rows
Saved customer_item_keys_chunk_159.parquet with 999,973 rows
Saved customer_item_keys_chunk_160.parquet with 999,973 rows
Saved customer_item_keys_chunk_161.parquet with 999,973 rows
Saved customer_item_keys_chunk_162.parquet with 999,973 rows
Saved customer_item_keys_chunk_163.parquet with 999,973 rows
Saved customer_item_keys_chunk_164.parquet with 999,973 rows
Saved customer_item_keys_chunk_165.parquet with 999,973 rows
Saved customer_item_keys_chunk_166.parquet with 999,973 rows
Saved customer_item_keys_chunk_167.parquet with 999,973 rows
Saved customer_item_keys_chunk_168.parquet with 999,973 rows
Saved customer_item_keys_chunk_169.parquet with 999,973 rows
Saved customer_item_keys_chunk_170.parquet with 999,973 rows
Saved customer_item_keys_chunk_171.parquet with 999,973 rows
Saved customer_item_keys_chunk_172.parquet with 999,973 rows
Saved customer_item_keys_chunk_173.parquet with 999,973 rows
Saved customer_item_keys_chunk_174.parquet with 999,973 rows
Saved customer_item_keys_chunk_175.parquet with 999,973 rows
Saved customer_item_keys_chunk_176.parquet with 999,973 rows
Saved customer_item_keys_chunk_177.parquet with 999,973 rows
Saved customer_item_keys_chunk_178.parquet with 999,973 rows
Saved customer_item_keys_chunk_179.parquet with 999,973 rows
Saved customer_item_keys_chunk_180.parquet with 999,973 rows
Saved customer_item_keys_chunk_181.parquet with 999,973 rows
Saved customer_item_keys_chunk_182.parquet with 999,973 rows
Saved customer_item_keys_chunk_183.parquet with 999,973 rows
Saved customer_item_keys_chunk_184.parquet with 999,973 rows
Saved customer_item_keys_chunk_185.parquet with 999,973 rows
Saved customer_item_keys_chunk_186.parquet with 723,426 rows
Total rows generated: 186,718,404

In [86]:
import polars as pl
from pathlib import Path

CHUNK_FOLDER = "cus_item_key"
PURCHASED_FILE = "item_Da_mua/customer_item_purchased.parquet"
OUTPUT_FOLDER = "cus_item_key_filter"

Path(OUTPUT_FOLDER).mkdir(exist_ok=True)

# Load các cặp đã mua (lazy, streaming)
purchased = pl.scan_parquet(PURCHASED_FILE).select(["customer_id", "item_id"])

chunk_files = sorted(Path(CHUNK_FOLDER).glob("*.parquet"))
print(f"🔹 Found {len(chunk_files)} chunks")

for i, chunk_path in enumerate(chunk_files, 1):
    print(f"[{i}/{len(chunk_files)}] Filtering {chunk_path.name}")

    chunk = pl.scan_parquet(chunk_path)

    # left join anti: giữ các cặp không có trong purchased
    filtered = chunk.join(
        purchased,
        on=["customer_id", "item_id"],
        how="anti"
    )

    # ghi ra output
    out_path = Path(OUTPUT_FOLDER) / chunk_path.name
    filtered.collect(streaming=True).write_parquet(out_path)

    print(f"  ✅ Saved filtered chunk → {out_path.name}")

print("🎉 DONE: All chunks filtered")

🔹 Found 204 chunks
[1/204] Filtering customer_item_keys_chunk_0.parquet

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_3540\2927891684.py:30: DeprecationWarning: the `streaming` parameter was deprecated in 1.25.0; use `engine` instead.
  filtered.collect(streaming=True).write_parquet(out_path)

  ✅ Saved filtered chunk → customer_item_keys_chunk_0.parquet
[2/204] Filtering customer_item_keys_chunk_1.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_1.parquet
[3/204] Filtering customer_item_keys_chunk_10.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_10.parquet
[4/204] Filtering customer_item_keys_chunk_100.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_100.parquet
[5/204] Filtering customer_item_keys_chunk_101.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_101.parquet
[6/204] Filtering customer_item_keys_chunk_102.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_102.parquet
[7/204] Filtering customer_item_keys_chunk_103.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_103.parquet
[8/204] Filtering customer_item_keys_chunk_104.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_104.parquet
[9/204] Filtering customer_item_keys_chunk_105.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_105.parquet
[10/204] Filtering customer_item_keys_chunk_106.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_106.parquet
[11/204] Filtering customer_item_keys_chunk_107.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_107.parquet
[12/204] Filtering customer_item_keys_chunk_108.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_108.parquet
[13/204] Filtering customer_item_keys_chunk_109.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_109.parquet
[14/204] Filtering customer_item_keys_chunk_11.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_11.parquet
[15/204] Filtering customer_item_keys_chunk_110.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_110.parquet
[16/204] Filtering customer_item_keys_chunk_111.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_111.parquet
[17/204] Filtering customer_item_keys_chunk_112.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_112.parquet
[18/204] Filtering customer_item_keys_chunk_113.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_113.parquet
[19/204] Filtering customer_item_keys_chunk_114.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_114.parquet
[20/204] Filtering customer_item_keys_chunk_115.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_115.parquet
[21/204] Filtering customer_item_keys_chunk_116.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_116.parquet
[22/204] Filtering customer_item_keys_chunk_117.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_117.parquet
[23/204] Filtering customer_item_keys_chunk_118.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_118.parquet
[24/204] Filtering customer_item_keys_chunk_119.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_119.parquet
[25/204] Filtering customer_item_keys_chunk_12.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_12.parquet
[26/204] Filtering customer_item_keys_chunk_120.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_120.parquet
[27/204] Filtering customer_item_keys_chunk_121.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_121.parquet
[28/204] Filtering customer_item_keys_chunk_122.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_122.parquet
[29/204] Filtering customer_item_keys_chunk_123.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_123.parquet
[30/204] Filtering customer_item_keys_chunk_124.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_124.parquet
[31/204] Filtering customer_item_keys_chunk_125.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_125.parquet
[32/204] Filtering customer_item_keys_chunk_126.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_126.parquet
[33/204] Filtering customer_item_keys_chunk_127.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_127.parquet
[34/204] Filtering customer_item_keys_chunk_128.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_128.parquet
[35/204] Filtering customer_item_keys_chunk_129.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_129.parquet
[36/204] Filtering customer_item_keys_chunk_13.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_13.parquet
[37/204] Filtering customer_item_keys_chunk_130.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_130.parquet
[38/204] Filtering customer_item_keys_chunk_131.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_131.parquet
[39/204] Filtering customer_item_keys_chunk_132.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_132.parquet
[40/204] Filtering customer_item_keys_chunk_133.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_133.parquet
[41/204] Filtering customer_item_keys_chunk_134.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_134.parquet
[42/204] Filtering customer_item_keys_chunk_135.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_135.parquet
[43/204] Filtering customer_item_keys_chunk_136.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_136.parquet
[44/204] Filtering customer_item_keys_chunk_137.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_137.parquet
[45/204] Filtering customer_item_keys_chunk_138.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_138.parquet
[46/204] Filtering customer_item_keys_chunk_139.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_139.parquet
[47/204] Filtering customer_item_keys_chunk_14.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_14.parquet
[48/204] Filtering customer_item_keys_chunk_140.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_140.parquet
[49/204] Filtering customer_item_keys_chunk_141.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_141.parquet
[50/204] Filtering customer_item_keys_chunk_142.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_142.parquet
[51/204] Filtering customer_item_keys_chunk_143.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_143.parquet
[52/204] Filtering customer_item_keys_chunk_144.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_144.parquet
[53/204] Filtering customer_item_keys_chunk_145.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_145.parquet
[54/204] Filtering customer_item_keys_chunk_146.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_146.parquet
[55/204] Filtering customer_item_keys_chunk_147.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_147.parquet
[56/204] Filtering customer_item_keys_chunk_148.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_148.parquet
[57/204] Filtering customer_item_keys_chunk_149.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_149.parquet
[58/204] Filtering customer_item_keys_chunk_15.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_15.parquet
[59/204] Filtering customer_item_keys_chunk_150.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_150.parquet
[60/204] Filtering customer_item_keys_chunk_151.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_151.parquet
[61/204] Filtering customer_item_keys_chunk_152.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_152.parquet
[62/204] Filtering customer_item_keys_chunk_153.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_153.parquet
[63/204] Filtering customer_item_keys_chunk_154.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_154.parquet
[64/204] Filtering customer_item_keys_chunk_155.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_155.parquet
[65/204] Filtering customer_item_keys_chunk_156.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_156.parquet
[66/204] Filtering customer_item_keys_chunk_157.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_157.parquet
[67/204] Filtering customer_item_keys_chunk_158.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_158.parquet
[68/204] Filtering customer_item_keys_chunk_159.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_159.parquet
[69/204] Filtering customer_item_keys_chunk_16.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_16.parquet
[70/204] Filtering customer_item_keys_chunk_160.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_160.parquet
[71/204] Filtering customer_item_keys_chunk_161.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_161.parquet
[72/204] Filtering customer_item_keys_chunk_162.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_162.parquet
[73/204] Filtering customer_item_keys_chunk_163.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_163.parquet
[74/204] Filtering customer_item_keys_chunk_164.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_164.parquet
[75/204] Filtering customer_item_keys_chunk_165.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_165.parquet
[76/204] Filtering customer_item_keys_chunk_166.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_166.parquet
[77/204] Filtering customer_item_keys_chunk_167.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_167.parquet
[78/204] Filtering customer_item_keys_chunk_168.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_168.parquet
[79/204] Filtering customer_item_keys_chunk_169.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_169.parquet
[80/204] Filtering customer_item_keys_chunk_17.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_17.parquet
[81/204] Filtering customer_item_keys_chunk_170.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_170.parquet
[82/204] Filtering customer_item_keys_chunk_171.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_171.parquet
[83/204] Filtering customer_item_keys_chunk_172.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_172.parquet
[84/204] Filtering customer_item_keys_chunk_173.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_173.parquet
[85/204] Filtering customer_item_keys_chunk_174.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_174.parquet
[86/204] Filtering customer_item_keys_chunk_175.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_175.parquet
[87/204] Filtering customer_item_keys_chunk_176.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_176.parquet
[88/204] Filtering customer_item_keys_chunk_177.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_177.parquet
[89/204] Filtering customer_item_keys_chunk_178.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_178.parquet
[90/204] Filtering customer_item_keys_chunk_179.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_179.parquet
[91/204] Filtering customer_item_keys_chunk_18.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_18.parquet
[92/204] Filtering customer_item_keys_chunk_180.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_180.parquet
[93/204] Filtering customer_item_keys_chunk_181.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_181.parquet
[94/204] Filtering customer_item_keys_chunk_182.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_182.parquet
[95/204] Filtering customer_item_keys_chunk_183.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_183.parquet
[96/204] Filtering customer_item_keys_chunk_184.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_184.parquet
[97/204] Filtering customer_item_keys_chunk_185.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_185.parquet
[98/204] Filtering customer_item_keys_chunk_186.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_186.parquet
[99/204] Filtering customer_item_keys_chunk_187.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_187.parquet
[100/204] Filtering customer_item_keys_chunk_188.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_188.parquet
[101/204] Filtering customer_item_keys_chunk_189.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_189.parquet
[102/204] Filtering customer_item_keys_chunk_19.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_19.parquet
[103/204] Filtering customer_item_keys_chunk_190.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_190.parquet
[104/204] Filtering customer_item_keys_chunk_191.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_191.parquet
[105/204] Filtering customer_item_keys_chunk_192.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_192.parquet
[106/204] Filtering customer_item_keys_chunk_193.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_193.parquet
[107/204] Filtering customer_item_keys_chunk_194.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_194.parquet
[108/204] Filtering customer_item_keys_chunk_195.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_195.parquet
[109/204] Filtering customer_item_keys_chunk_196.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_196.parquet
[110/204] Filtering customer_item_keys_chunk_197.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_197.parquet
[111/204] Filtering customer_item_keys_chunk_198.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_198.parquet
[112/204] Filtering customer_item_keys_chunk_199.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_199.parquet
[113/204] Filtering customer_item_keys_chunk_2.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_2.parquet
[114/204] Filtering customer_item_keys_chunk_20.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_20.parquet
[115/204] Filtering customer_item_keys_chunk_200.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_200.parquet
[116/204] Filtering customer_item_keys_chunk_201.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_201.parquet
[117/204] Filtering customer_item_keys_chunk_202.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_202.parquet
[118/204] Filtering customer_item_keys_chunk_203.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_203.parquet
[119/204] Filtering customer_item_keys_chunk_21.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_21.parquet
[120/204] Filtering customer_item_keys_chunk_22.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_22.parquet
[121/204] Filtering customer_item_keys_chunk_23.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_23.parquet
[122/204] Filtering customer_item_keys_chunk_24.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_24.parquet
[123/204] Filtering customer_item_keys_chunk_25.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_25.parquet
[124/204] Filtering customer_item_keys_chunk_26.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_26.parquet
[125/204] Filtering customer_item_keys_chunk_27.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_27.parquet
[126/204] Filtering customer_item_keys_chunk_28.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_28.parquet
[127/204] Filtering customer_item_keys_chunk_29.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_29.parquet
[128/204] Filtering customer_item_keys_chunk_3.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_3.parquet
[129/204] Filtering customer_item_keys_chunk_30.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_30.parquet
[130/204] Filtering customer_item_keys_chunk_31.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_31.parquet
[131/204] Filtering customer_item_keys_chunk_32.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_32.parquet
[132/204] Filtering customer_item_keys_chunk_33.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_33.parquet
[133/204] Filtering customer_item_keys_chunk_34.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_34.parquet
[134/204] Filtering customer_item_keys_chunk_35.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_35.parquet
[135/204] Filtering customer_item_keys_chunk_36.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_36.parquet
[136/204] Filtering customer_item_keys_chunk_37.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_37.parquet
[137/204] Filtering customer_item_keys_chunk_38.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_38.parquet
[138/204] Filtering customer_item_keys_chunk_39.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_39.parquet
[139/204] Filtering customer_item_keys_chunk_4.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_4.parquet
[140/204] Filtering customer_item_keys_chunk_40.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_40.parquet
[141/204] Filtering customer_item_keys_chunk_41.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_41.parquet
[142/204] Filtering customer_item_keys_chunk_42.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_42.parquet
[143/204] Filtering customer_item_keys_chunk_43.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_43.parquet
[144/204] Filtering customer_item_keys_chunk_44.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_44.parquet
[145/204] Filtering customer_item_keys_chunk_45.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_45.parquet
[146/204] Filtering customer_item_keys_chunk_46.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_46.parquet
[147/204] Filtering customer_item_keys_chunk_47.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_47.parquet
[148/204] Filtering customer_item_keys_chunk_48.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_48.parquet
[149/204] Filtering customer_item_keys_chunk_49.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_49.parquet
[150/204] Filtering customer_item_keys_chunk_5.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_5.parquet
[151/204] Filtering customer_item_keys_chunk_50.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_50.parquet
[152/204] Filtering customer_item_keys_chunk_51.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_51.parquet
[153/204] Filtering customer_item_keys_chunk_52.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_52.parquet
[154/204] Filtering customer_item_keys_chunk_53.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_53.parquet
[155/204] Filtering customer_item_keys_chunk_54.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_54.parquet
[156/204] Filtering customer_item_keys_chunk_55.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_55.parquet
[157/204] Filtering customer_item_keys_chunk_56.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_56.parquet
[158/204] Filtering customer_item_keys_chunk_57.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_57.parquet
[159/204] Filtering customer_item_keys_chunk_58.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_58.parquet
[160/204] Filtering customer_item_keys_chunk_59.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_59.parquet
[161/204] Filtering customer_item_keys_chunk_6.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_6.parquet
[162/204] Filtering customer_item_keys_chunk_60.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_60.parquet
[163/204] Filtering customer_item_keys_chunk_61.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_61.parquet
[164/204] Filtering customer_item_keys_chunk_62.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_62.parquet
[165/204] Filtering customer_item_keys_chunk_63.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_63.parquet
[166/204] Filtering customer_item_keys_chunk_64.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_64.parquet
[167/204] Filtering customer_item_keys_chunk_65.parquet
  ✅ Saved filtered chunk → customer_item_keys_chunk_65.parquet
[168/204] Filtering customer_item_keys_chunk_66.parquet

In [24]:
import polars as pl
from pathlib import Path

# ========= CONFIG =========
VAL_FILE = "features_train.parquet"

OUTPUT_DIR = Path("features_split")
OUTPUT_DIR.mkdir(exist_ok=True)

# ========= LOAD =========
features = pl.read_parquet(VAL_FILE)

# ========= DROP Y IF EXISTS =========
if "Y" in features.columns:
    features = features.drop("Y")

print("Loaded VAL (Y removed if existed)")

# ========= 1. customer-item =========
feat_cus_item = (
    features
    .select([
        "customer_id",
        "item_id",
        "X_1", "X_2", "X_3"
    ])
    .unique(
        subset=["customer_id", "item_id"],
        keep="first"
    )
)

feat_cus_item.write_parquet(OUTPUT_DIR / "feat_cus_item.parquet")
print("Saved feat_cus_item.parquet")

# ========= 2. item =========
feat_item = (
    features
    .select([
        "item_id",
        "X_4", "X_5"
    ])
    .unique(
        subset=["item_id"],
        keep="first"
    )
)

feat_item.write_parquet(OUTPUT_DIR / "feat_item.parquet")
print("Saved feat_item.parquet")

# ========= 3. customer =========
feat_cus = (
    features
    .select([
        "customer_id",
        "X_6", "X_7", "X_8",
        "X_9", "X_10", "X_11",
        "X_12", "X_13", "X_14",
        "X_15", "X_16"
    ])
    .unique(
        subset=["customer_id"],
        keep="first"
    )
)

feat_cus.write_parquet(OUTPUT_DIR / "feat_cus.parquet")
print("Saved feat_cus.parquet")

print("🎉 DONE: features_split created from VAL only")

Loaded VAL (Y removed if existed)
Saved feat_cus_item.parquet
Saved feat_item.parquet
Saved feat_cus.parquet
🎉 DONE: features_split created from VAL only

In [25]:
pl.scan_parquet("features_split/feat_cus_item.parquet") \
  .unique(["customer_id", "item_id"]) \
  .collect(engine="streaming") \
  .write_parquet("features_split/feat_cus_item_u.parquet")

pl.scan_parquet("features_split/feat_item.parquet") \
  .unique("item_id") \
  .collect(engine="streaming") \
  .write_parquet("features_split/feat_item_u.parquet")

pl.scan_parquet("features_split/feat_cus.parquet") \
  .unique("customer_id") \
  .collect(engine="streaming") \
  .write_parquet("features_split/feat_cus_u.parquet")

print("finish")

finish

In [26]:
import polars as pl
from pathlib import Path

FEATURE_COLS = [f"X_{i}" for i in range(1, 17)]

def join_features_chunks_pipeline_merge_all_add_Y(
    test_folder: str,
    feat_cus_item_parquet: str,
    feat_item_parquet: str,
    feat_cus_parquet: str,
    output_folder: str
):
    test_folder = Path(test_folder)
    out_dir = Path(output_folder)
    out_dir.mkdir(exist_ok=True)

    # Load features (lazy)
    feat_cus_item = pl.scan_parquet(feat_cus_item_parquet)
    feat_item     = pl.scan_parquet(feat_item_parquet)
    feat_cus      = pl.scan_parquet(feat_cus_parquet)

    test_files = sorted(test_folder.glob("*.parquet"))
    print(f"🔹 Found {len(test_files)} test chunks")

    for idx, test_path in enumerate(test_files, 1):
        print(f"\n▶ [{idx}/{len(test_files)}] {test_path.name}")

        test = pl.scan_parquet(test_path)

        joined = (
            test
            .join(feat_item, on="item_id", how="left")
            .join(feat_cus, on="customer_id", how="left")
            .join(feat_cus_item, on=["customer_id", "item_id"], how="left")
            .fill_null(0)
            # 👉 thêm cột Y = 0.2
            .with_columns(
                pl.lit(0.2).alias("Y")
            )
        )

        # sắp xếp lại cột
        final_cols = (
            ["customer_id", "item_id"]
            + FEATURE_COLS
            + ["Y"]
        )

        joined = joined.select(final_cols)

        joined.collect(streaming=True).write_parquet(out_dir / test_path.name)
        print("  ✅ saved MERGED + X_1..X_16 + Y=0.2")

    print("\n🎉 DONE: added Y = 0.2 for all rows")

In [27]:
join_features_chunks_pipeline_merge_all_add_Y(
    test_folder="cus_item_key_filter",          # folder chứa các chunk test
    feat_cus_item_parquet="features_split/feat_cus_item_u.parquet",
    feat_item_parquet="features_split/feat_item_u.parquet",
    feat_cus_parquet="features_split/feat_cus_u.parquet",
    output_folder="cus_item_key_features_train"          # output merged + Y
)

🔹 Found 204 test chunks

▶ [1/204] customer_item_keys_chunk_0.parquet

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_17996\3580755331.py:51: DeprecationWarning: the `streaming` parameter was deprecated in 1.25.0; use `engine` instead.
  joined.collect(streaming=True).write_parquet(out_dir / test_path.name)

  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [2/204] customer_item_keys_chunk_1.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [3/204] customer_item_keys_chunk_10.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [4/204] customer_item_keys_chunk_100.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [5/204] customer_item_keys_chunk_101.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [6/204] customer_item_keys_chunk_102.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [7/204] customer_item_keys_chunk_103.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [8/204] customer_item_keys_chunk_104.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [9/204] customer_item_keys_chunk_105.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [10/204] customer_item_keys_chunk_106.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [11/204] customer_item_keys_chunk_107.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [12/204] customer_item_keys_chunk_108.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [13/204] customer_item_keys_chunk_109.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [14/204] customer_item_keys_chunk_11.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [15/204] customer_item_keys_chunk_110.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [16/204] customer_item_keys_chunk_111.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [17/204] customer_item_keys_chunk_112.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [18/204] customer_item_keys_chunk_113.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [19/204] customer_item_keys_chunk_114.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [20/204] customer_item_keys_chunk_115.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [21/204] customer_item_keys_chunk_116.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [22/204] customer_item_keys_chunk_117.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [23/204] customer_item_keys_chunk_118.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [24/204] customer_item_keys_chunk_119.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [25/204] customer_item_keys_chunk_12.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [26/204] customer_item_keys_chunk_120.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [27/204] customer_item_keys_chunk_121.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [28/204] customer_item_keys_chunk_122.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [29/204] customer_item_keys_chunk_123.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [30/204] customer_item_keys_chunk_124.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [31/204] customer_item_keys_chunk_125.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [32/204] customer_item_keys_chunk_126.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [33/204] customer_item_keys_chunk_127.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [34/204] customer_item_keys_chunk_128.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [35/204] customer_item_keys_chunk_129.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [36/204] customer_item_keys_chunk_13.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [37/204] customer_item_keys_chunk_130.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [38/204] customer_item_keys_chunk_131.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [39/204] customer_item_keys_chunk_132.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [40/204] customer_item_keys_chunk_133.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [41/204] customer_item_keys_chunk_134.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [42/204] customer_item_keys_chunk_135.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [43/204] customer_item_keys_chunk_136.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [44/204] customer_item_keys_chunk_137.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [45/204] customer_item_keys_chunk_138.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [46/204] customer_item_keys_chunk_139.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [47/204] customer_item_keys_chunk_14.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [48/204] customer_item_keys_chunk_140.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [49/204] customer_item_keys_chunk_141.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [50/204] customer_item_keys_chunk_142.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [51/204] customer_item_keys_chunk_143.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [52/204] customer_item_keys_chunk_144.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [53/204] customer_item_keys_chunk_145.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [54/204] customer_item_keys_chunk_146.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [55/204] customer_item_keys_chunk_147.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [56/204] customer_item_keys_chunk_148.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [57/204] customer_item_keys_chunk_149.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [58/204] customer_item_keys_chunk_15.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [59/204] customer_item_keys_chunk_150.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [60/204] customer_item_keys_chunk_151.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [61/204] customer_item_keys_chunk_152.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [62/204] customer_item_keys_chunk_153.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [63/204] customer_item_keys_chunk_154.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [64/204] customer_item_keys_chunk_155.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [65/204] customer_item_keys_chunk_156.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [66/204] customer_item_keys_chunk_157.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [67/204] customer_item_keys_chunk_158.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [68/204] customer_item_keys_chunk_159.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [69/204] customer_item_keys_chunk_16.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [70/204] customer_item_keys_chunk_160.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [71/204] customer_item_keys_chunk_161.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [72/204] customer_item_keys_chunk_162.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [73/204] customer_item_keys_chunk_163.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [74/204] customer_item_keys_chunk_164.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [75/204] customer_item_keys_chunk_165.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [76/204] customer_item_keys_chunk_166.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [77/204] customer_item_keys_chunk_167.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [78/204] customer_item_keys_chunk_168.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [79/204] customer_item_keys_chunk_169.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [80/204] customer_item_keys_chunk_17.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [81/204] customer_item_keys_chunk_170.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [82/204] customer_item_keys_chunk_171.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [83/204] customer_item_keys_chunk_172.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [84/204] customer_item_keys_chunk_173.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [85/204] customer_item_keys_chunk_174.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [86/204] customer_item_keys_chunk_175.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [87/204] customer_item_keys_chunk_176.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [88/204] customer_item_keys_chunk_177.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [89/204] customer_item_keys_chunk_178.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [90/204] customer_item_keys_chunk_179.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [91/204] customer_item_keys_chunk_18.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [92/204] customer_item_keys_chunk_180.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [93/204] customer_item_keys_chunk_181.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [94/204] customer_item_keys_chunk_182.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [95/204] customer_item_keys_chunk_183.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [96/204] customer_item_keys_chunk_184.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [97/204] customer_item_keys_chunk_185.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [98/204] customer_item_keys_chunk_186.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [99/204] customer_item_keys_chunk_187.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [100/204] customer_item_keys_chunk_188.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [101/204] customer_item_keys_chunk_189.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [102/204] customer_item_keys_chunk_19.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [103/204] customer_item_keys_chunk_190.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [104/204] customer_item_keys_chunk_191.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [105/204] customer_item_keys_chunk_192.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [106/204] customer_item_keys_chunk_193.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [107/204] customer_item_keys_chunk_194.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [108/204] customer_item_keys_chunk_195.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [109/204] customer_item_keys_chunk_196.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [110/204] customer_item_keys_chunk_197.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [111/204] customer_item_keys_chunk_198.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [112/204] customer_item_keys_chunk_199.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [113/204] customer_item_keys_chunk_2.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [114/204] customer_item_keys_chunk_20.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [115/204] customer_item_keys_chunk_200.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [116/204] customer_item_keys_chunk_201.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [117/204] customer_item_keys_chunk_202.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [118/204] customer_item_keys_chunk_203.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [119/204] customer_item_keys_chunk_21.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [120/204] customer_item_keys_chunk_22.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [121/204] customer_item_keys_chunk_23.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [122/204] customer_item_keys_chunk_24.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [123/204] customer_item_keys_chunk_25.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [124/204] customer_item_keys_chunk_26.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [125/204] customer_item_keys_chunk_27.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [126/204] customer_item_keys_chunk_28.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [127/204] customer_item_keys_chunk_29.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [128/204] customer_item_keys_chunk_3.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [129/204] customer_item_keys_chunk_30.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [130/204] customer_item_keys_chunk_31.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [131/204] customer_item_keys_chunk_32.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [132/204] customer_item_keys_chunk_33.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [133/204] customer_item_keys_chunk_34.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [134/204] customer_item_keys_chunk_35.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [135/204] customer_item_keys_chunk_36.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [136/204] customer_item_keys_chunk_37.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [137/204] customer_item_keys_chunk_38.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [138/204] customer_item_keys_chunk_39.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [139/204] customer_item_keys_chunk_4.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [140/204] customer_item_keys_chunk_40.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [141/204] customer_item_keys_chunk_41.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [142/204] customer_item_keys_chunk_42.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [143/204] customer_item_keys_chunk_43.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [144/204] customer_item_keys_chunk_44.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [145/204] customer_item_keys_chunk_45.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [146/204] customer_item_keys_chunk_46.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [147/204] customer_item_keys_chunk_47.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [148/204] customer_item_keys_chunk_48.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [149/204] customer_item_keys_chunk_49.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [150/204] customer_item_keys_chunk_5.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [151/204] customer_item_keys_chunk_50.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [152/204] customer_item_keys_chunk_51.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [153/204] customer_item_keys_chunk_52.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [154/204] customer_item_keys_chunk_53.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [155/204] customer_item_keys_chunk_54.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [156/204] customer_item_keys_chunk_55.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [157/204] customer_item_keys_chunk_56.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [158/204] customer_item_keys_chunk_57.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [159/204] customer_item_keys_chunk_58.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [160/204] customer_item_keys_chunk_59.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [161/204] customer_item_keys_chunk_6.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [162/204] customer_item_keys_chunk_60.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [163/204] customer_item_keys_chunk_61.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [164/204] customer_item_keys_chunk_62.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [165/204] customer_item_keys_chunk_63.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [166/204] customer_item_keys_chunk_64.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [167/204] customer_item_keys_chunk_65.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [168/204] customer_item_keys_chunk_66.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [169/204] customer_item_keys_chunk_67.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [170/204] customer_item_keys_chunk_68.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [171/204] customer_item_keys_chunk_69.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [172/204] customer_item_keys_chunk_7.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [173/204] customer_item_keys_chunk_70.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [174/204] customer_item_keys_chunk_71.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [175/204] customer_item_keys_chunk_72.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [176/204] customer_item_keys_chunk_73.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [177/204] customer_item_keys_chunk_74.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [178/204] customer_item_keys_chunk_75.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [179/204] customer_item_keys_chunk_76.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [180/204] customer_item_keys_chunk_77.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [181/204] customer_item_keys_chunk_78.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [182/204] customer_item_keys_chunk_79.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [183/204] customer_item_keys_chunk_8.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [184/204] customer_item_keys_chunk_80.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [185/204] customer_item_keys_chunk_81.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [186/204] customer_item_keys_chunk_82.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [187/204] customer_item_keys_chunk_83.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [188/204] customer_item_keys_chunk_84.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [189/204] customer_item_keys_chunk_85.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [190/204] customer_item_keys_chunk_86.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [191/204] customer_item_keys_chunk_87.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [192/204] customer_item_keys_chunk_88.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [193/204] customer_item_keys_chunk_89.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [194/204] customer_item_keys_chunk_9.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [195/204] customer_item_keys_chunk_90.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [196/204] customer_item_keys_chunk_91.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [197/204] customer_item_keys_chunk_92.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [198/204] customer_item_keys_chunk_93.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [199/204] customer_item_keys_chunk_94.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [200/204] customer_item_keys_chunk_95.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [201/204] customer_item_keys_chunk_96.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [202/204] customer_item_keys_chunk_97.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [203/204] customer_item_keys_chunk_98.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [204/204] customer_item_keys_chunk_99.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

🎉 DONE: added Y = 0.2 for all rows

In [28]:
df= pl.read_parquet("cus_item_key_features_train/customer_item_keys_chunk_95.parquet")
df.head(1)

shape: (1, 19)
┌─────────────┬───────────────┬─────┬─────┬───┬──────┬──────┬──────┬─────┐
│ customer_id ┆ item_id       ┆ X_1 ┆ X_2 ┆ … ┆ X_14 ┆ X_15 ┆ X_16 ┆ Y   │
│ ---         ┆ ---           ┆ --- ┆ --- ┆   ┆ ---  ┆ ---  ┆ ---  ┆ --- │
│ i32         ┆ str           ┆ u32 ┆ u32 ┆   ┆ i64  ┆ f64  ┆ i64  ┆ f64 │
╞═════════════╪═══════════════╪═════╪═════╪═══╪══════╪══════╪══════╪═════╡
│ 8197400     ┆ 4759000000002 ┆ 0   ┆ 0   ┆ … ┆ 0    ┆ 0.0  ┆ 2    ┆ 0.2 │
└─────────────┴───────────────┴─────┴─────┴───┴──────┴──────┴──────┴─────┘

In [10]:
import polars as pl
from pathlib import Path
import xgboost as xgb
import numpy as np

# ================= CONFIG =================
PARQUET_DIR = Path("cus_item_key_features_train")

FEATURE_COLS = [f"X_{i}" for i in range(1, 17)]
LABEL_COL = "Y"

BATCH_SIZE = 400_000      # chỉnh theo RAM / VRAM
ROUNDS_PER_BATCH = 10    # số cây cho mỗi batch
MODEL_PATH = "xgb_model_stream.json"

DEVICE = "cuda"   # "cuda" hoặc "cpu"
# =========================================


# ========= XGBOOST PARAMS =========
params = {
    "objective": "reg:squarederror",
    "eval_metric": "rmse",
    "learning_rate": 0.05,
    "max_depth": 8,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "tree_method": "hist",
    "device": DEVICE,
    "seed": 42,
}

# ========= LOAD FILE LIST =========
files = sorted(PARQUET_DIR.glob("customer_item_keys_chunk_*.parquet"))
print(f"🔹 Found {len(files)} parquet files")

booster = None
total_trained = 0

# ========= TRAIN STREAMING =========
for fi, pq in enumerate(files, 1):
    print(f"\n▶ [{fi}/{len(files)}] Training {pq.name}")

    lf = pl.scan_parquet(pq)
    n_rows = lf.select(pl.len()).collect().item()
    print(f"   Rows: {n_rows:,}")

    for start in range(0, n_rows, BATCH_SIZE):
        batch = (
            lf
            .slice(start, BATCH_SIZE)
            .select(FEATURE_COLS + [LABEL_COL])
            .collect(streaming=True)
        )

        X = batch.select(FEATURE_COLS).to_numpy()
        y = batch[LABEL_COL].to_numpy()

        dtrain = xgb.DMatrix(X, label=y)

        booster = xgb.train(
            params=params,
            dtrain=dtrain,
            num_boost_round=ROUNDS_PER_BATCH,
            xgb_model=booster,   # ⭐ tiếp tục train
            verbose_eval=False
        )

        total_trained += len(y)
        print(f"   ✓ trained {total_trained:,} rows")

print("\n🎉 DONE: trained XGBoost streaming")
print(f"📊 Total rows trained: {total_trained:,}")

# ========= SAVE MODEL =========
booster.save_model(MODEL_PATH)
print(f"💾 Model saved to: {MODEL_PATH}")

🔹 Found 231 parquet files

▶ [1/231] Training customer_item_keys_chunk_0.parquet
   Rows: 982,305

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_25560\3367675987.py:53: DeprecationWarning: the `streaming` parameter was deprecated in 1.25.0; use `engine` instead.
  .collect(streaming=True)

   ✓ trained 400,000 rows
   ✓ trained 800,000 rows
   ✓ trained 982,305 rows

▶ [2/231] Training customer_item_keys_chunk_1.parquet
   Rows: 981,920
   ✓ trained 1,382,305 rows
   ✓ trained 1,782,305 rows
   ✓ trained 1,964,225 rows

▶ [3/231] Training customer_item_keys_chunk_10.parquet
   Rows: 982,497
   ✓ trained 2,364,225 rows
   ✓ trained 2,764,225 rows
   ✓ trained 2,946,722 rows

▶ [4/231] Training customer_item_keys_chunk_100.parquet
   Rows: 981,667
   ✓ trained 3,346,722 rows
   ✓ trained 3,746,722 rows
   ✓ trained 3,928,389 rows

▶ [5/231] Training customer_item_keys_chunk_101.parquet
   Rows: 982,132
   ✓ trained 4,328,389 rows
   ✓ trained 4,728,389 rows
   ✓ trained 4,910,521 rows

▶ [6/231] Training customer_item_keys_chunk_102.parquet
   Rows: 982,608
   ✓ trained 5,310,521 rows
   ✓ trained 5,710,521 rows
   ✓ trained 5,893,129 rows

▶ [7/231] Training customer_item_keys_chunk_103.parquet
   Rows: 982,694
   ✓ trained 6,293,129 rows
   ✓ trained 6,693,129 rows
   ✓ trained 6,875,823 rows

▶ [8/231] Training customer_item_keys_chunk_104.parquet
   Rows: 982,385
   ✓ trained 7,275,823 rows
   ✓ trained 7,675,823 rows
   ✓ trained 7,858,208 rows

▶ [9/231] Training customer_item_keys_chunk_105.parquet
   Rows: 982,447
   ✓ trained 8,258,208 rows
   ✓ trained 8,658,208 rows
   ✓ trained 8,840,655 rows

▶ [10/231] Training customer_item_keys_chunk_106.parquet
   Rows: 982,337
   ✓ trained 9,240,655 rows
   ✓ trained 9,640,655 rows
   ✓ trained 9,822,992 rows

▶ [11/231] Training customer_item_keys_chunk_107.parquet
   Rows: 982,498
   ✓ trained 10,222,992 rows
   ✓ trained 10,622,992 rows
   ✓ trained 10,805,490 rows

▶ [12/231] Training customer_item_keys_chunk_108.parquet
   Rows: 982,063
   ✓ trained 11,205,490 rows
   ✓ trained 11,605,490 rows
   ✓ trained 11,787,553 rows

▶ [13/231] Training customer_item_keys_chunk_109.parquet
   Rows: 982,355
   ✓ trained 12,187,553 rows
   ✓ trained 12,587,553 rows
   ✓ trained 12,769,908 rows

▶ [14/231] Training customer_item_keys_chunk_11.parquet
   Rows: 982,384
   ✓ trained 13,169,908 rows
   ✓ trained 13,569,908 rows
   ✓ trained 13,752,292 rows

▶ [15/231] Training customer_item_keys_chunk_110.parquet
   Rows: 982,449
   ✓ trained 14,152,292 rows
   ✓ trained 14,552,292 rows
   ✓ trained 14,734,741 rows

▶ [16/231] Training customer_item_keys_chunk_111.parquet
   Rows: 982,285
   ✓ trained 15,134,741 rows
   ✓ trained 15,534,741 rows
   ✓ trained 15,717,026 rows

▶ [17/231] Training customer_item_keys_chunk_112.parquet
   Rows: 982,388
   ✓ trained 16,117,026 rows
   ✓ trained 16,517,026 rows
   ✓ trained 16,699,414 rows

▶ [18/231] Training customer_item_keys_chunk_113.parquet
   Rows: 982,296
   ✓ trained 17,099,414 rows
   ✓ trained 17,499,414 rows
   ✓ trained 17,681,710 rows

▶ [19/231] Training customer_item_keys_chunk_114.parquet
   Rows: 981,954
   ✓ trained 18,081,710 rows
   ✓ trained 18,481,710 rows
   ✓ trained 18,663,664 rows

▶ [20/231] Training customer_item_keys_chunk_115.parquet
   Rows: 982,259
   ✓ trained 19,063,664 rows
   ✓ trained 19,463,664 rows
   ✓ trained 19,645,923 rows

▶ [21/231] Training customer_item_keys_chunk_116.parquet
   Rows: 982,819
   ✓ trained 20,045,923 rows
   ✓ trained 20,445,923 rows
   ✓ trained 20,628,742 rows

▶ [22/231] Training customer_item_keys_chunk_117.parquet
   Rows: 982,409
   ✓ trained 21,028,742 rows
   ✓ trained 21,428,742 rows
   ✓ trained 21,611,151 rows

▶ [23/231] Training customer_item_keys_chunk_118.parquet
   Rows: 981,703
   ✓ trained 22,011,151 rows
   ✓ trained 22,411,151 rows
   ✓ trained 22,592,854 rows

▶ [24/231] Training customer_item_keys_chunk_119.parquet
   Rows: 981,948
   ✓ trained 22,992,854 rows
   ✓ trained 23,392,854 rows
   ✓ trained 23,574,802 rows

▶ [25/231] Training customer_item_keys_chunk_12.parquet
   Rows: 982,267
   ✓ trained 23,974,802 rows
   ✓ trained 24,374,802 rows
   ✓ trained 24,557,069 rows

▶ [26/231] Training customer_item_keys_chunk_120.parquet
   Rows: 982,326
   ✓ trained 24,957,069 rows
   ✓ trained 25,357,069 rows
   ✓ trained 25,539,395 rows

▶ [27/231] Training customer_item_keys_chunk_121.parquet
   Rows: 982,045
   ✓ trained 25,939,395 rows
   ✓ trained 26,339,395 rows
   ✓ trained 26,521,440 rows

▶ [28/231] Training customer_item_keys_chunk_122.parquet
   Rows: 982,985
   ✓ trained 26,921,440 rows
   ✓ trained 27,321,440 rows
   ✓ trained 27,504,425 rows

▶ [29/231] Training customer_item_keys_chunk_123.parquet
   Rows: 981,800
   ✓ trained 27,904,425 rows
   ✓ trained 28,304,425 rows
   ✓ trained 28,486,225 rows

▶ [30/231] Training customer_item_keys_chunk_124.parquet
   Rows: 982,476
   ✓ trained 28,886,225 rows
   ✓ trained 29,286,225 rows
   ✓ trained 29,468,701 rows

▶ [31/231] Training customer_item_keys_chunk_125.parquet
   Rows: 982,432
   ✓ trained 29,868,701 rows
   ✓ trained 30,268,701 rows
   ✓ trained 30,451,133 rows

▶ [32/231] Training customer_item_keys_chunk_126.parquet
   Rows: 982,872
   ✓ trained 30,851,133 rows
   ✓ trained 31,251,133 rows
   ✓ trained 31,434,005 rows

▶ [33/231] Training customer_item_keys_chunk_127.parquet
   Rows: 982,559
   ✓ trained 31,834,005 rows
   ✓ trained 32,234,005 rows
   ✓ trained 32,416,564 rows

▶ [34/231] Training customer_item_keys_chunk_128.parquet
   Rows: 982,376
   ✓ trained 32,816,564 rows
   ✓ trained 33,216,564 rows
   ✓ trained 33,398,940 rows

▶ [35/231] Training customer_item_keys_chunk_129.parquet
   Rows: 982,019
   ✓ trained 33,798,940 rows
   ✓ trained 34,198,940 rows
   ✓ trained 34,380,959 rows

▶ [36/231] Training customer_item_keys_chunk_13.parquet
   Rows: 982,891
   ✓ trained 34,780,959 rows
   ✓ trained 35,180,959 rows
   ✓ trained 35,363,850 rows

▶ [37/231] Training customer_item_keys_chunk_130.parquet
   Rows: 982,507
   ✓ trained 35,763,850 rows
   ✓ trained 36,163,850 rows
   ✓ trained 36,346,357 rows

▶ [38/231] Training customer_item_keys_chunk_131.parquet
   Rows: 981,695
   ✓ trained 36,746,357 rows
   ✓ trained 37,146,357 rows
   ✓ trained 37,328,052 rows

▶ [39/231] Training customer_item_keys_chunk_132.parquet
   Rows: 982,191
   ✓ trained 37,728,052 rows
   ✓ trained 38,128,052 rows
   ✓ trained 38,310,243 rows

▶ [40/231] Training customer_item_keys_chunk_133.parquet
   Rows: 982,483
   ✓ trained 38,710,243 rows
   ✓ trained 39,110,243 rows
   ✓ trained 39,292,726 rows

▶ [41/231] Training customer_item_keys_chunk_134.parquet
   Rows: 982,685
   ✓ trained 39,692,726 rows
   ✓ trained 40,092,726 rows
   ✓ trained 40,275,411 rows

▶ [42/231] Training customer_item_keys_chunk_135.parquet
   Rows: 982,111
   ✓ trained 40,675,411 rows
   ✓ trained 41,075,411 rows
   ✓ trained 41,257,522 rows

▶ [43/231] Training customer_item_keys_chunk_136.parquet
   Rows: 982,604
   ✓ trained 41,657,522 rows
   ✓ trained 42,057,522 rows
   ✓ trained 42,240,126 rows

▶ [44/231] Training customer_item_keys_chunk_137.parquet
   Rows: 982,496
   ✓ trained 42,640,126 rows
   ✓ trained 43,040,126 rows
   ✓ trained 43,222,622 rows

▶ [45/231] Training customer_item_keys_chunk_138.parquet
   Rows: 982,487
   ✓ trained 43,622,622 rows
   ✓ trained 44,022,622 rows
   ✓ trained 44,205,109 rows

▶ [46/231] Training customer_item_keys_chunk_139.parquet
   Rows: 982,531
   ✓ trained 44,605,109 rows
   ✓ trained 45,005,109 rows
   ✓ trained 45,187,640 rows

▶ [47/231] Training customer_item_keys_chunk_14.parquet
   Rows: 981,911
   ✓ trained 45,587,640 rows
   ✓ trained 45,987,640 rows
   ✓ trained 46,169,551 rows

▶ [48/231] Training customer_item_keys_chunk_140.parquet
   Rows: 982,504
   ✓ trained 46,569,551 rows
   ✓ trained 46,969,551 rows
   ✓ trained 47,152,055 rows

▶ [49/231] Training customer_item_keys_chunk_141.parquet
   Rows: 982,239
   ✓ trained 47,552,055 rows
   ✓ trained 47,952,055 rows
   ✓ trained 48,134,294 rows

▶ [50/231] Training customer_item_keys_chunk_142.parquet
   Rows: 981,925
   ✓ trained 48,534,294 rows
   ✓ trained 48,934,294 rows
   ✓ trained 49,116,219 rows

▶ [51/231] Training customer_item_keys_chunk_143.parquet
   Rows: 982,383
   ✓ trained 49,516,219 rows
   ✓ trained 49,916,219 rows
   ✓ trained 50,098,602 rows

▶ [52/231] Training customer_item_keys_chunk_144.parquet
   Rows: 982,005
   ✓ trained 50,498,602 rows
   ✓ trained 50,898,602 rows
   ✓ trained 51,080,607 rows

▶ [53/231] Training customer_item_keys_chunk_145.parquet
   Rows: 982,228
   ✓ trained 51,480,607 rows
   ✓ trained 51,880,607 rows
   ✓ trained 52,062,835 rows

▶ [54/231] Training customer_item_keys_chunk_146.parquet
   Rows: 981,688
   ✓ trained 52,462,835 rows
   ✓ trained 52,862,835 rows
   ✓ trained 53,044,523 rows

▶ [55/231] Training customer_item_keys_chunk_147.parquet
   Rows: 982,789
   ✓ trained 53,444,523 rows
   ✓ trained 53,844,523 rows
   ✓ trained 54,027,312 rows

▶ [56/231] Training customer_item_keys_chunk_148.parquet
   Rows: 982,314
   ✓ trained 54,427,312 rows
   ✓ trained 54,827,312 rows
   ✓ trained 55,009,626 rows

▶ [57/231] Training customer_item_keys_chunk_149.parquet
   Rows: 982,355
   ✓ trained 55,409,626 rows
   ✓ trained 55,809,626 rows
   ✓ trained 55,991,981 rows

▶ [58/231] Training customer_item_keys_chunk_15.parquet
   Rows: 982,678
   ✓ trained 56,391,981 rows
   ✓ trained 56,791,981 rows
   ✓ trained 56,974,659 rows

▶ [59/231] Training customer_item_keys_chunk_150.parquet
   Rows: 982,128
   ✓ trained 57,374,659 rows
   ✓ trained 57,774,659 rows
   ✓ trained 57,956,787 rows

▶ [60/231] Training customer_item_keys_chunk_151.parquet
   Rows: 982,002
   ✓ trained 58,356,787 rows
   ✓ trained 58,756,787 rows
   ✓ trained 58,938,789 rows

▶ [61/231] Training customer_item_keys_chunk_152.parquet
   Rows: 982,132
   ✓ trained 59,338,789 rows
   ✓ trained 59,738,789 rows
   ✓ trained 59,920,921 rows

▶ [62/231] Training customer_item_keys_chunk_153.parquet
   Rows: 982,069
   ✓ trained 60,320,921 rows
   ✓ trained 60,720,921 rows
   ✓ trained 60,902,990 rows

▶ [63/231] Training customer_item_keys_chunk_154.parquet
   Rows: 981,530
   ✓ trained 61,302,990 rows
   ✓ trained 61,702,990 rows
   ✓ trained 61,884,520 rows

▶ [64/231] Training customer_item_keys_chunk_155.parquet
   Rows: 982,275
   ✓ trained 62,284,520 rows
   ✓ trained 62,684,520 rows
   ✓ trained 62,866,795 rows

▶ [65/231] Training customer_item_keys_chunk_156.parquet
   Rows: 982,235
   ✓ trained 63,266,795 rows
   ✓ trained 63,666,795 rows
   ✓ trained 63,849,030 rows

▶ [66/231] Training customer_item_keys_chunk_157.parquet
   Rows: 982,536
   ✓ trained 64,249,030 rows
   ✓ trained 64,649,030 rows
   ✓ trained 64,831,566 rows

▶ [67/231] Training customer_item_keys_chunk_158.parquet
   Rows: 981,993
   ✓ trained 65,231,566 rows
   ✓ trained 65,631,566 rows
   ✓ trained 65,813,559 rows

▶ [68/231] Training customer_item_keys_chunk_159.parquet
   Rows: 982,485
   ✓ trained 66,213,559 rows
   ✓ trained 66,613,559 rows
   ✓ trained 66,796,044 rows

▶ [69/231] Training customer_item_keys_chunk_16.parquet
   Rows: 982,052
   ✓ trained 67,196,044 rows
   ✓ trained 67,596,044 rows
   ✓ trained 67,778,096 rows

▶ [70/231] Training customer_item_keys_chunk_160.parquet
   Rows: 981,975
   ✓ trained 68,178,096 rows
   ✓ trained 68,578,096 rows
   ✓ trained 68,760,071 rows

▶ [71/231] Training customer_item_keys_chunk_161.parquet
   Rows: 982,203
   ✓ trained 69,160,071 rows
   ✓ trained 69,560,071 rows
   ✓ trained 69,742,274 rows

▶ [72/231] Training customer_item_keys_chunk_162.parquet
   Rows: 982,355
   ✓ trained 70,142,274 rows
   ✓ trained 70,542,274 rows
   ✓ trained 70,724,629 rows

▶ [73/231] Training customer_item_keys_chunk_163.parquet
   Rows: 981,902
   ✓ trained 71,124,629 rows
   ✓ trained 71,524,629 rows
   ✓ trained 71,706,531 rows

▶ [74/231] Training customer_item_keys_chunk_164.parquet
   Rows: 981,989
   ✓ trained 72,106,531 rows
   ✓ trained 72,506,531 rows
   ✓ trained 72,688,520 rows

▶ [75/231] Training customer_item_keys_chunk_165.parquet
   Rows: 983,062
   ✓ trained 73,088,520 rows
   ✓ trained 73,488,520 rows
   ✓ trained 73,671,582 rows

▶ [76/231] Training customer_item_keys_chunk_166.parquet
   Rows: 981,563
   ✓ trained 74,071,582 rows
   ✓ trained 74,471,582 rows
   ✓ trained 74,653,145 rows

▶ [77/231] Training customer_item_keys_chunk_167.parquet
   Rows: 981,892
   ✓ trained 75,053,145 rows
   ✓ trained 75,453,145 rows
   ✓ trained 75,635,037 rows

▶ [78/231] Training customer_item_keys_chunk_168.parquet
   Rows: 982,308
   ✓ trained 76,035,037 rows
   ✓ trained 76,435,037 rows
   ✓ trained 76,617,345 rows

▶ [79/231] Training customer_item_keys_chunk_169.parquet
   Rows: 982,243
   ✓ trained 77,017,345 rows
   ✓ trained 77,417,345 rows
   ✓ trained 77,599,588 rows

▶ [80/231] Training customer_item_keys_chunk_17.parquet
   Rows: 981,993
   ✓ trained 77,999,588 rows
   ✓ trained 78,399,588 rows
   ✓ trained 78,581,581 rows

▶ [81/231] Training customer_item_keys_chunk_170.parquet
   Rows: 982,153
   ✓ trained 78,981,581 rows
   ✓ trained 79,381,581 rows
   ✓ trained 79,563,734 rows

▶ [82/231] Training customer_item_keys_chunk_171.parquet
   Rows: 982,168
   ✓ trained 79,963,734 rows
   ✓ trained 80,363,734 rows
   ✓ trained 80,545,902 rows

▶ [83/231] Training customer_item_keys_chunk_172.parquet
   Rows: 982,165
   ✓ trained 80,945,902 rows
   ✓ trained 81,345,902 rows
   ✓ trained 81,528,067 rows

▶ [84/231] Training customer_item_keys_chunk_173.parquet
   Rows: 981,840
   ✓ trained 81,928,067 rows
   ✓ trained 82,328,067 rows
   ✓ trained 82,509,907 rows

▶ [85/231] Training customer_item_keys_chunk_174.parquet
   Rows: 982,054
   ✓ trained 82,909,907 rows
   ✓ trained 83,309,907 rows
   ✓ trained 83,491,961 rows

▶ [86/231] Training customer_item_keys_chunk_175.parquet
   Rows: 982,655
   ✓ trained 83,891,961 rows
   ✓ trained 84,291,961 rows
   ✓ trained 84,474,616 rows

▶ [87/231] Training customer_item_keys_chunk_176.parquet
   Rows: 982,346
   ✓ trained 84,874,616 rows
   ✓ trained 85,274,616 rows
   ✓ trained 85,456,962 rows

▶ [88/231] Training customer_item_keys_chunk_177.parquet
   Rows: 981,863
   ✓ trained 85,856,962 rows
   ✓ trained 86,256,962 rows
   ✓ trained 86,438,825 rows

▶ [89/231] Training customer_item_keys_chunk_178.parquet
   Rows: 982,714
   ✓ trained 86,838,825 rows
   ✓ trained 87,238,825 rows
   ✓ trained 87,421,539 rows

▶ [90/231] Training customer_item_keys_chunk_179.parquet
   Rows: 982,217
   ✓ trained 87,821,539 rows
   ✓ trained 88,221,539 rows
   ✓ trained 88,403,756 rows

▶ [91/231] Training customer_item_keys_chunk_18.parquet
   Rows: 982,228
   ✓ trained 88,803,756 rows
   ✓ trained 89,203,756 rows
   ✓ trained 89,385,984 rows

▶ [92/231] Training customer_item_keys_chunk_180.parquet
   Rows: 982,014
   ✓ trained 89,785,984 rows
   ✓ trained 90,185,984 rows
   ✓ trained 90,367,998 rows

▶ [93/231] Training customer_item_keys_chunk_181.parquet
   Rows: 982,224
   ✓ trained 90,767,998 rows
   ✓ trained 91,167,998 rows
   ✓ trained 91,350,222 rows

▶ [94/231] Training customer_item_keys_chunk_182.parquet
   Rows: 982,179
   ✓ trained 91,750,222 rows
   ✓ trained 92,150,222 rows
   ✓ trained 92,332,401 rows

▶ [95/231] Training customer_item_keys_chunk_183.parquet
   Rows: 982,710
   ✓ trained 92,732,401 rows
   ✓ trained 93,132,401 rows
   ✓ trained 93,315,111 rows

▶ [96/231] Training customer_item_keys_chunk_184.parquet
   Rows: 982,117
   ✓ trained 93,715,111 rows
   ✓ trained 94,115,111 rows
   ✓ trained 94,297,228 rows

▶ [97/231] Training customer_item_keys_chunk_185.parquet
   Rows: 982,028
   ✓ trained 94,697,228 rows
   ✓ trained 95,097,228 rows
   ✓ trained 95,279,256 rows

▶ [98/231] Training customer_item_keys_chunk_186.parquet
   Rows: 982,506
   ✓ trained 95,679,256 rows
   ✓ trained 96,079,256 rows
   ✓ trained 96,261,762 rows

▶ [99/231] Training customer_item_keys_chunk_187.parquet
   Rows: 982,883
   ✓ trained 96,661,762 rows
   ✓ trained 97,061,762 rows
   ✓ trained 97,244,645 rows

▶ [100/231] Training customer_item_keys_chunk_188.parquet
   Rows: 982,368
   ✓ trained 97,644,645 rows
   ✓ trained 98,044,645 rows
   ✓ trained 98,227,013 rows

▶ [101/231] Training customer_item_keys_chunk_189.parquet
   Rows: 981,739
   ✓ trained 98,627,013 rows
   ✓ trained 99,027,013 rows
   ✓ trained 99,208,752 rows

▶ [102/231] Training customer_item_keys_chunk_19.parquet
   Rows: 982,609
   ✓ trained 99,608,752 rows
   ✓ trained 100,008,752 rows
   ✓ trained 100,191,361 rows

▶ [103/231] Training customer_item_keys_chunk_190.parquet
   Rows: 982,679
   ✓ trained 100,591,361 rows
   ✓ trained 100,991,361 rows
   ✓ trained 101,174,040 rows

▶ [104/231] Training customer_item_keys_chunk_191.parquet
   Rows: 982,029
   ✓ trained 101,574,040 rows
   ✓ trained 101,974,040 rows
   ✓ trained 102,156,069 rows

▶ [105/231] Training customer_item_keys_chunk_192.parquet
   Rows: 982,831
   ✓ trained 102,556,069 rows
   ✓ trained 102,956,069 rows
   ✓ trained 103,138,900 rows

▶ [106/231] Training customer_item_keys_chunk_193.parquet
   Rows: 981,613
   ✓ trained 103,538,900 rows
   ✓ trained 103,938,900 rows
   ✓ trained 104,120,513 rows

▶ [107/231] Training customer_item_keys_chunk_194.parquet
   Rows: 982,051
   ✓ trained 104,520,513 rows
   ✓ trained 104,920,513 rows
   ✓ trained 105,102,564 rows

▶ [108/231] Training customer_item_keys_chunk_195.parquet
   Rows: 982,350
   ✓ trained 105,502,564 rows
   ✓ trained 105,902,564 rows
   ✓ trained 106,084,914 rows

▶ [109/231] Training customer_item_keys_chunk_196.parquet
   Rows: 982,419
   ✓ trained 106,484,914 rows
   ✓ trained 106,884,914 rows
   ✓ trained 107,067,333 rows

▶ [110/231] Training customer_item_keys_chunk_197.parquet
   Rows: 982,465
   ✓ trained 107,467,333 rows
   ✓ trained 107,867,333 rows
   ✓ trained 108,049,798 rows

▶ [111/231] Training customer_item_keys_chunk_198.parquet
   Rows: 981,955
   ✓ trained 108,449,798 rows
   ✓ trained 108,849,798 rows
   ✓ trained 109,031,753 rows

▶ [112/231] Training customer_item_keys_chunk_199.parquet
   Rows: 982,577
   ✓ trained 109,431,753 rows
   ✓ trained 109,831,753 rows
   ✓ trained 110,014,330 rows

▶ [113/231] Training customer_item_keys_chunk_2.parquet
   Rows: 982,246
   ✓ trained 110,414,330 rows
   ✓ trained 110,814,330 rows
   ✓ trained 110,996,576 rows

▶ [114/231] Training customer_item_keys_chunk_20.parquet
   Rows: 982,257
   ✓ trained 111,396,576 rows
   ✓ trained 111,796,576 rows
   ✓ trained 111,978,833 rows

▶ [115/231] Training customer_item_keys_chunk_200.parquet
   Rows: 981,975
   ✓ trained 112,378,833 rows
   ✓ trained 112,778,833 rows
   ✓ trained 112,960,808 rows

▶ [116/231] Training customer_item_keys_chunk_201.parquet
   Rows: 982,407
   ✓ trained 113,360,808 rows
   ✓ trained 113,760,808 rows
   ✓ trained 113,943,215 rows

▶ [117/231] Training customer_item_keys_chunk_202.parquet
   Rows: 981,849
   ✓ trained 114,343,215 rows
   ✓ trained 114,743,215 rows
   ✓ trained 114,925,064 rows

▶ [118/231] Training customer_item_keys_chunk_203.parquet
   Rows: 176,834
   ✓ trained 115,101,898 rows

▶ [119/231] Training customer_item_keys_chunk_205.parquet
   Rows: 1,000,000
   ✓ trained 115,501,898 rows
   ✓ trained 115,901,898 rows
   ✓ trained 116,101,898 rows

▶ [120/231] Training customer_item_keys_chunk_206.parquet
   Rows: 1,000,000
   ✓ trained 116,501,898 rows
   ✓ trained 116,901,898 rows
   ✓ trained 117,101,898 rows

▶ [121/231] Training customer_item_keys_chunk_207.parquet
   Rows: 1,000,000
   ✓ trained 117,501,898 rows
   ✓ trained 117,901,898 rows
   ✓ trained 118,101,898 rows

▶ [122/231] Training customer_item_keys_chunk_208.parquet
   Rows: 1,000,000
   ✓ trained 118,501,898 rows
   ✓ trained 118,901,898 rows
   ✓ trained 119,101,898 rows

▶ [123/231] Training customer_item_keys_chunk_209.parquet
   Rows: 1,000,000
   ✓ trained 119,501,898 rows
   ✓ trained 119,901,898 rows
   ✓ trained 120,101,898 rows

▶ [124/231] Training customer_item_keys_chunk_21.parquet
   Rows: 982,715
   ✓ trained 120,501,898 rows
   ✓ trained 120,901,898 rows
   ✓ trained 121,084,613 rows


In [2]:
import polars as pl
from pathlib import Path

# ========= CONFIG =========
VAL_FILE = "features_val.parquet"

OUTPUT_DIR = Path("features_split_test")
OUTPUT_DIR.mkdir(exist_ok=True)

# ========= LOAD =========
features = pl.read_parquet(VAL_FILE)

# ========= DROP Y IF EXISTS =========
if "Y" in features.columns:
    features = features.drop("Y")

print("Loaded VAL (Y removed if existed)")

# ========= 1. customer-item =========
feat_cus_item = (
    features
    .select([
        "customer_id",
        "item_id",
        "X_1", "X_2", "X_3"
    ])
    .unique(
        subset=["customer_id", "item_id"],
        keep="first"
    )
)

feat_cus_item.write_parquet(OUTPUT_DIR / "feat_cus_item.parquet")
print("Saved feat_cus_item.parquet")

# ========= 2. item =========
feat_item = (
    features
    .select([
        "item_id",
        "X_4", "X_5"
    ])
    .unique(
        subset=["item_id"],
        keep="first"
    )
)

feat_item.write_parquet(OUTPUT_DIR / "feat_item.parquet")
print("Saved feat_item.parquet")

# ========= 3. customer =========
feat_cus = (
    features
    .select([
        "customer_id",
        "X_6", "X_7", "X_8",
        "X_9", "X_10", "X_11",
        "X_12", "X_13", "X_14",
        "X_15", "X_16"
    ])
    .unique(
        subset=["customer_id"],
        keep="first"
    )
)

feat_cus.write_parquet(OUTPUT_DIR / "feat_cus.parquet")
print("Saved feat_cus.parquet")

print("🎉 DONE: features_split created from VAL only")

Loaded VAL (Y removed if existed)
Saved feat_cus_item.parquet
Saved feat_item.parquet
Saved feat_cus.parquet
🎉 DONE: features_split created from VAL only

In [3]:
pl.scan_parquet("features_split_test/feat_cus_item.parquet") \
  .unique(["customer_id", "item_id"]) \
  .collect(engine="streaming") \
  .write_parquet("features_split_test/feat_cus_item_u.parquet")

pl.scan_parquet("features_split_test/feat_item.parquet") \
  .unique("item_id") \
  .collect(engine="streaming") \
  .write_parquet("features_split_test/feat_item_u.parquet")

pl.scan_parquet("features_split_test/feat_cus.parquet") \
  .unique("customer_id") \
  .collect(engine="streaming") \
  .write_parquet("features_split_test/feat_cus_u.parquet")

print("finish")

finish

In [7]:
import polars as pl
from pathlib import Path

FEATURE_COLS = [f"X_{i}" for i in range(1, 17)]

def join_features_chunks_pipeline_merge_all_add_Y(
    test_folder: str,
    feat_cus_item_parquet: str,
    feat_item_parquet: str,
    feat_cus_parquet: str,
    output_folder: str
):
    test_folder = Path(test_folder)
    out_dir = Path(output_folder)
    out_dir.mkdir(exist_ok=True)

    # Load features (lazy)
    feat_cus_item = pl.scan_parquet(feat_cus_item_parquet)
    feat_item     = pl.scan_parquet(feat_item_parquet)
    feat_cus      = pl.scan_parquet(feat_cus_parquet)

    test_files = sorted(test_folder.glob("*.parquet"))
    print(f"🔹 Found {len(test_files)} test chunks")

    for idx, test_path in enumerate(test_files, 1):
        print(f"\n▶ [{idx}/{len(test_files)}] {test_path.name}")

        test = pl.scan_parquet(test_path)

        joined = (
            test
            .join(feat_item, on="item_id", how="left")
            .join(feat_cus, on="customer_id", how="left")
            .join(feat_cus_item, on=["customer_id", "item_id"], how="left")
            .fill_null(0)
            # 👉 thêm cột Y = 0.2
        )

        # sắp xếp lại cột
        final_cols = (
            ["customer_id", "item_id"]
            + FEATURE_COLS
        )

        joined = joined.select(final_cols)

        joined.collect(streaming=True).write_parquet(out_dir / test_path.name)
        print("  ✅ saved MERGED + X_1..X_16 + Y=0.2")

    print("\n🎉 DONE: added Y = 0.2 for all rows")

In [9]:
join_features_chunks_pipeline_merge_all_add_Y(
    test_folder="cus_item_key_filter",          # folder chứa các chunk test
    feat_cus_item_parquet="features_split_test/feat_cus_item_u.parquet",
    feat_item_parquet="features_split_test/feat_item_u.parquet",
    feat_cus_parquet="features_split_test/feat_cus_u.parquet",
    output_folder="cus_item_key_features_test"      )

🔹 Found 204 test chunks

▶ [1/204] customer_item_keys_chunk_0.parquet

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_4260\2668680823.py:47: DeprecationWarning: the `streaming` parameter was deprecated in 1.25.0; use `engine` instead.
  joined.collect(streaming=True).write_parquet(out_dir / test_path.name)

  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [2/204] customer_item_keys_chunk_1.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [3/204] customer_item_keys_chunk_10.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [4/204] customer_item_keys_chunk_100.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [5/204] customer_item_keys_chunk_101.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [6/204] customer_item_keys_chunk_102.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [7/204] customer_item_keys_chunk_103.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [8/204] customer_item_keys_chunk_104.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [9/204] customer_item_keys_chunk_105.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [10/204] customer_item_keys_chunk_106.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [11/204] customer_item_keys_chunk_107.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [12/204] customer_item_keys_chunk_108.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [13/204] customer_item_keys_chunk_109.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [14/204] customer_item_keys_chunk_11.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [15/204] customer_item_keys_chunk_110.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [16/204] customer_item_keys_chunk_111.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [17/204] customer_item_keys_chunk_112.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [18/204] customer_item_keys_chunk_113.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [19/204] customer_item_keys_chunk_114.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [20/204] customer_item_keys_chunk_115.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [21/204] customer_item_keys_chunk_116.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [22/204] customer_item_keys_chunk_117.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [23/204] customer_item_keys_chunk_118.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [24/204] customer_item_keys_chunk_119.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [25/204] customer_item_keys_chunk_12.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [26/204] customer_item_keys_chunk_120.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [27/204] customer_item_keys_chunk_121.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [28/204] customer_item_keys_chunk_122.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [29/204] customer_item_keys_chunk_123.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [30/204] customer_item_keys_chunk_124.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [31/204] customer_item_keys_chunk_125.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [32/204] customer_item_keys_chunk_126.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [33/204] customer_item_keys_chunk_127.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [34/204] customer_item_keys_chunk_128.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [35/204] customer_item_keys_chunk_129.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [36/204] customer_item_keys_chunk_13.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [37/204] customer_item_keys_chunk_130.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [38/204] customer_item_keys_chunk_131.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [39/204] customer_item_keys_chunk_132.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [40/204] customer_item_keys_chunk_133.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [41/204] customer_item_keys_chunk_134.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [42/204] customer_item_keys_chunk_135.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [43/204] customer_item_keys_chunk_136.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [44/204] customer_item_keys_chunk_137.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [45/204] customer_item_keys_chunk_138.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [46/204] customer_item_keys_chunk_139.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [47/204] customer_item_keys_chunk_14.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [48/204] customer_item_keys_chunk_140.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [49/204] customer_item_keys_chunk_141.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [50/204] customer_item_keys_chunk_142.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [51/204] customer_item_keys_chunk_143.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [52/204] customer_item_keys_chunk_144.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [53/204] customer_item_keys_chunk_145.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [54/204] customer_item_keys_chunk_146.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [55/204] customer_item_keys_chunk_147.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [56/204] customer_item_keys_chunk_148.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [57/204] customer_item_keys_chunk_149.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [58/204] customer_item_keys_chunk_15.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [59/204] customer_item_keys_chunk_150.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [60/204] customer_item_keys_chunk_151.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [61/204] customer_item_keys_chunk_152.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [62/204] customer_item_keys_chunk_153.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [63/204] customer_item_keys_chunk_154.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [64/204] customer_item_keys_chunk_155.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [65/204] customer_item_keys_chunk_156.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [66/204] customer_item_keys_chunk_157.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [67/204] customer_item_keys_chunk_158.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [68/204] customer_item_keys_chunk_159.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [69/204] customer_item_keys_chunk_16.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [70/204] customer_item_keys_chunk_160.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [71/204] customer_item_keys_chunk_161.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [72/204] customer_item_keys_chunk_162.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [73/204] customer_item_keys_chunk_163.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [74/204] customer_item_keys_chunk_164.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [75/204] customer_item_keys_chunk_165.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [76/204] customer_item_keys_chunk_166.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [77/204] customer_item_keys_chunk_167.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [78/204] customer_item_keys_chunk_168.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [79/204] customer_item_keys_chunk_169.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [80/204] customer_item_keys_chunk_17.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [81/204] customer_item_keys_chunk_170.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [82/204] customer_item_keys_chunk_171.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [83/204] customer_item_keys_chunk_172.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [84/204] customer_item_keys_chunk_173.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [85/204] customer_item_keys_chunk_174.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [86/204] customer_item_keys_chunk_175.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [87/204] customer_item_keys_chunk_176.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [88/204] customer_item_keys_chunk_177.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [89/204] customer_item_keys_chunk_178.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [90/204] customer_item_keys_chunk_179.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [91/204] customer_item_keys_chunk_18.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [92/204] customer_item_keys_chunk_180.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [93/204] customer_item_keys_chunk_181.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [94/204] customer_item_keys_chunk_182.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [95/204] customer_item_keys_chunk_183.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [96/204] customer_item_keys_chunk_184.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [97/204] customer_item_keys_chunk_185.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [98/204] customer_item_keys_chunk_186.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [99/204] customer_item_keys_chunk_187.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [100/204] customer_item_keys_chunk_188.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [101/204] customer_item_keys_chunk_189.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [102/204] customer_item_keys_chunk_19.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [103/204] customer_item_keys_chunk_190.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [104/204] customer_item_keys_chunk_191.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [105/204] customer_item_keys_chunk_192.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [106/204] customer_item_keys_chunk_193.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [107/204] customer_item_keys_chunk_194.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [108/204] customer_item_keys_chunk_195.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [109/204] customer_item_keys_chunk_196.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [110/204] customer_item_keys_chunk_197.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [111/204] customer_item_keys_chunk_198.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [112/204] customer_item_keys_chunk_199.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [113/204] customer_item_keys_chunk_2.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [114/204] customer_item_keys_chunk_20.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [115/204] customer_item_keys_chunk_200.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [116/204] customer_item_keys_chunk_201.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [117/204] customer_item_keys_chunk_202.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [118/204] customer_item_keys_chunk_203.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [119/204] customer_item_keys_chunk_21.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [120/204] customer_item_keys_chunk_22.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [121/204] customer_item_keys_chunk_23.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [122/204] customer_item_keys_chunk_24.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [123/204] customer_item_keys_chunk_25.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [124/204] customer_item_keys_chunk_26.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [125/204] customer_item_keys_chunk_27.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [126/204] customer_item_keys_chunk_28.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [127/204] customer_item_keys_chunk_29.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [128/204] customer_item_keys_chunk_3.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [129/204] customer_item_keys_chunk_30.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [130/204] customer_item_keys_chunk_31.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [131/204] customer_item_keys_chunk_32.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [132/204] customer_item_keys_chunk_33.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [133/204] customer_item_keys_chunk_34.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [134/204] customer_item_keys_chunk_35.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [135/204] customer_item_keys_chunk_36.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [136/204] customer_item_keys_chunk_37.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [137/204] customer_item_keys_chunk_38.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [138/204] customer_item_keys_chunk_39.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [139/204] customer_item_keys_chunk_4.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [140/204] customer_item_keys_chunk_40.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [141/204] customer_item_keys_chunk_41.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [142/204] customer_item_keys_chunk_42.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [143/204] customer_item_keys_chunk_43.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [144/204] customer_item_keys_chunk_44.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [145/204] customer_item_keys_chunk_45.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [146/204] customer_item_keys_chunk_46.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [147/204] customer_item_keys_chunk_47.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [148/204] customer_item_keys_chunk_48.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [149/204] customer_item_keys_chunk_49.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [150/204] customer_item_keys_chunk_5.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [151/204] customer_item_keys_chunk_50.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [152/204] customer_item_keys_chunk_51.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [153/204] customer_item_keys_chunk_52.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [154/204] customer_item_keys_chunk_53.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [155/204] customer_item_keys_chunk_54.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [156/204] customer_item_keys_chunk_55.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [157/204] customer_item_keys_chunk_56.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [158/204] customer_item_keys_chunk_57.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [159/204] customer_item_keys_chunk_58.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [160/204] customer_item_keys_chunk_59.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [161/204] customer_item_keys_chunk_6.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [162/204] customer_item_keys_chunk_60.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [163/204] customer_item_keys_chunk_61.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [164/204] customer_item_keys_chunk_62.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [165/204] customer_item_keys_chunk_63.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [166/204] customer_item_keys_chunk_64.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [167/204] customer_item_keys_chunk_65.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [168/204] customer_item_keys_chunk_66.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [169/204] customer_item_keys_chunk_67.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [170/204] customer_item_keys_chunk_68.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [171/204] customer_item_keys_chunk_69.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [172/204] customer_item_keys_chunk_7.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [173/204] customer_item_keys_chunk_70.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [174/204] customer_item_keys_chunk_71.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [175/204] customer_item_keys_chunk_72.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [176/204] customer_item_keys_chunk_73.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [177/204] customer_item_keys_chunk_74.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [178/204] customer_item_keys_chunk_75.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [179/204] customer_item_keys_chunk_76.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [180/204] customer_item_keys_chunk_77.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [181/204] customer_item_keys_chunk_78.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [182/204] customer_item_keys_chunk_79.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [183/204] customer_item_keys_chunk_8.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [184/204] customer_item_keys_chunk_80.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [185/204] customer_item_keys_chunk_81.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [186/204] customer_item_keys_chunk_82.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [187/204] customer_item_keys_chunk_83.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [188/204] customer_item_keys_chunk_84.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [189/204] customer_item_keys_chunk_85.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [190/204] customer_item_keys_chunk_86.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [191/204] customer_item_keys_chunk_87.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [192/204] customer_item_keys_chunk_88.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [193/204] customer_item_keys_chunk_89.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [194/204] customer_item_keys_chunk_9.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [195/204] customer_item_keys_chunk_90.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [196/204] customer_item_keys_chunk_91.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [197/204] customer_item_keys_chunk_92.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [198/204] customer_item_keys_chunk_93.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [199/204] customer_item_keys_chunk_94.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [200/204] customer_item_keys_chunk_95.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [201/204] customer_item_keys_chunk_96.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [202/204] customer_item_keys_chunk_97.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [203/204] customer_item_keys_chunk_98.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

▶ [204/204] customer_item_keys_chunk_99.parquet
  ✅ saved MERGED + X_1..X_16 + Y=0.2

🎉 DONE: added Y = 0.2 for all rows

In [1]:
import polars as pl
from pathlib import Path
import numpy as np
import xgboost as xgb
import gc
import re

# ======================
# 🔧 CONFIG
# ======================
DATA_FOLDER = "cus_item_key_features_test"
MODEL_PATH = "xgb_model_stream.json"      # 👈 model XGB
OUTPUT_FOLDER = "prediction_3cols_all_files"

BATCH_SIZE = 500_000

FEATURE_COLS = [f"X_{i}" for i in range(1, 17)]
START_CHUNK = 0
END_CHUNK = 231   # inclusive

DEVICE = "cuda"   # "cuda" hoặc "cpu"

Path(OUTPUT_FOLDER).mkdir(exist_ok=True)

# ======================
# 🚀 LOAD MODEL
# ======================
model = xgb.Booster()
model.load_model(MODEL_PATH)
model.set_param({"device": DEVICE})

print("✅ XGBoost model loaded")

# ======================
# 📁 LOAD & FILTER PARQUET FILES
# ======================
all_files = sorted(Path(DATA_FOLDER).glob("customer_item_keys_chunk_*.parquet"))

def extract_chunk_id(path: Path) -> int:
    m = re.search(r"chunk_(\d+)", path.name)
    return int(m.group(1)) if m else -1

files = [
    f for f in all_files
    if START_CHUNK <= extract_chunk_id(f) <= END_CHUNK
]

print(f"\n📂 Found {len(files)} parquet files (chunk {START_CHUNK} → {END_CHUNK})")

if not files:
    raise RuntimeError("❌ No parquet files in selected chunk range!")

# ======================
# 🔮 PREDICT LOOP
# ======================
for idx, file in enumerate(files, 1):
    chunk_id = extract_chunk_id(file)
    print(f"\n[{idx}/{len(files)}] 🔮 Predicting {file.name} (chunk {chunk_id})")

    df = pl.read_parquet(file)

    if "Y" in df.columns:
        df = df.drop("Y")

    n_rows = df.height
    out_path = Path(OUTPUT_FOLDER) / file.name

    first_batch = True

    for start in range(0, n_rows, BATCH_SIZE):
        end = min(start + BATCH_SIZE, n_rows)
        batch = df.slice(start, end - start)

        X = (
            batch
            .select(FEATURE_COLS)
            .with_columns(pl.all().cast(pl.Float32))
            .to_numpy(order="c")
        )

        dtest = xgb.DMatrix(X)
        y_pred = model.predict(dtest)

        df_out = pl.DataFrame({
            "customer_id": batch["customer_id"],
            "item_id": batch["item_id"],
            "y_pred": y_pred
        })

        if first_batch:
            df_out.write_parquet(out_path)
            first_batch = False
        else:
            pl.concat(
                [pl.read_parquet(out_path), df_out],
                how="vertical"
            ).write_parquet(out_path)

        del X, dtest, y_pred, df_out, batch
        gc.collect()

    del df
    gc.collect()

print("\n🎉 DONE: Predicted chunks using XGBoost")

✅ XGBoost model loaded

📂 Found 204 parquet files (chunk 0 → 231)

[1/204] 🔮 Predicting customer_item_keys_chunk_0.parquet (chunk 0)

[2/204] 🔮 Predicting customer_item_keys_chunk_1.parquet (chunk 1)

[3/204] 🔮 Predicting customer_item_keys_chunk_10.parquet (chunk 10)

[4/204] 🔮 Predicting customer_item_keys_chunk_100.parquet (chunk 100)

[5/204] 🔮 Predicting customer_item_keys_chunk_101.parquet (chunk 101)

[6/204] 🔮 Predicting customer_item_keys_chunk_102.parquet (chunk 102)

[7/204] 🔮 Predicting customer_item_keys_chunk_103.parquet (chunk 103)

[8/204] 🔮 Predicting customer_item_keys_chunk_104.parquet (chunk 104)

[9/204] 🔮 Predicting customer_item_keys_chunk_105.parquet (chunk 105)

[10/204] 🔮 Predicting customer_item_keys_chunk_106.parquet (chunk 106)

[11/204] 🔮 Predicting customer_item_keys_chunk_107.parquet (chunk 107)

[12/204] 🔮 Predicting customer_item_keys_chunk_108.parquet (chunk 108)

[13/204] 🔮 Predicting customer_item_keys_chunk_109.parquet (chunk 109)

[14/204] 🔮 Predicting customer_item_keys_chunk_11.parquet (chunk 11)

[15/204] 🔮 Predicting customer_item_keys_chunk_110.parquet (chunk 110)

[16/204] 🔮 Predicting customer_item_keys_chunk_111.parquet (chunk 111)

[17/204] 🔮 Predicting customer_item_keys_chunk_112.parquet (chunk 112)

[18/204] 🔮 Predicting customer_item_keys_chunk_113.parquet (chunk 113)

[19/204] 🔮 Predicting customer_item_keys_chunk_114.parquet (chunk 114)

[20/204] 🔮 Predicting customer_item_keys_chunk_115.parquet (chunk 115)

[21/204] 🔮 Predicting customer_item_keys_chunk_116.parquet (chunk 116)

[22/204] 🔮 Predicting customer_item_keys_chunk_117.parquet (chunk 117)

[23/204] 🔮 Predicting customer_item_keys_chunk_118.parquet (chunk 118)

[24/204] 🔮 Predicting customer_item_keys_chunk_119.parquet (chunk 119)

[25/204] 🔮 Predicting customer_item_keys_chunk_12.parquet (chunk 12)

[26/204] 🔮 Predicting customer_item_keys_chunk_120.parquet (chunk 120)

[27/204] 🔮 Predicting customer_item_keys_chunk_121.parquet (chunk 121)

[28/204] 🔮 Predicting customer_item_keys_chunk_122.parquet (chunk 122)

[29/204] 🔮 Predicting customer_item_keys_chunk_123.parquet (chunk 123)

[30/204] 🔮 Predicting customer_item_keys_chunk_124.parquet (chunk 124)

[31/204] 🔮 Predicting customer_item_keys_chunk_125.parquet (chunk 125)

[32/204] 🔮 Predicting customer_item_keys_chunk_126.parquet (chunk 126)

[33/204] 🔮 Predicting customer_item_keys_chunk_127.parquet (chunk 127)

[34/204] 🔮 Predicting customer_item_keys_chunk_128.parquet (chunk 128)

[35/204] 🔮 Predicting customer_item_keys_chunk_129.parquet (chunk 129)

[36/204] 🔮 Predicting customer_item_keys_chunk_13.parquet (chunk 13)

[37/204] 🔮 Predicting customer_item_keys_chunk_130.parquet (chunk 130)

[38/204] 🔮 Predicting customer_item_keys_chunk_131.parquet (chunk 131)

[39/204] 🔮 Predicting customer_item_keys_chunk_132.parquet (chunk 132)

[40/204] 🔮 Predicting customer_item_keys_chunk_133.parquet (chunk 133)

[41/204] 🔮 Predicting customer_item_keys_chunk_134.parquet (chunk 134)

[42/204] 🔮 Predicting customer_item_keys_chunk_135.parquet (chunk 135)

[43/204] 🔮 Predicting customer_item_keys_chunk_136.parquet (chunk 136)

[44/204] 🔮 Predicting customer_item_keys_chunk_137.parquet (chunk 137)

[45/204] 🔮 Predicting customer_item_keys_chunk_138.parquet (chunk 138)

[46/204] 🔮 Predicting customer_item_keys_chunk_139.parquet (chunk 139)

[47/204] 🔮 Predicting customer_item_keys_chunk_14.parquet (chunk 14)

[48/204] 🔮 Predicting customer_item_keys_chunk_140.parquet (chunk 140)

[49/204] 🔮 Predicting customer_item_keys_chunk_141.parquet (chunk 141)

[50/204] 🔮 Predicting customer_item_keys_chunk_142.parquet (chunk 142)

[51/204] 🔮 Predicting customer_item_keys_chunk_143.parquet (chunk 143)

[52/204] 🔮 Predicting customer_item_keys_chunk_144.parquet (chunk 144)

[53/204] 🔮 Predicting customer_item_keys_chunk_145.parquet (chunk 145)

[54/204] 🔮 Predicting customer_item_keys_chunk_146.parquet (chunk 146)

[55/204] 🔮 Predicting customer_item_keys_chunk_147.parquet (chunk 147)

[56/204] 🔮 Predicting customer_item_keys_chunk_148.parquet (chunk 148)

[57/204] 🔮 Predicting customer_item_keys_chunk_149.parquet (chunk 149)

[58/204] 🔮 Predicting customer_item_keys_chunk_15.parquet (chunk 15)

[59/204] 🔮 Predicting customer_item_keys_chunk_150.parquet (chunk 150)

[60/204] 🔮 Predicting customer_item_keys_chunk_151.parquet (chunk 151)

[61/204] 🔮 Predicting customer_item_keys_chunk_152.parquet (chunk 152)

[62/204] 🔮 Predicting customer_item_keys_chunk_153.parquet (chunk 153)

[63/204] 🔮 Predicting customer_item_keys_chunk_154.parquet (chunk 154)

[64/204] 🔮 Predicting customer_item_keys_chunk_155.parquet (chunk 155)

[65/204] 🔮 Predicting customer_item_keys_chunk_156.parquet (chunk 156)

[66/204] 🔮 Predicting customer_item_keys_chunk_157.parquet (chunk 157)

[67/204] 🔮 Predicting customer_item_keys_chunk_158.parquet (chunk 158)

[68/204] 🔮 Predicting customer_item_keys_chunk_159.parquet (chunk 159)

[69/204] 🔮 Predicting customer_item_keys_chunk_16.parquet (chunk 16)

[70/204] 🔮 Predicting customer_item_keys_chunk_160.parquet (chunk 160)

[71/204] 🔮 Predicting customer_item_keys_chunk_161.parquet (chunk 161)

[72/204] 🔮 Predicting customer_item_keys_chunk_162.parquet (chunk 162)

[73/204] 🔮 Predicting customer_item_keys_chunk_163.parquet (chunk 163)

[74/204] 🔮 Predicting customer_item_keys_chunk_164.parquet (chunk 164)

[75/204] 🔮 Predicting customer_item_keys_chunk_165.parquet (chunk 165)

[76/204] 🔮 Predicting customer_item_keys_chunk_166.parquet (chunk 166)

[77/204] 🔮 Predicting customer_item_keys_chunk_167.parquet (chunk 167)

[78/204] 🔮 Predicting customer_item_keys_chunk_168.parquet (chunk 168)

[79/204] 🔮 Predicting customer_item_keys_chunk_169.parquet (chunk 169)

[80/204] 🔮 Predicting customer_item_keys_chunk_17.parquet (chunk 17)

[81/204] 🔮 Predicting customer_item_keys_chunk_170.parquet (chunk 170)

[82/204] 🔮 Predicting customer_item_keys_chunk_171.parquet (chunk 171)

[83/204] 🔮 Predicting customer_item_keys_chunk_172.parquet (chunk 172)

[84/204] 🔮 Predicting customer_item_keys_chunk_173.parquet (chunk 173)

[85/204] 🔮 Predicting customer_item_keys_chunk_174.parquet (chunk 174)

[86/204] 🔮 Predicting customer_item_keys_chunk_175.parquet (chunk 175)

[87/204] 🔮 Predicting customer_item_keys_chunk_176.parquet (chunk 176)

[88/204] 🔮 Predicting customer_item_keys_chunk_177.parquet (chunk 177)

[89/204] 🔮 Predicting customer_item_keys_chunk_178.parquet (chunk 178)

[90/204] 🔮 Predicting customer_item_keys_chunk_179.parquet (chunk 179)

[91/204] 🔮 Predicting customer_item_keys_chunk_18.parquet (chunk 18)

[92/204] 🔮 Predicting customer_item_keys_chunk_180.parquet (chunk 180)

[93/204] 🔮 Predicting customer_item_keys_chunk_181.parquet (chunk 181)

[94/204] 🔮 Predicting customer_item_keys_chunk_182.parquet (chunk 182)

[95/204] 🔮 Predicting customer_item_keys_chunk_183.parquet (chunk 183)

[96/204] 🔮 Predicting customer_item_keys_chunk_184.parquet (chunk 184)

[97/204] 🔮 Predicting customer_item_keys_chunk_185.parquet (chunk 185)

[98/204] 🔮 Predicting customer_item_keys_chunk_186.parquet (chunk 186)

[99/204] 🔮 Predicting customer_item_keys_chunk_187.parquet (chunk 187)

[100/204] 🔮 Predicting customer_item_keys_chunk_188.parquet (chunk 188)

[101/204] 🔮 Predicting customer_item_keys_chunk_189.parquet (chunk 189)

[102/204] 🔮 Predicting customer_item_keys_chunk_19.parquet (chunk 19)

[103/204] 🔮 Predicting customer_item_keys_chunk_190.parquet (chunk 190)

[104/204] 🔮 Predicting customer_item_keys_chunk_191.parquet (chunk 191)

[105/204] 🔮 Predicting customer_item_keys_chunk_192.parquet (chunk 192)

[106/204] 🔮 Predicting customer_item_keys_chunk_193.parquet (chunk 193)

[107/204] 🔮 Predicting customer_item_keys_chunk_194.parquet (chunk 194)

[108/204] 🔮 Predicting customer_item_keys_chunk_195.parquet (chunk 195)

[109/204] 🔮 Predicting customer_item_keys_chunk_196.parquet (chunk 196)

[110/204] 🔮 Predicting customer_item_keys_chunk_197.parquet (chunk 197)

[111/204] 🔮 Predicting customer_item_keys_chunk_198.parquet (chunk 198)

[112/204] 🔮 Predicting customer_item_keys_chunk_199.parquet (chunk 199)

[113/204] 🔮 Predicting customer_item_keys_chunk_2.parquet (chunk 2)

[114/204] 🔮 Predicting customer_item_keys_chunk_20.parquet (chunk 20)

[115/204] 🔮 Predicting customer_item_keys_chunk_200.parquet (chunk 200)

[116/204] 🔮 Predicting customer_item_keys_chunk_201.parquet (chunk 201)

[117/204] 🔮 Predicting customer_item_keys_chunk_202.parquet (chunk 202)

[118/204] 🔮 Predicting customer_item_keys_chunk_203.parquet (chunk 203)

[119/204] 🔮 Predicting customer_item_keys_chunk_21.parquet (chunk 21)

[120/204] 🔮 Predicting customer_item_keys_chunk_22.parquet (chunk 22)

[121/204] 🔮 Predicting customer_item_keys_chunk_23.parquet (chunk 23)

[122/204] 🔮 Predicting customer_item_keys_chunk_24.parquet (chunk 24)

[123/204] 🔮 Predicting customer_item_keys_chunk_25.parquet (chunk 25)

[124/204] 🔮 Predicting customer_item_keys_chunk_26.parquet (chunk 26)

[125/204] 🔮 Predicting customer_item_keys_chunk_27.parquet (chunk 27)

[126/204] 🔮 Predicting customer_item_keys_chunk_28.parquet (chunk 28)

[127/204] 🔮 Predicting customer_item_keys_chunk_29.parquet (chunk 29)

[128/204] 🔮 Predicting customer_item_keys_chunk_3.parquet (chunk 3)

[129/204] 🔮 Predicting customer_item_keys_chunk_30.parquet (chunk 30)

[130/204] 🔮 Predicting customer_item_keys_chunk_31.parquet (chunk 31)

[131/204] 🔮 Predicting customer_item_keys_chunk_32.parquet (chunk 32)

[132/204] 🔮 Predicting customer_item_keys_chunk_33.parquet (chunk 33)

[133/204] 🔮 Predicting customer_item_keys_chunk_34.parquet (chunk 34)

[134/204] 🔮 Predicting customer_item_keys_chunk_35.parquet (chunk 35)

[135/204] 🔮 Predicting customer_item_keys_chunk_36.parquet (chunk 36)

[136/204] 🔮 Predicting customer_item_keys_chunk_37.parquet (chunk 37)

[137/204] 🔮 Predicting customer_item_keys_chunk_38.parquet (chunk 38)

[138/204] 🔮 Predicting customer_item_keys_chunk_39.parquet (chunk 39)

[139/204] 🔮 Predicting customer_item_keys_chunk_4.parquet (chunk 4)

[140/204] 🔮 Predicting customer_item_keys_chunk_40.parquet (chunk 40)

[141/204] 🔮 Predicting customer_item_keys_chunk_41.parquet (chunk 41)

[142/204] 🔮 Predicting customer_item_keys_chunk_42.parquet (chunk 42)

[143/204] 🔮 Predicting customer_item_keys_chunk_43.parquet (chunk 43)

[144/204] 🔮 Predicting customer_item_keys_chunk_44.parquet (chunk 44)

[145/204] 🔮 Predicting customer_item_keys_chunk_45.parquet (chunk 45)

[146/204] 🔮 Predicting customer_item_keys_chunk_46.parquet (chunk 46)

[147/204] 🔮 Predicting customer_item_keys_chunk_47.parquet (chunk 47)

[148/204] 🔮 Predicting customer_item_keys_chunk_48.parquet (chunk 48)

[149/204] 🔮 Predicting customer_item_keys_chunk_49.parquet (chunk 49)

[150/204] 🔮 Predicting customer_item_keys_chunk_5.parquet (chunk 5)

[151/204] 🔮 Predicting customer_item_keys_chunk_50.parquet (chunk 50)

[152/204] 🔮 Predicting customer_item_keys_chunk_51.parquet (chunk 51)

[153/204] 🔮 Predicting customer_item_keys_chunk_52.parquet (chunk 52)

[154/204] 🔮 Predicting customer_item_keys_chunk_53.parquet (chunk 53)

[155/204] 🔮 Predicting customer_item_keys_chunk_54.parquet (chunk 54)

[156/204] 🔮 Predicting customer_item_keys_chunk_55.parquet (chunk 55)

[157/204] 🔮 Predicting customer_item_keys_chunk_56.parquet (chunk 56)

[158/204] 🔮 Predicting customer_item_keys_chunk_57.parquet (chunk 57)

[159/204] 🔮 Predicting customer_item_keys_chunk_58.parquet (chunk 58)

[160/204] 🔮 Predicting customer_item_keys_chunk_59.parquet (chunk 59)

[161/204] 🔮 Predicting customer_item_keys_chunk_6.parquet (chunk 6)

[162/204] 🔮 Predicting customer_item_keys_chunk_60.parquet (chunk 60)

[163/204] 🔮 Predicting customer_item_keys_chunk_61.parquet (chunk 61)

[164/204] 🔮 Predicting customer_item_keys_chunk_62.parquet (chunk 62)

[165/204] 🔮 Predicting customer_item_keys_chunk_63.parquet (chunk 63)

[166/204] 🔮 Predicting customer_item_keys_chunk_64.parquet (chunk 64)

[167/204] 🔮 Predicting customer_item_keys_chunk_65.parquet (chunk 65)

[168/204] 🔮 Predicting customer_item_keys_chunk_66.parquet (chunk 66)

[169/204] 🔮 Predicting customer_item_keys_chunk_67.parquet (chunk 67)

[170/204] 🔮 Predicting customer_item_keys_chunk_68.parquet (chunk 68)

[171/204] 🔮 Predicting customer_item_keys_chunk_69.parquet (chunk 69)

[172/204] 🔮 Predicting customer_item_keys_chunk_7.parquet (chunk 7)

[173/204] 🔮 Predicting customer_item_keys_chunk_70.parquet (chunk 70)

[174/204] 🔮 Predicting customer_item_keys_chunk_71.parquet (chunk 71)

[175/204] 🔮 Predicting customer_item_keys_chunk_72.parquet (chunk 72)

[176/204] 🔮 Predicting customer_item_keys_chunk_73.parquet (chunk 73)

[177/204] 🔮 Predicting customer_item_keys_chunk_74.parquet (chunk 74)

[178/204] 🔮 Predicting customer_item_keys_chunk_75.parquet (chunk 75)

[179/204] 🔮 Predicting customer_item_keys_chunk_76.parquet (chunk 76)

[180/204] 🔮 Predicting customer_item_keys_chunk_77.parquet (chunk 77)

[181/204] 🔮 Predicting customer_item_keys_chunk_78.parquet (chunk 78)

[182/204] 🔮 Predicting customer_item_keys_chunk_79.parquet (chunk 79)

[183/204] 🔮 Predicting customer_item_keys_chunk_8.parquet (chunk 8)

[184/204] 🔮 Predicting customer_item_keys_chunk_80.parquet (chunk 80)

[185/204] 🔮 Predicting customer_item_keys_chunk_81.parquet (chunk 81)

[186/204] 🔮 Predicting customer_item_keys_chunk_82.parquet (chunk 82)

[187/204] 🔮 Predicting customer_item_keys_chunk_83.parquet (chunk 83)

[188/204] 🔮 Predicting customer_item_keys_chunk_84.parquet (chunk 84)

[189/204] 🔮 Predicting customer_item_keys_chunk_85.parquet (chunk 85)

[190/204] 🔮 Predicting customer_item_keys_chunk_86.parquet (chunk 86)

[191/204] 🔮 Predicting customer_item_keys_chunk_87.parquet (chunk 87)

[192/204] 🔮 Predicting customer_item_keys_chunk_88.parquet (chunk 88)

[193/204] 🔮 Predicting customer_item_keys_chunk_89.parquet (chunk 89)

[194/204] 🔮 Predicting customer_item_keys_chunk_9.parquet (chunk 9)

[195/204] 🔮 Predicting customer_item_keys_chunk_90.parquet (chunk 90)

[196/204] 🔮 Predicting customer_item_keys_chunk_91.parquet (chunk 91)

[197/204] 🔮 Predicting customer_item_keys_chunk_92.parquet (chunk 92)

[198/204] 🔮 Predicting customer_item_keys_chunk_93.parquet (chunk 93)

[199/204] 🔮 Predicting customer_item_keys_chunk_94.parquet (chunk 94)

[200/204] 🔮 Predicting customer_item_keys_chunk_95.parquet (chunk 95)

[201/204] 🔮 Predicting customer_item_keys_chunk_96.parquet (chunk 96)

[202/204] 🔮 Predicting customer_item_keys_chunk_97.parquet (chunk 97)

[203/204] 🔮 Predicting customer_item_keys_chunk_98.parquet (chunk 98)

[204/204] 🔮 Predicting customer_item_keys_chunk_99.parquet (chunk 99)

🎉 DONE: Predicted chunks using XGBoost

In [2]:
import polars as pl
from glob import glob
import json

# ===========================
# 1️⃣ Lấy danh sách file parquet
# ===========================
files = sorted(glob("prediction_3cols_all_files/customer_item_keys_chunk_*.parquet"))

# ===========================
# 2️⃣ Đọc và gộp tất cả các chunk
# ===========================
dfs = []
for f in files:
    df = pl.read_parquet(f)
    if df.height > 0:  # bỏ file rỗng
        dfs.append(df)

if not dfs:
    raise ValueError("Không có DataFrame nào được load!")

all_df = pl.concat(dfs)

# ===========================
# 3️⃣ Sort: customer_id ↑ , Y ↓
# ===========================
all_df = all_df.sort([
    pl.col("customer_id"), 
    pl.col("y_pred").reverse()  # Y giảm dần
])

# ===========================
# 4️⃣ Lấy top 10 item mỗi customer
# ===========================
top10_df = all_df.group_by("customer_id").head(10)

# ===========================
# 5️⃣ Gom item_id thành list
# ===========================
df_result = top10_df.group_by("customer_id").agg(
    pl.col("item_id").implode().alias("items")
)

# ===========================
# 6️⃣ Ghi JSON theo batch để tránh tràn RAM
# ===========================
BATCH_SIZE = 100_000
total = df_result.height

with open("submission2.json", "w", encoding="utf-8") as f:
    f.write("{\n")
    for start in range(0, total, BATCH_SIZE):
        batch = df_result.slice(start, BATCH_SIZE)
        for idx, row in enumerate(batch.iter_rows(named=True)):
            customer_id = str(row["customer_id"])
            items = row["items"]
            f.write(f'"{customer_id}": ')
            json.dump(items, f)
            if start + idx < total - 1:
                f.write(",\n")
    f.write("\n}")

print("✅ Đã xuất submission2.json – mỗi customer tối đa 10 item")

✅ Đã xuất submission2.json – mỗi customer tối đa 10 item

In [5]:
import pickle
import json
import numpy as np

def precision_at_k(pred, gt, hist=None, filter_bought_items=True, K=10):
    """
    pred: dict {customer_id: [item_id1, item_id2, ...]} - file submission
    gt: dict {customer_id: [item_id1, item_id2, ...]} - file groundtruth
    hist: dict {customer_id: [item_id1, ...]} - lịch sử mua của user, optional
    filter_bought_items: nếu True, loại bỏ các item đã mua trong history
    K: đánh giá top-K
    """
    precisions = []
    cold_start_users = []

    for user in gt.keys():
        if user not in pred:
            cold_start_users.append(user)
            continue

        gt_items = set(gt[user])
        if filter_bought_items and hist is not None and user in hist:
            gt_items -= set(hist[user])

        hits = len(set(pred[user][:K]) & gt_items)
        precisions.append(hits / K)

    mean_precision = np.mean(precisions) if precisions else 0.0
    return mean_precision, cold_start_users

# --- Load groundtruth ---
with open("final_groundtruth_clean.pkl", "rb") as f:
    groundtruth = pickle.load(f)

print(f"Số customer trong groundtruth: {len(groundtruth)}")

# --- Load submission ---
with open("submission/submission_without_hist.json", "r") as f:
    submission = json.load(f)

# Nếu keys trong submission là str mà groundtruth là int, chuyển sang int
try:
    submission_fixed = {int(k): v for k, v in submission.items()}
except ValueError:
    submission_fixed = submission  # giữ nguyên nếu không thể chuyển

print(f"Số customer trong submission: {len(submission_fixed)}")
 
# --- Tính precision@K ---
precision, cold_users = precision_at_k(submission_fixed, groundtruth, hist=None, K=10)
print(f"Precision@10: {precision:.6f}")
print(f"Số cold start users (không có dự đoán): {len(cold_users)}")

Số customer trong groundtruth: 644970
Số customer trong submission: 2094582
Precision@10: 0.034826
Số cold start users (không có dự đoán): 148385

In [34]:
import pickle
import json
import numpy as np
import pandas as pd

# ================= FUNCTION =================
def precision_at_k(pred, gt, hist=None, filter_bought_items=True, K=10, fill_cold_start=None):
    precisions = []

    for user in gt.keys():
        if user in pred:
            user_pred = pred[user][:K]
        else:
            if fill_cold_start is not None:
                user_pred = fill_cold_start[:K]
            else:
                user_pred = []

        gt_items = set(gt[user])
        if filter_bought_items and hist is not None and user in hist:
            gt_items -= set(hist[user])

        hits = len(set(user_pred) & gt_items)
        precisions.append(hits / K)

    return np.mean(precisions) if precisions else 0.0


# ================= LOAD GROUNDTRUTH =================
with open("final_groundtruth_clean.pkl", "rb") as f:
    groundtruth = pickle.load(f)

print(f"👥 Số customer trong groundtruth: {len(groundtruth)}")


# ================= LOAD SUBMISSION =================
with open("submission_without_hist.json", "r", encoding="utf-8") as f:
    submission = json.load(f)

# fix key type nếu cần
try:
    submission = {int(k): v for k, v in submission.items()}
except ValueError:
    pass

print(f"📁 Số customer trong submission gốc: {len(submission)}")


# ================= LOAD TOP ITEMS =================
top_items_df = pd.read_csv("top10_first_purchase_by_count.csv")
top_items = top_items_df["item_id"].tolist()


# ================= FILL COLD START (KHÔNG LOẠI CUSTOMER) =================

# 1️⃣ Giữ nguyên toàn bộ submission gốc
submission_filled = {
    user: items[:10]
    for user, items in submission.items()
}

# 2️⃣ Chỉ fill customer thiếu so với groundtruth
cold_start_count = 0
for user in groundtruth.keys():
    if user not in submission_filled:
        submission_filled[user] = top_items[:10]
        cold_start_count += 1

print(f"❄️ Cold-start customers được fill: {cold_start_count}")
print(f"✅ Tổng customer sau fill: {len(submission_filled)}")


# ================= SAVE FILLED SUBMISSION =================
with open("submission_without_hist_full.json", "w", encoding="utf-8") as f:
    json.dump(submission_filled, f, ensure_ascii=False)

print("💾 Đã lưu file submission_filled.json")


# ================= EVALUATE =================
precision = precision_at_k(
    submission_filled,
    groundtruth,
    hist=None,
    K=10,
    fill_cold_start=None   # đã fill rồi nên không cần nữa
)

print(f"🎯 Precision@10 (sau khi fill & lưu): {precision:.6f}")

👥 Số customer trong groundtruth: 644970
📁 Số customer trong submission gốc: 2094582
❄️ Cold-start customers được fill: 148385
✅ Tổng customer sau fill: 2242967
💾 Đã lưu file submission_filled.json
🎯 Precision@10 (sau khi fill & lưu): 0.026813

In [7]:
import pickle
import json
import numpy as np
import pandas as pd
def precision_at_k(pred, gt, hist=None, filter_bought_items=True, K=10):
    precisions = []
    cold_start_users = []
    per_user_result = []   # 👈 lưu kết quả từng user

    for user in gt.keys():
        if user not in pred:
            cold_start_users.append(user)
            continue

        pred_items = pred[user][:K]
        gt_items = set(gt[user])

        if filter_bought_items and hist is not None and user in hist:
            gt_items -= set(hist[user])

        hits = set(pred_items) & gt_items
        precision_u = len(hits) / K

        precisions.append(precision_u)

        per_user_result.append({
            "customer_id": user,
            "precision": precision_u,
            "pred_items": pred_items,
            "gt_items": list(gt_items),
            "hit_items": list(hits)
        })

    mean_precision = np.mean(precisions) if precisions else 0.0
    return mean_precision, cold_start_users, per_user_result


# ================= LOAD GROUNDTRUTH =================
with open("final_groundtruth_clean.pkl", "rb") as f:
    groundtruth = pickle.load(f)

print(f"👥 Số customer trong groundtruth: {len(groundtruth)}")


# ================= LOAD SUBMISSION =================
with open("submission/submission_without_hist.json", "r", encoding="utf-8") as f:
    submission = json.load(f)

# fix key type nếu cần
try:
    submission_fixed = {int(k): v for k, v in submission.items()}
except ValueError:
    submission_fixed = submission

print(f"📁 Số customer trong submission: {len(submission_fixed)}")


# ================= EVALUATE =================
precision, cold_users, per_user = precision_at_k(
    submission_fixed,
    groundtruth,
    hist=None,
    K=10
)

print(f"\n🎯 Precision@10 (overall): {precision:.6f}")
print(f"❄️ Số cold-start users: {len(cold_users)}")


# ================= TOP 2 CUSTOMER CÓ PRECISION CAO NHẤT =================
top_users = sorted(
    per_user,
    key=lambda x: x["precision"],
    reverse=True
)[:2]

print("\n🔥 TOP 2 CUSTOMER CÓ ĐỘ CHÍNH XÁC CAO NHẤT\n")

for i, u in enumerate(top_users, 1):
    print(f"#{i}")
    print(f"Customer ID : {u['customer_id']}")
    print(f"Precision   : {u['precision']:.2f}")
    print(f"Pred items  : {u['pred_items']}")
    print(f"GT items    : {u['gt_items']}")
    print("-" * 50)
# ================= IN 1 COLD-START USER =================
top_items_df = pd.read_csv("top10_first_purchase_by_count.csv")
top_items = top_items_df["item_id"].tolist()
if cold_users:
    cold_user = cold_users[0]   # lấy 1 user bất kỳ
    print("\n🧊 VÍ DỤ 1 COLD-START USER")
    print(f"Customer ID : {cold_user}")
    print(f"GT items    : {groundtruth[cold_user]}")
    print(f"pred        : {top_items}")
    
else:
    print("\n✅ Không có cold-start user nào")

👥 Số customer trong groundtruth: 644970
📁 Số customer trong submission: 2094582

🎯 Precision@10 (overall): 0.034826
❄️ Số cold-start users: 148385

🔥 TOP 2 CUSTOMER CÓ ĐỘ CHÍNH XÁC CAO NHẤT

#1
Customer ID : 1181664
Precision   : 1.00
Pred items  : ['4603024000002', '3047000000002', '3052000000001', '3880000000001', '5444000000016', '3880000000002', '4690000000001', '2798000000001', '2803000000011', '2803000000012']
GT items    : ['6796000000002', '2798000000001', '2803000000011', '3518000000157', '5427000000006', '3880000000001', '2278000000027', '4398000000004', '7115000000005', '1370000000012', '1371000000004', '5029000000006', '1371000000005', '2278000000042', '2982000000001', '2793000000004', '7238000000001', '1370000000014', '1371000000007', '3880000000002', '2950000000002', '5444000000016', '4690000000001', '5537000000001', '4603024000002', '1371000000001', '1370000000013', '3951000000228', '5444000000017', '1974000000006', '0029140000031', '4400000000005', '2278000000039', '2019000000001', '3944000000347', '2803000000012', '5420000000002', '1371000000006', '1371000000002', '3953000000427', '1371000000003', '6996000000122', '3052000000001', '3047000000002', '7115000000003', '5537000000003', '5420000000003', '0068000000080']
--------------------------------------------------
#2
Customer ID : 7155663
Precision   : 1.00
Pred items  : ['2803000000010', '2803000000012', '2798000000001', '0029120000029', '5599000000001', '6382000000004', '0020010000438', '5444000000016', '3880000000002', '3880000000001']
GT items    : ['2793000000003', '2798000000001', '5599000000001', '5868000000001', '2803000000011', '2610000000004', '3880000000001', '1455000000004', '6053000000050', '1920001360750', '2803000000013', '4020000000007', '1455000000003', '0020120000029', '5437000000001', '0020090000003', '0029140000027', '6792000000003', '0029130000025', '5857000000001', '3880000000002', '5506000000002', '0029120000029', '5444000000016', '2803000000012', '0008020000200', '5444000000018', '2803000000010', '0020010000438', '6382000000004']
--------------------------------------------------

🧊 VÍ DỤ 1 COLD-START USER
Customer ID : 30671
GT items    : ['4784000000003', '0007090000158', '0007090000157', '4783000000003', '3675000000001', '2700000000001', '4783000000002', '7097000000004', '1396000000018', '4783000000013', '1771000000001', '1771000000002']
pred        : [1512000000004, 1215000000002, 6766000000002, 5950000000001, 20010000210, 175000000007, 203000000004, 4603024000001, 4690000000001, 7090000252]